### ISSUE TITLE
VirtualBox VM created on Linux does not mount shared folders

### ISSUE THREAD

**Issue by jonocodes** [docker/machine#1376] opened 2015-06-17 16:01 UTC
Steps to reproduce (Ubuntu host):

> docker run --volume $HOME:/testhome busybox ls -laR /testhome

/testhome:
total 4
drwxr-xr-x    2 root     root            40 Jun 17 15:57 .
drwxr-xr-x   24 root     root          4096 Jun 17 15:57 ..

I would expect it to see a list of the files from my host home directory, but it shows and empty file list instead.

Looking at the code it appears there is support for this in Win and OSX, but not Linux yet.
https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L329

**Comment by UserTaken** [comment] 2015-06-17 18:45
When using the Docker Remote API, `$HOME` points to your Docker client's `$HOME` which may not exist on the server.

**Comment by thomasbilk** [comment] 2015-10-19 08:56
I am also running into this issue. I use `docker-machine` at work on a mac and wanted to use it on my personal linux (mint 17.2) notebook. 

Are there any plans to make this work on linux aswell?

**Comment by thomasbilk** [comment] 2015-10-19 09:31
I have looked into this a bit more and this is what I found. On Windows and Mac OS the `Users` folder from the host is shared with the `boot2docker` linux used by `docker-machine`. The `boot2docker` image is configured to automatically mount these shares, as described here: [Boot2Docker Readme](https://github.com/boot2docker/boot2docker/#virtualbox-guest-additions).  

The problem now is that `boot2docker` cannot mount the linux host `/home` into the vm `/home` since it is already there. The linked readme from above already contains some ideas to solve this issue. They are all feasible yet not very convenient.

**Comment by atomi** [comment] 2015-10-22 02:58
This issue seems like it should be more important and should be addressed for 0.5.0. I understand the boot2docker image had to be updated but sharing in Linux worked fine in release 0.4.0 rc2.

**Comment by nathanleclaire** [comment] 2015-10-23 00:36
I don't think it's a regression, if I remember correctly it was never supported at all.  It _was_ supported in some of the 0.4.0 RC binaries because we were considering moving to a new boot2docker OS which is based on Debian instead of TCL, and modified some Docker Machine code accordingly, including adding shared folder support for Linux.  I'm sorry to everyone who is wanting this feature and doesn't have it, hopefully we can add it soon, but it won't make it in for 0.5.0.

**Comment by bascht** [comment] 2015-10-23 04:26
@nathanleclaire So, out of sheer curiosity: Does that mean that though there *is* a Linux build, `docker-machine` isn't usable on Linux hosts yet? :)

**Comment by nathanleclaire** [comment] 2015-10-23 18:09
@bascht It's perfectly usable, there's just not support for VirtualBox shared folders on Linux yet.

**Comment by bascht** [comment] 2015-10-23 20:34
@nathanleclaire I might be at a loss here, but docker-machine was not usable for me as I couldn't access any files from inside the Container - which I created #2063 for. That project relies on a bind mount and I couldn't use docker-machine.

**Comment by nathanleclaire** [comment] 2015-10-23 20:45
@bascht Sounds like you can create, start/stop, and remove VMs fine, so to me `docker-machine` is usable, it just lacks the auto-mount feature on Linux.  We're not opposed to adding this feature, it just hasn't been a high priority and no one has driven a PR for it through to completion yet.

In the interim, you should be able to create the share and mount the share manually.

**Comment by chantra** [comment] 2015-10-30 03:24
@nathanleclaire here is a PR: #2122

**Comment by atomi** [comment] 2015-10-30 04:07
Haha 3 lines minus the VTX checking. If that's all, I think this should be in 0.5.0 to stay in parity.

**Comment by chantra** [comment] 2015-10-30 05:22
it also requires https://github.com/boot2docker/boot2docker/pull/1086 to be functional though

**Comment by atomi** [comment] 2015-10-30 06:01
That makes more sense.  Yea linked directories might being up race condition issues...

**Comment by dgageot** [comment] 2015-11-19 16:51
Fixed with https://github.com/docker/machine/pull/2122

**Closed by dgageot** 2015-11-19 16:51 UTC
Labels: driver/virtualbox

**Comment by JacobBrownAustin** [comment] 2018-08-21 20:53
I ran into this issue and it looks like `/home` is actually mounted as `/hosthome` in docker-machine.  

Therefore, if I run `docker run --volume /home/jacob:/testhome busybox ls -laR /testhome ` , it won't work.  

The work around is `docker run --volume /hosthome/jacob:/testhome busybox ls -laR /testhome`

I thought I should add this comment in case someone one else runs into this issue and could use a quick workaround.  Or if someone wants to fix this bug.
