### ISSUE TITLE
No download link to Docker Machine for Linux

### ISSUE THREAD

**Issue by stain** [docker/machine#1827] opened 2015-09-09 15:42 UTC
I've been trying to look at https://docs.docker.com/machine/ https://docs.docker.com/machine/get-started/ and https://docs.docker.com/linux/started/ and can't find a link to Download Docker Machine for Linux.

Is Docker Machine only available for OS X and Linux?

**Comment by stain** [comment] 2015-09-09 15:44
Linux description was at https://docs.docker.com/machine/install-machine/ - but there should be a link to this page from probably all 3 of the above pages.

**Comment by booyaa** [comment] 2015-09-09 16:26
Hi on the last page that you referenced, you download the command using curl `$ curl -L https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_linux-amd64 > /usr/local/bin/docker-machine`.

**Comment by booyaa** [comment] 2015-09-09 16:27
I wouldn't expect download links to be available in the intro documentation and getting started guides for machine.

**Comment by ehazlett** [comment] 2015-09-09 16:28
Yes we used to have a link to the GitHub releases.  I'm not sure what happened.  I will add that back.  For now, you can get the latest release at https://github.com/docker/machine/releases

**Comment by booyaa** [comment] 2015-09-09 16:38
hi again the download link is on install-machine page [web](https://docs.docker.com/machine/install-machine/)|[source](https://github.com/docker/machine/blob/master/docs/install-machine.md), it's in the first paragraph.

> Docker Machine is supported on Windows, OS X, and Linux and is installable as one standalone binary. The links to the binaries for the various platforms and architectures are available at the _Github Release_ page.

**Comment by nathanleclaire** [comment] 2015-09-09 19:46
I agree with the sentiment of this thread (installation of the binary directly should be clearer), but I'm closing this issue as a dupe of: https://github.com/docker/machine/issues/1680

**Closed by nathanleclaire** 2015-09-09 19:46 UTC
Labels: area/docs

**Comment by stain** [comment] 2015-09-13 05:06
I've commented on #1680. 

Once you hunt around in the menu and see "Install" and realize this also has a sub-menu for Docker Machine you are good to go, as it then includes the `curl` commands. 

The problem is finding the page https://docs.docker.com/machine/install-machine/ if you are on any of the Docker Machine pages. Just because it belongs under the global "Install" section does not mean that there shouldn't be cross-links to it from other sections.
