### ISSUE TITLE
Fix Cisco AnyConnect (or at least provide decent workaround)

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2101] opened 2015-10-27 22:04 UTC

**Comment by nathanleclaire** [comment] 2015-10-27 22:19
:+1:

**Comment by dmp42** [comment] 2015-10-28 01:49
Apparently available for download here: https://wiki.umms.med.umich.edu/display/UMHSHELPDESK/VPN+-+Cisco+AnyConnect+Client+for+Macintosh#VPN-CiscoAnyConnectClientforMacintosh-MacOSX10.6.8%2C10.7%2610.8

Successfully installed and ran it (be sure to disable everything but the "VPN" option).

**Comment by dgageot** [comment] 2015-11-02 13:51
Hi @dmp42, I'm not sure I understand your message here...

**Comment by sjwoodard** [comment] 2015-11-12 00:46
@dmp42, can you provide a description on this issue? Thanks.

**Comment by dmp42** [comment] 2015-11-12 01:10
@sjwoodard @nathanleclaire mentioned several people were having issues with VPN clients, specifically Cisco AnyConnect.

Right now, the guess is that such softwares are messing up with the host routing, and the first step would be to reproduce such an environment to test.

**Comment by dgageot** [comment] 2015-12-30 09:52
Closing duplicate of https://github.com/docker/machine/issues/2258

**Closed by dgageot** 2015-12-30 09:52 UTC
