### ISSUE TITLE
Unable to create VMware Fusion machine due to missing MAC address in vmx

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [docker/machine#1752] opened 2015-08-24 08:50 UTC
Hi :)

I've been trying to get `docker-machine create` to work. I'm on Capitan DP B7, and I've tried with both Fusion 7 latest stable, and the Fusion preview which is offically claimed to support Capitan beta. I've disabled rootless protection and `csrutil disable`d the OS in a recovery mode terminal.

Here's an example of what I'm looking at when trying to create a machine:

`$ docker-machine --debug create --driver vmwarefusion fusion --vmwarefusion-memory-size 2048
Creating SSH key...
Creating VM...
Creating disk '/Users/daniel/.docker/machine/machines/fusion/fusion.vmdk'
Virtual disk creation successful.
Starting fusion...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/daniel/.docker/machine/machines/fusion/fusion.vmx nogui
Waiting for VM to come online...
Not there yet 1/60, error: couldn't find MAC address in VMX file /Users/daniel/.docker/machine/machines/fusion/fusion.vmx
[... snip snap ...]
Not there yet 60/60, error: couldn't find MAC address in VMX file /Users/daniel/.docker/machine/machines/fusion/fusion.vmx
Error creating machine: Machine didn't return an IP after 120 seconds, aborting
You will want to check the provider to make sure the machine and associated resources were properly removed.`

Examining the VMX file, it doesn't say anything about MAC addresses, and AFAICT from the [source code](https://github.com/docker/machine/blob/master/drivers/vmwarefusion/fusion_darwin.go#L362), then indeed it is missing, as it should be picked up from `vmxparse := regexp.MustCompile(`^ethernet0.generatedAddress\s*=\s*"(.*?)"\s*$`)` — and there is no `ethernet0.generatedAddress` entry in `/Users/daniel/.docker/machine/machines/fusion/fusion.vmx`. However, this machine was created by `docker-machine` itself, so I'm puzzled as to why that line wouldn't be there?

I've noticed that if I try to run the VMX in Fusion manually, it'll ask me to upgrade the machine immediately (both with the stable Fusion 7, and the preview version), but I'm not sure if it's related...

Doing `open /Users/daniel/.docker/machine/machines/fusion/fusion.vmx` and saying yes to upgrade the machine, it'll boot into it, ending up at a `root@boot2docker` prompt. After that I'll get periodic `Failed to get vmstats` error on the guest's TTY. I've tried wrapping the vmrun bin in a bash script to automatically do `vmupgrade` on the machine first, in case that was the problem, but to no avail. The stdout and stderr of vmrun seems to be captured by docker-machine, even with `--debug`, so it's difficult to see what the underlying problem might be.

**Comment by DanielSmedegaardBuus** [comment] 2015-08-24 09:24
When manually directing outputs to a log file from a `vmrun` bash wrapper script (with --debug, why is output from vmrun still suppressed?) I get:

`/Users/daniel/.docker/machine/machines/fusion/fusion.vmx: Readlink /var/run/vmware/1e7eece2194f688cac8a6a6eb468919e failed: Permission denied
2015-08-24T11:19:47.052| ServiceImpl_Opener: PID 33548`

Makes sense, since
`$ stat /var/run/vmware/1e7eece2194f688cac8a6a6eb468919e`
`  File: ‘/var/run/vmware/1e7eece2194f688cac8a6a6eb468919e’stat: cannot read symbolic link '/var/run/vmware/1e7eece2194f688cac8a6a6eb468919e': Permission denied`
`  Size: 49        	Blocks: 8          IO Block: 4096   symbolic link`
`Device: 1000004h/16777220d	Inode: 7811412     Links: 1`
`Access: (0700/lrwx------)  Uid: (    0/    root)   Gid: (    1/  daemon)`
`Access: 2015-08-24 11:19:47.000000000 +0200`
`Modify: 2015-08-24 11:19:47.000000000 +0200`
`Change: 2015-08-24 11:19:47.000000000 +0200`
`  Birth: 2015-08-24 11:19:47.000000000 +0200`

**Comment by DanielSmedegaardBuus** [comment] 2015-08-24 09:34
`chown`ing `/var/run/vmware/*` to `$UID:$GID` just before doing `vmrun vmupgrade` makes that part succeed, but `vmrun start` fails with

`Cnx_CreateSocketDir: Failed to create user socket dir.`
`Failed to initialize VM.`

Seems like permissions issues again :/ Also, opening the VMX manually in Fusion still wants me to upgrade it, so `vmrun vmupgrade` "succeeding" is more like not erroring out :)

**Comment by DanielSmedegaardBuus** [comment] 2015-08-24 11:51
After fiddling around with permissions on `~/.docker` and `/var/run` with no success, I finally did a `sudo rm -rf /var/run/vmware* /var/run/VMware*`, and got further. It seems before every attempt, I had to do this to avoid erroring out. Or rather, since `docker-image create` doesn't act on non-zero exit codes, to get to where the image is (almost) created. I renamed Fusion's `vmrun` to `vmrun.bin` and created a BASH script in its place:

```sh
#!/bin/bash

cd "/Applications/VMware Fusion.app/Contents/Library"

touch ~/vmware.log

echo "=== Wrapping $0 $@ ..." >> ~/vmware.log

[[ "$1" = "start" ]] &&
    echo "=== House cleaning before run ..." >> ~/vmware.log &&
    sudo killall vmnet-netifup vmnet-dhcpd vmnet-natd vmnet-bridge vmware-vmx-debug vmware-usbarbitrator "VMware Fusion Services" "VMware Fusion" "VMware Fusion Start Menu" vmru$
    sudo rm -rf /var/run/vmware* &&
    sudo rm -rf /var/run/vmnet* &&
    sudo rm -rf /var/run/VMware*

echo "=== DOING ./vmrun.bin $@" >> ~/vmware.log
./vmrun.bin "$@" 2>> ~/vmware.log | tee -a ~/vmware.log

exit $?
```

And _finally_ I can create a working, running docker machine :) Of course, if anyone else runs into this issue before it's fixed and use my script there, make sure you replace it with the original `vmrun` binary afterwards ;) Also, you should run a `sudo` command before running it to make sure the `sudo`s in the script work properly — something like `sudo ls` will do.

**Comment by DanielSmedegaardBuus** [comment] 2015-08-24 13:53
Actually, it seems I can't use `docker-machine start fusion` afterwards so long as the `nogui` parameter is used. This appears to be some bug with VMware in Capitan ... Keeping the script in place and letting it strip out the `nogui` parameter from vmrun commands will open the boot2docker machine in the GUI VMware app, otherwise it'll fail to start.

**Comment by frapposelli** [comment] 2015-08-24 14:48
Seems like the original problem with `docker-machine` ("couldn't find MAC address in VMX file") is due to Fusion not being able to start up itself correctly with the `nogui` params that is used with the `vmrun` command.

Unfortunately I don't have a system with El Capitan installed at this moment, but I know the fusion team released a Fusion 8 technical preview a few weeks ago, it may be worth a try (haven't tested myself so YMMV): https://communities.vmware.com/community/vmtn/fusion/vmware-fusion-technology-preview-2015

**Comment by DanielSmedegaardBuus** [comment] 2015-08-25 06:35
That's the conclusion I came to as well :)

I'm already running the preview... But I'm thinking perhaps my turning off SIP might have had adverse side effects. I went to Disk Utility to run a permissions repair, only to find that "it's no longer necessary because of SIP". Eek :D

**Comment by frapposelli** [comment] 2015-08-25 14:30
@DanielSmedegaardBuus can you please run this for me?

- Fresh El Capitan install
- Docker-Machine compiled from `HEAD`
- Fusion 7.1.2 or 8 TP

Run a `docker-machine create` (the one that fails with "couldn't find MAC address in VMX file") and send me the `vmware.log` that is created.

**Comment by mwl** [comment] 2015-08-25 15:17
Having what I believe is the same issue as @DanielSmedegaardBuus, I did a `create` with latest Fusion 8.0.0 (2985594) and El Capitan 10.11 Beta (15A263e) from Docker Machine HEAD 0.5.0-dev (816d602) with the following result

```
DEBUG=1 ./docker-machine_darwin-amd64 create --driver=vmwarefusion test
Creating SSH key...
Creating VM...
Creating disk '/Users/mwl/.docker/machine/machines/test/test.vmdk'
Virtual disk creation successful.
Starting test...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/mwl/.docker/machine/machines/test/test.vmx nogui
Waiting for VM to come online...
Not there yet 1/60, error: couldn't find MAC address in VMX file /Users/mwl/.docker/machine/machines/test/test.vmx
Not there yet 2/60, error: couldn't find MAC address in VMX file /Users/mwl/.docker/machine/machines/test/test.vmx
Not there yet 3/60, error: couldn't find MAC address in VMX file /Users/mwl/.docker/machine/machines/test/test.vmx
…
Not there yet 60/60, error: couldn't find MAC address in VMX file /Users/mwl/.docker/machine/machines/test/test.vmx
Error creating machine: Machine didn't return an IP after 120 seconds, aborting
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

And ~/vmware.log
```
=== Wrapping /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/mwl/.docker/machine/machines/test/test.vmx nogui ...
=== House cleaning before run ...
=== DOING ./vmrun.bin start /Users/mwl/.docker/machine/machines/test/test.vmx nogui
2015-08-25T16:11:36.240| ServiceImpl_Opener: PID 4550
Error: The operation was canceled
```

**Comment by frapposelli** [comment] 2015-08-25 15:32
@mwl I need the `vmware.log` that is at `/Users/mwl/.docker/machine/machines/test/vmware.log`.

**Comment by mwl** [comment] 2015-08-25 15:43
@frapposelli I think my issues above might have been a general fusion issue that goes away with a restart.
With the same setup I now get the following result

```
DEBUG=1 docker-machine create --driver=vmwarefusion test
Creating SSH key...
Creating VM...
Creating disk '/Users/mwl/.docker/machine/machines/test/test.vmdk'
Virtual disk creation successful.
Starting test...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun start /Users/mwl/.docker/machine/machines/test/test.vmx nogui
Waiting for VM to come online...
MAC address in VMX: 00:0c:29:90:3b:a5
IP found in DHCP lease table: 192.168.76.130
Got an ip: 192.168.76.130
Creating Tar key bundle...
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser directoryExistsInGuest /Users/mwl/.docker/machine/machines/test/test.vmx /var/lib/boot2docker
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/mwl/.docker/machine/machines/test/test.vmx /Users/mwl/.docker/machine/machines/test/userdata.tar /home/docker/userdata.tar
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/mwl/.docker/machine/machines/test/test.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar && sudo tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1 && sudo chown -R docker:staff /home/docker
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser enableSharedFolders /Users/mwl/.docker/machine/machines/test/test.vmx
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser addSharedFolder /Users/mwl/.docker/machine/machines/test/test.vmx Users /Users
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/mwl/.docker/machine/machines/test/test.vmx /bin/sh sudo mkdir /Users && sudo mount -t vmhgfs .host:/Users /Users
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
…
executing: /Applications/VMware Fusion.app/Contents/Library/vmrun list
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

And ~/.docker/machine/machines/test/vmware.log, https://gist.github.com/mwl/e1dde29ea5dead592709

**Comment by frapposelli** [comment] 2015-08-25 20:21
@mwl I think I found your problem, from your `vmware.log`:

```
2015-08-25T16:30:41.797Z| vcpu-0| I125: [msg.vnet.padrConflict] MAC address 00:0C:29:90:3B:A5 of adapter 'Ethernet0' is within the reserved address range or is in use by another virtual adapter on your system. Adapter 'Ethernet0' may not have network connectivity.
```

The error is pretty telling, apparently your Fusion network configuration is corrupted, I suggest you to properly uninstall/reinstall fusion (there's a script for that), that will rebuild the virtual network config and should fix your problem.

Your `docker-machine create` command fails because it tries to connect via SSH to configure the docker daemon (technically that is done by `libmachine` and not the `vmwarefusion` driver) while all the previous command are done through VMware tools and don't require network connectivity.

**Comment by geek** [comment] 2015-08-25 20:44
I had the same issue on a fresh install of docker/docker-machine and vmware fusion 8.  The solution was to restart the computer as @mwl points out.

**Comment by geek** [comment] 2015-08-25 21:07
@frapposelli I have the same issue with vmware fusion 8, a fresh install of docker and docker-machine.  I have the same error in my vmware.log about `padrConflict`.

**Comment by frapposelli** [comment] 2015-08-25 21:07
@geek are you on El Capitan as well?

**Comment by geek** [comment] 2015-08-25 21:08
Nope, on Yosemite

**Comment by mwl** [comment] 2015-08-25 21:25
@frapposelli Thanks for input. I did a complete reinstall of Fusion 8 as per http://kb.vmware.com/selfservice/search.do?cmd=displayKC&docType=kc&docTypeID=DT_KB_1_1&externalId=1017838 with the following result in vmware.log: https://gist.github.com/mwl/c993a9e940bf14e1230d

Command line output from the create command looks to be exactly the same. Still failing after one minut of `vmrun list`

**Comment by geek** [comment] 2015-08-26 19:51
@mwl or @frapposelli any luck getting further on this issue?

**Comment by frapposelli** [comment] 2015-08-27 15:46
This looks like a duplicate of #1671 /cc: @ehazlett

**Comment by dgageot** [comment] 2016-01-26 16:51
Duplicate of https://github.com/docker/machine/issues/1671

**Closed by dgageot** 2016-01-26 16:51 UTC
Labels: driver/vmwarefusion
