### ISSUE TITLE
Windows 10: blocking ssh keys management (docker-machine 0.7.0-rc4)

### ISSUE THREAD

**Issue by VonC** [docker/machine#3292] opened 2016-04-11 11:24 UTC
docker-machine 0.7.0-rc4, docker 11-rc3 on Windows 10 with VirtualBox 5.0.14 or 5.0.16

I can no longer list machines with docker-machine:

````
C:\prgs\dm>dm ls
NAME       ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
test       *        virtualbox   Running                 Unknown   Permissions 0666 for 'C:\Users\vonc\.docker\machine\machines\blessed\id_rsa' are too open.
default    *        virtualbox   Running                 Unknown   Permissions 0666 for 'C:\Users\vonc\.docker\machine\machines\default\id_rsa' are too open.
````

That is because of https://github.com/docker/machine/blame/5b9663f8960af73c048e14cc60566ae487c07728/libmachine/ssh/client.go#L335, commit https://github.com/docker/machine/commit/f2acfa9492d9352edeb722ba625adaf86bcdee7e

It uses `os.Stat()` (https://golang.org/src/os/stat_windows.go) which wraps a calls to https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946%28v=vs.85%29.aspx

That maps poorly with POSIX permission, and setting a Windows file to 600 (instead of the default 644) is difficult/impossible (I tried http://stackoverflow.com/q/5264595/6309 or http://superuser.com/a/318176/141)

Note: openssh (from git-for-windows or for cygwin) does work even if 'ls' (also packaged with git-for-windows) sees the certificates as 644, not 600: I can ssh with ssh.exe, not with docker-machine 0.7.0-rc4 (I can with docker-machine 0.6.0 obviously, since commit https://github.com/docker/machine/commit/f2acfa9492d9352edeb722ba625adaf86bcdee7e was not there)

Even if I recompile docker-machine by removing that test, docker-machine ls still does not work (but any ssh access/copy does work). It will list the machines with the warning/error `certificate signed by unknown authority` message. (I'll open another issue for that: regenerating the certs does not change the SAN in the tls/server.pem)

**Comment by nathanleclaire** [comment] 2016-04-11 20:59
I've seen this issue as well.  Should we set the permissions to 644 for Windows?

**Comment by VonC** [comment] 2016-04-11 21:40
@nathanleclaire I am not sure you can set any specific protection mode on Windows. I just removed that test (for Windows only) in my compiled version.

**Comment by nathanleclaire** [comment] 2016-04-11 21:51
Oh, so if you remove the stat check, it works fine?

**Comment by VonC** [comment] 2016-04-11 21:55
Yes, it does manage to contact the machine.

**Comment by nathanleclaire** [comment] 2016-04-11 21:58
Hmm... Messy ... @mmalchuk, FYI, https://github.com/docker/machine/commit/f2acfa9492d9352edeb722ba625adaf86bcdee7e is causing this issue on Windows, it will need to be fixed by the release.  I will look into it if needed or if you can submit changes to fix it, that would be great as well.

**Comment by nathanleclaire** [comment] 2016-04-11 22:17
Since I can verify that `f2acfa9` has caused a regression, I'm going to go ahead and revert it, and we can followup to add it back it in with the regression fixed.

**Closed** 2016-04-11 22:17 UTC

**Comment by mmalchuk** [comment] 2016-04-12 08:57
@nathanleclaire this mess because we need to run CI on Windows OS too)
The new fix is ready.

**Comment by nathanleclaire** [comment] 2016-04-12 18:25
@mmalchuk Yes, agreed, our test surface could always grow larger than what we have today.

**Comment by mmalchuk** [comment] 2016-04-12 18:33
@nathanleclaire what about the new fix https://github.com/docker/machine/pull/3296 ?

**Comment by nathanleclaire** [comment] 2016-04-12 18:52
@mmalchuk Code looks good, just have to give it a whirl and verify that the issue is fixed.

**Comment by VonC** [comment] 2016-04-18 22:01
@nathanleclaire @mmalchuk Sorry for the late feedback. 

I just wanted to thank you both: I have been using docker 1.11 final extensively for the past 4 days: it does work without any issue when it comes to docker machine and ssh on Windows.

**Comment by nathanleclaire** [comment] 2016-04-18 22:06
@VonC 👍
