### ISSUE TITLE
google: --google-use-internal-ip creates external IP too

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#2876] opened 2016-01-19 20:57 UTC
Hi, I'm trying to understand the [`--google-use-internal-ip`](https://docs.docker.com/machine/drivers/gce/) argument. Is it created for using private IP instead of public IP in machine OR not having an external IP for the machine altogether?

I assumed this would not create a public IP and make the machine secure within the private network but it doesn't work that way. So I'm trying to understand the motive here.

**Comment by dgageot** [comment] 2016-01-19 21:02
Hi @ahmetalpbalkan, if I recall correctly, VMs on GCE have an internal IP and have an optional ephemeral or reserved public IP. 
The ` --google-use-internal-ip` flag configures the VM to use its private IP only.

The motive here is to create private VMs that are not reachable from the Internet.

Did you encounter a different behaviour?

**Comment by ahmetalpbalkan** [comment] 2016-01-19 21:45
Yes I encountered a different behavior. External IP gets created for the instance from what I tell from the management console.

**Comment by daehyeok** [comment] 2016-01-20 21:38
I'm quick look the source code.  ```--google-use-internal-ip``` option not affect when instance created. I think it's easy to patch to create inter only machine. but how to progress provision after create machine without reachable ip when it executed in the external network(internet)?

**Comment by ahmetalpbalkan** [comment] 2016-01-21 02:00
I think --use-internal-ip is only usable when you're inside a Google Cloud
instance and in that network you are trying to create the new machine. That
is the only way provisioning would proceed.
On Wed, Jan 20, 2016 at 1:39 PM Daehyeok Mun <notifications@github.com>
wrote:

> I'm quick look the source code. --google-use-internal-ip option not
> affect when instance created. I think it's easy to patch to create inter
> only machine. but how to progress provision after create machine without
> reachable ip when it executed in the external network(internet)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/2876#issuecomment-173368190>.
>
-- 
—Ahmet Alp Balkan

**Comment by dgageot** [comment] 2016-01-21 06:00
@ahmetalpbalkan yes, that's it. When you create Docker Machine hosts from inside Google's network, maybe you to reach them through their internal IP but still have an external IP to expose services.

**Comment by daehyeok** [comment] 2016-01-21 19:55
Okay. If nobody interesting implement or fix code. I will try.

**Comment by ahmetalpbalkan** [comment] 2016-01-22 09:21
@daehyeok I don't think there is anything to fix here.

amazonec2 driver has both `amazonec2-use-private-address`, `amazonec2-private-address-only` flags. I can imagine one just says use private address in swarm or `docker-machine ip` command. The other one says “don't even create a public IP, I'm not going to run any public-facing servers on this instance”. 

google simply does not have this, it may be a design decision or simply a lacking feature. Up to you really if you would like to add the feature.

**Comment by dgageot** [comment] 2016-01-25 21:24
@ahmetalpbalkan, @daehyeok I'm going to close this ticket since it's really a feature and not a bug. Feel free to create another ticket (with a reference to this ticket) if you want flags similar to `amazonec2-use-private-address`, `amazonec2-private-address-only`

**Closed by dgageot** 2016-01-25 21:24 UTC
Labels: driver/google, kind/question
