### ISSUE TITLE
/dev/sda1 not mounted on new VirtualBox machine

### ISSUE THREAD

**Issue by marceldegraaf** [docker/machine#2508] opened 2015-12-07 09:35 UTC
I created a new VirtualBox machine with `docker-machine create -d virtualbox dev`. Pulling a Docker image on this fresh machine fails almost immediately with `no space left on device` errors.

Closer inspection reveals that `/mnt/sda1/var/lib/docker/aufs` is mounted on `tmpfs`, which is only ~900MB in size. However, I expect to see that folder mounted on `/dev/sda1`, the VirtualBox hard disk.

The same problem is referenced in #1928.

**Version info**:
```
$ docker-machine -v
docker-machine version 0.5.1 (HEAD)

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Disk space on `dev` machine**:
```
$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.6M    124.2M    772.3M  14% /
tmpfs                   498.1M         0    498.1M   0% /dev/shm
cgroup                  498.1M         0    498.1M   0% /sys/fs/cgroup
none                    464.8G    339.8G    125.0G  73% /Users
tmpfs                   896.6M    124.2M    772.3M  14% /mnt/sda1/var/lib/docker/aufs
```

**Mounts on `dev` machine**:
```
$ mount
tmpfs on / type tmpfs (rw,relatime,size=918096k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
none on /Users type vboxsf (rw,nodev,relatime)
tmpfs on /mnt/sda1/var/lib/docker/aufs type tmpfs (rw,relatime,size=918096k)
```

**Comment by marceldegraaf** [comment] 2015-12-07 10:13
Interestingly, when I recreated the machine with the following command, I did get a mounted `/dev/sda1` on `/mnt/sda1/var/lib/docker/aufs`. Not sure how those extra options would matter.

```
docker-machine create -d virtualbox --virtualbox-disk-size "15000" --virtualbox-memory "2048" dev
```

**Comment by jeanlaurent** [comment] 2016-01-25 13:14
Closing as duplicate of #1928 
Linking there for reference of the detailed output and workaround using flags.

Please feel free to re-open if I missed something.

**Closed** 2016-01-25 13:14 UTC
Labels: driver/virtualbox
