### ISSUE TITLE
5000ms are added to all requests done using a local hostname from /etc/hosts - running on OSX

### ISSUE THREAD

**Issue by motin** [docker/machine#2055] opened 2015-10-22 08:15 UTC
Using docker-machine 1.4.2 (migrated from boot2docker using the Docker toolbox installer) and experiencing a 5000ms extra latency on all requests done using a local hostname from /etc/hosts. 

Steps to reproduce:

Use the following docker-compose.yml:

    web:
      image: tutum/hello-world
      ports:
        - "80"

Add to /etc/hosts locally:

    192.168.99.100 docker.local

Fire up the stack and make a request from outside the docker machine:

    $ docker-compose up -d
    Starting 5000mslatency_web_1...
    $ docker-compose ps
           Name                      Command               State           Ports
    ------------------------------------------------------------------------------------
    5000mslatency_web_1   /bin/sh -c php-fpm -d vari ...   Up      0.0.0.0:32897->80/tcp
    $ date && time curl -v http://docker.local:32897/
    Tor 22 Okt 2015 10:12:17 CEST
    *   Trying 192.168.99.100...
    * Connected to docker.local (192.168.99.100) port 32897 (#0)
    > GET / HTTP/1.1
    > Host: docker.local:32897
    > User-Agent: curl/7.44.0
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Server: nginx/1.6.2
    < Date: Thu, 22 Oct 2015 08:12:22 GMT
    < Content-Type: text/html; charset=UTF-8
    < Transfer-Encoding: chunked
    < Connection: keep-alive
    < X-Powered-By: PHP/5.6.8
    <
    <html>
    <head>
        <title>Hello world!</title>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <style>
        body {
            background-color: white;
            text-align: center;
            padding: 50px;
            font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
        }

        #logo {
            margin-bottom: 40px;
        }
        </style>
    </head>
    <body>
        <img id="logo" src="logo.png" />
        <h1>Hello world!</h1>
        <h3>My hostname is 86b59404553c</h3>	</body>
    </html>
    * Connection #0 to host docker.local left intact

    real	0m5.038s
    user	0m0.004s
    sys	0m0.005s

Then, run it directly against the IP and see that there is no 5000ms latency:

    $ date && time curl -v http://192.168.99.100:32897/
    Tor 22 Okt 2015 10:32:51 CEST
    *   Trying 192.168.99.100...
    * Connected to 192.168.99.100 (192.168.99.100) port 32897 (#0)
    > GET / HTTP/1.1
    > Host: 192.168.99.100:32897
    > User-Agent: curl/7.44.0
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Server: nginx/1.6.2
    < Date: Thu, 22 Oct 2015 08:32:51 GMT
    < Content-Type: text/html; charset=UTF-8
    < Transfer-Encoding: chunked
    < Connection: keep-alive
    < X-Powered-By: PHP/5.6.8
    <
    <html>
    <head>
      <title>Hello world!</title>
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
      <style>
      body {
        background-color: white;
        text-align: center;
        padding: 50px;
        font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
      }
    
      #logo {
        margin-bottom: 40px;
      }
      </style>
    </head>
    <body>
      <img id="logo" src="logo.png" />
      <h1>Hello world!</h1>
      <h3>My hostname is 86b59404553c</h3>	</body>
    </html>
    * Connection #0 to host 192.168.99.100 left intact
    
    real	0m0.011s
    user	0m0.003s
    sys	0m0.003s

When running from inside the docker-machine, there is no extra latency, with or without a local hostname in the query.

**Comment by motin** [comment] 2015-10-22 17:51
This could be a more general VirtualBox DNS issue, not related directly to docker-machine, but I have never experienced a slow-down like this before installing docker-machine. Also, changing DNS servers to google's 8.8.8.8 locally and/or in the docker-machine has no difference on the latest.

**Comment by nathanleclaire** [comment] 2015-10-22 18:14
Thanks for filing the issue -- I can dupe, but don't know what the problem is.  I'll look into it more and report back any findings here.

**Comment by nathanleclaire** [comment] 2015-10-22 18:16
My guess is that the `.local` TLD is problematic.  Changing the entry to `docker` or `docker.dev` for me makes it resolve at normal speeds, it's just `docker.local` which adds the extra 5s overhead.

**Comment by nathanleclaire** [comment] 2015-10-22 18:23
Since the issue doesn't seem related to Machine (other hostnames work fine), I'm closing this.

**Closed by nathanleclaire** 2015-10-22 18:23 UTC

**Comment by motin** [comment] 2015-10-22 23:39
Thanks @nathanleclaire great find! There are workarounds and solutions to the issue with .local host names here: http://stackoverflow.com/questions/10064581/how-can-i-eliminate-slow-resolving-loading-of-localhost-virtualhost-a-2-3-secon

**Comment by nathanleclaire** [comment] 2015-10-22 23:57
:+1:
