### ISSUE TITLE
docker-machine don't start VM

### ISSUE THREAD

**Issue by marioidival** [docker/machine#1223] opened 2015-05-24 13:34 UTC
![VM don't Start](https://cloud.githubusercontent.com/assets/1129263/7788042/859b64fa-0200-11e5-91f6-265e73306d35.png)

**Comment by marioidival** [comment] 2015-05-25 13:39
@mattetti

**Comment by efrecon** [comment] 2015-05-25 19:03
Probably the same as #986. As far as I can understand, this has been fixed in the master branch.

**Comment by marioidival** [comment] 2015-05-25 21:16
@efrecon 
I watched in virtualbox, while the docker-machine stood on this screen (I sent in the screenshot). The virtualbox has a preview area where you can watch what is going on in the virtual machine. And in a moment, the distro (boot2docker) completes the boot process and is expecting login and password. Maybe this can help.

**Comment by legal90** [comment] 2015-05-27 10:24
I have the same issue, but it is not related to #986. 
It is caused by 9bf78124733d4bd15a90d7aead80046a568b3cf2 (because the build from the previous commit, 74de38d97fb02af6c4e83378093cbd88ee3bd1d4, works fine)

Look at the part of debug log (reproduced on 9bf78124733d4bd15a90d7aead80046a568b3cf2):

```
$ docker-machine create -d virtualbox b2d-vbox2 --debug
<...>
Using SSH client type: external
About to run SSH command:
sudo /etc/init.d/docker start
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -t -i /Users/legal/.docker/machine/machines/b2d-vbox2/id_rsa -p 57837 docker@localhost sudo /etc/init.d/docker start] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: hostname: b2d-vbox2: Resolver internal error
Need TLS certs for b2d-vbox2,,10.0.2.15,192.168.99.103
-------------------

Daemon not responding yet: dial tcp 192.168.99.103:2376: connection refused
Daemon not responding yet: dial tcp 192.168.99.103:2376: connection refused
Daemon not responding yet: dial tcp 192.168.99.103:2376: connection refused
Daemon not responding yet: dial tcp 192.168.99.103:2376: connection refused
<...>
Error creating machine: Maximum number of retries (60) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.
```
Actually, vm is created and we can access it by ssh, but `sudo netstat -anp | grep 23` returns nothing, which means that docker daemon is not running. We can run it manually:
```
docker@b2d-vbox2:$ sudo /etc/init.d/docker start
hostname: b2d-vbox2: Resolver internal error
Need TLS certs for b2d-vbox2,,10.0.2.15,192.168.99.103
-------------------

docker@b2d-vbox2:~$ sudo netstat -anp | grep 23
tcp        0      0 :::2376                 :::*                    LISTEN      1682/docker
```
cc:/ @efrecon

**Comment by efrecon** [comment] 2015-05-27 11:33
Then I have no idea, you will have to wait for some more knowledgeable people from docker to look into this.

**Comment by legal90** [comment] 2015-05-27 11:40
@ehazlett Could you please take look at this? Seems like it is caused by #1090

**Comment by ehazlett** [comment] 2015-05-27 11:50
Yes taking a look.

**Comment by ehazlett** [comment] 2015-05-27 11:51
It is the tty allocation in the ssh command needed for redhat provisioning. We are working on a fix.

**Closed** 2015-05-27 12:39 UTC
Labels: in progress
