### ISSUE TITLE
Release artefact names should follow covnetion used in Compose

### ISSUE THREAD

**Issue by errordeveloper** [docker/machine#985] opened 2015-04-09 16:20 UTC
To get Compose, I run
```
curl -L https://github.com/docker/compose/releases/download/1.2.0rc3/docker-compose-`uname -s`-`uname -m`
```

where expanded URL is
```
https://github.com/docker/compose/releases/download/1.1.0/docker-compose-Darwin-x86_64
```

With Machine, I cannot do the same, as URLs look like
```
https://github.com/docker/machine/releases/download/v0.2.0-rc3/docker-machine_darwin-amd64
```

So first of all it's the way OS/architecture prefix is. Secondly, there is the `1.2.0rc3` vs `v0.2.0-rc3`, which is somewhat less annoying.

**Comment by ehazlett** [comment] 2015-04-10 13:17
Thanks for the feedback.  Closing as a duplicate of #494.  We will get this on the 0.3.0 milestone for the next release.  As for the versioning (rc, etc), we use the same convention as the docker engine and swarm.

**Closed by ehazlett** 2015-04-10 13:17 UTC

**Comment by errordeveloper** [comment] 2015-04-10 13:35
Makes sense. So it's a in issue with Compose not using the same convention.
