### ISSUE TITLE
machine config files do not support ~ expansion

### ISSUE THREAD

**Issue by sneak** [docker/machine#3298] opened 2016-04-12 15:59 UTC
I'm synchronizing a `~/.docker` between my two workstations, but the problem is that the machine config files specify all of their paths as absolute, which is `/Users/jp/.docker`... on one machine and `/home/sneak/.docker`... on another.  Adding and using these paths relative to $HOME, or supporting the `~` or `$HOME` shell expansions would be beneficial for this use case.

**Comment by nathanleclaire** [comment] 2016-04-12 20:24
Going to close this as a dupe of: https://github.com/docker/machine/issues/2516

**Closed by nathanleclaire** 2016-04-12 20:24 UTC
