### ISSUE TITLE
wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by asethia** [docker/machine#2836] opened 2016-01-14 07:38 UTC
every time when I am trying to run docker-machine I am getting following error

Docker Machine Version:  0.5.5, build 02c4254
Found binary path at d:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:56088
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Found binary path at d:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:56092
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.12r104815
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(default) DBG | Couldn't check that VT-X/AMD-v is enabled. Will check that the vm is properly created: exit status 2147749911
(default) DBG | local Boot2Docker ISO version:  v1.9.1
Error creating machine: Error with pre-create check: read tcp 127.0.0.1:56093->127.0.0.1:56092: wsarecv: An existing connection was forcibly closed by the remote host.

It is on windows 7 (64 bit)

**Comment by nathanleclaire** [comment] 2016-01-15 00:14
Hi @asethia thanks for the issue.  Can you please try it with this binary: https://www.dropbox.com/s/gfn4ow147e3xzbc/docker-machine_windows-amd64.exe?dl=1 and post the same output.  It is a fairly recent build from master and should hopefully at least give more useful information for the error.

**Comment by asethia** [comment] 2016-01-16 05:13
Thanks It worked... any reason why I can't use "docker toolbox"

**Comment by asethia** [comment] 2016-01-16 06:27
now I tried VirtualBox "4.3.34" with "DockerToolbox-1.9.1h" , It is working great. It looks like it is problem with virtual box 5.0 with docker tool box 1.9 (docker-machine version 0.5.5, build 02c4254).

**Comment by dgageot** [comment] 2016-01-18 08:01
Hi @asethia can you try Docker Machine 0.5.6? It contains workarounds to virtualbox bugs.

**Comment by dgageot** [comment] 2016-02-12 06:12
Duplicate of https://github.com/docker/machine/issues/2318

**Closed by dgageot** 2016-02-12 06:12 UTC
Labels: area/windows, driver/virtualbox

**Comment by Pa1sathvik** [comment] 2018-02-12 11:09
Hi ,
I tried with all host ip's, but still  i am getting this error.
below is my .ini file details.

enabled = true
host = smtp.gmail.com:465
user =ses*****@gmail.com
# If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
password =
;cert_file =
;key_file =mail.smtp.host
;skip_verify = false
from_address = se*****@gmail.com
from_name = vsathvik
# EHLO identity in SMTP dialog (defaults to instance_name)
;ehlo_identity = dashboard.example.com
