### ISSUE TITLE
Virtualbox arguments are not used and do not error if passed after machine name

### ISSUE THREAD

**Issue by philwinder** [docker/machine#1535] opened 2015-07-16 11:27 UTC
What I see:
```
docker-machine create -d virtualbox dev --virtualbox-memory 4096 --virtualbox-cpu-count 2
docker-machine inspect dev                                                               
{
    "DriverName": "virtualbox",
    "Driver": {
        "IPAddress": "192.168.99.100",
        "CPU": 1,
        "MachineName": "dev",
        "SSHUser": "docker",
        "SSHPort": 61782,
        "Memory": 1024,
...

docker-machine create -d virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count 2 dev
docker-machine inspect dev                                                               
{
    "DriverName": "virtualbox",
    "Driver": {
        "IPAddress": "192.168.99.100",
        "CPU": 2,
        "MachineName": "dev",
        "SSHUser": "docker",
        "SSHPort": 61950,
        "Memory": 4096,
```

I would expect that the first command should either use the parameters, or error to say that they haven't been read.

docker-machine version 0.3.0 (0a251fe)

**Comment by ehazlett** [comment] 2015-07-16 15:02
Thanks for the feedback.  Due to the way the CLI library we use handles the args, you must pass all driver flags before the machine name arg.  Also I'm not sure with the `--` after the machine name arg that we will be able to tell what is a driver flag or not due to the terminator.  Not sure though.

**Comment by nathanleclaire** [comment] 2015-07-20 17:38
> Due to the way the CLI library we use handles the args, you must pass all driver flags before the machine name arg. 

Yeah, I'm not sure if this is a codegansta/cli bug or expected behavior.  I have seen users run into this before, so I definitely think we should give some thought to erroring out if the name isn't the last argument, or something equivalent.

**Comment by dgageot** [comment] 2015-10-14 12:12
Duplicate of #1914. Closing

**Closed by dgageot** 2015-10-14 12:12 UTC
