### ISSUE TITLE
docker machine upgrade from 1.9.1 to 1.10.* on Azure, does not upgrade

### ISSUE THREAD

**Issue by NoamB** [docker/machine#3058] opened 2016-02-14 10:35 UTC
Hi,

Been trying over the last few days to upgrade Azure VMs (Ubuntu 14.04.3 LTS) using toolbox 1.10 and 1.10.1 with no success.
Upgrade seems to go without an error, however `docker-machine ls` shows no change in docker version on the node (still shows 1.9.1).

**Comment by benzimmer** [comment] 2016-02-20 11:49
I have the same problem. The only lead I can give comes from the debug log during the run:

`rm: cannot remove '/etc/apt/sources.list.d/docker.list': No such file or directory`

The rest looks rather normal.

It also seems that this is also not working on ec2: #3079

**Comment by dogik** [comment] 2016-02-22 20:40
+1
Ubuntu 14.04.2 LTS. Driver - generic. Same error:
```
SSH cmd err, output: <nil>: rm: cannot remove ‘/etc/apt/sources.list.d/docker.list’: No such file or directory
```

@NoamB Thanks for posting this. In lights of the Can you please change `driver/azure` to `driver/all` label? Thanks.

**Comment by ahmetalpbalkan** [comment] 2016-03-15 21:29
This is duplicate of #3014 and similar to #3009. Probably not specific to `driver/azure` at all.

**Comment by nathanleclaire** [comment] 2016-04-14 22:24
Please try #3308 (comment), and open a new issue if that does not help you upgrade.

**Closed by nathanleclaire** 2016-04-14 22:24 UTC
Labels: area/upgrade, driver/azure
