### ISSUE TITLE
Cannot create host-only adapter with VBox 5 on Windows 10 (using administrative shell)

### ISSUE THREAD

**Issue by hheimbuerger** [docker/machine#1521] opened 2015-07-14 08:52 UTC
Environment:
 * Windows 10 build 10162 (basically the RC1)
 * VirtualBox 5.0 (final)
 * docker-machine latest as of 2015-07-13 (downloaded from the [nightly builds](https://docker-machine-builds.evanhazlett.com/latest/), because VBox 5 needs [this fix](https://github.com/docker/machine/commit/8089e222c36aaeaee127e5f919d348b51d180b9c))

In an administrative command prompt (`Win-X -> Command Prompt (Admin)`), trying to create a VirtualBox boot2docker vm fails when attempting to create a host-only adapter:

    C:\Users\myuser\Downloads>docker-machine_windows_amd64.exe create --driver virtualbox dev -D
    Creating CA: C:\Users\myuser\.docker\machine\certs\ca.pem
    Creating client certificate: C:\Users\myuser\.docker\machine\certs\cert.pem
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe
    STDOUT: Oracle VM VirtualBox Command Line Management Interface Version 5.0.0
    (C) 2005-2015 Oracle Corporation
    All rights reserved.

    Usage:

      VBoxManage [<general option>] <command>

    [... snip entire VBoxManage syntax help ...]

    STDERR:
    Image cache does not exist, creating it at C:\Users\myuser\.docker\machine\cache...
    No default boot2docker iso found locally, downloading the latest release...
    Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso to C:\Users\myuser\.docker\machine\cache\boot2docker.iso...
    Creating VirtualBox VM...
    Creating SSH key...
    Creating disk image...
    Creating 20000 MB hard disk image...
    Converting from raw image file="stdin" to file="C:\Users\myuser\.docker\machine\machines\dev\disk.vmdk"...
    Creating dynamic image with size 20971520000 bytes (20000MB)...
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\Users\myuser\.docker\machine\machines\dev --name dev --register
    STDOUT: Virtual machine 'dev' is created and registered.
    UUID: 8b4e1083-2ad1-4a75-bc64-ce6b20ad440c
    Settings file: 'C:\Users\myuser\.docker\machine\machines\dev\dev\dev.vbox'

    STDERR:
    VM CPUS: 1
    VM Memory: 1024
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm dev --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
    STDOUT:
    STDERR:
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm dev --nic1 nat --nictype1 82540EM --cableconnected1 on
    STDOUT:
    STDERR:
    using 192.168.99.1 for dhcp address
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
    STDOUT: Name:            VirtualBox Host-Only Ethernet Adapter #11
    GUID:            c1389c26-1670-4cb8-97c6-974c8f039d00
    DHCP:            Disabled
    IPAddress:       192.168.59.99
    NetworkMask:     255.255.255.0
    IPV6Address:     fe80:0000:0000:0000:f540:67b5:0465:b90d
    IPV6NetworkMaskPrefixLength: 64
    HardwareAddress: 0a:00:27:00:00:00
    MediumType:      Ethernet
    Status:          Up
    VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #11

    STDERR:
    executing: c:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
    STDOUT:
    STDERR: 0%...
    Progress state: E_FAIL
    VBoxManage.exe: error: Failed to create the host-only adapter
    VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
    VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

    Error creating machine: exit status 1
    You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by nathanleclaire** [comment] 2015-07-14 22:00
Thanks for reporting this issue.  I'll look into it.

**Comment by sakai135** [comment] 2015-07-16 06:28
I'm having the same issue with Windows 10 build 10240 and VirtualBox 5.0. It seems to be a VirtualBox issue though, since just running `VBoxManage.exe hostonlyif create` alone errors.

I have been able to bypass the issue by setting the IP address on the adapter manually to match the `HostOnlyCIDR` value.

**Comment by hheimbuerger** [comment] 2015-07-16 06:46
Yeah, that's similar to how I've been solving it, too.

I'm also having occasional routing errors (the correct routing entries disappear) with the host-only adapter, which might be related to all of this.

**Comment by henriiik** [comment] 2015-07-16 07:38
Thanks for sharing your solution @sakai135, I was having the same problem. :)

I also had to enable DHCP server on the network interface to get it up and running.

**Comment by cyclonebt** [comment] 2015-07-16 21:13
I can also confirm this, on Win 10, build 10240
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

This is fixed when, as above, I input the expected IP address in the Host-Only NIC configuration. I did not have to do anything with DHCP.

**Comment by hheimbuerger** [comment] 2015-07-21 12:42
Possible cause in VirtualBox 5.0: https://www.virtualbox.org/ticket/14040

**Comment by levgaas** [comment] 2015-07-28 20:15
Hi, I'm new to all these "docker things" and have some troubles here. I'm using Windows 10x64 10162 build
I did everything as you said:
1) downloaded new version of docker-machine
2) Ran `docker-machine_windows_amd64.exe -D create -d virtualbox --virtualbox-hostonly-cidr 192.168.56.1/24 dev`
3) I did nothing with DHCP server as @henriiik mentioned above

**Then it was fine until**


`STDERR:
Error dialing TCP: ssh: handshake failed: WSARecv tcp 127.0.0.1:49751: An existing connection was forcibly closed by the remote host.
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: EOF
Error dialing TCP: ssh: handshake failed: WSARecv tcp 127.0.0.1:49803: An established connection was aborted by the software in your host machine.
Error dialing TCP: ssh: handshake failed: EOF
SSH returned: 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:41:85:25 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe41:8525/64 scope link
       valid_lft forever preferred_lft forever

END SSH
.....
.....
.....
ERROR getting IP: No IP address found 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:41:85:25 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe41:8525/64 scope link
       valid_lft forever preferred_lft forever

`Error creating machine: Maximum number of retries (5) exceeded
You will want to check the provider to make sure the machine and associated resources were properly removed.`


**However, VM boots good** and 
`$ docker version` from VM command line gives me next

Client version: 1.7.1
Client API version: 1.19
Go version(client): go1.4.2
Git commit(client): 786b29d 
OS/Arch(client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit(server): 786b29d 
OS/Arch(server): linux/amd64

But when i'm running 
`$ eval "$(docker-machine_windows_amd64.exe env dev)`
`> docker ps`
`>`
from my `msysgit 1.95` nothing happens
Have i something misunderstood?
Help me please

Thanks in advance

**Comment by sakai135** [comment] 2015-07-28 22:12
@levgaas Yours seems like a separate issue. Install build 10240 and see what happens. 10162 is pretty outdated.

**Comment by cyclonebt** [comment] 2015-07-28 22:55
I'm using Vagrant, not Docker, but my workaround was to assign a static IP
on the bridged interface and explicitly specify the correct adapter in the
public network section of the Vagrantfile.

Storm Chaser Scott Roberts
KSStorm.info
-- from mobile device

**Comment by Maifunti** [comment] 2015-07-29 02:28
Finally got it running by manually setting up the host-only-network on my Windows 10 machine. The init script for boot2docker calls "VBoxManage.exe list hostOnlyifs". It searches for a host only interface matching parameters set up in $HOME/.boot2docker/profile. For convenience you can access these with:
"boot2docker config" 
All you have to do is create a hostonlyInterface configuration matching these parameters. As an example, here was mine:

Init = false
Verbose = false
Driver = "virtualbox"
Clobber = false
ForceUpgradeDownload = false
SSH = "ssh"
SSHGen = "ssh-keygen"
SSHKey = "C:\\Users\\Yakubu\\.ssh\\id_boot2docker"
**VM = "boot2docker-vm"**
Dir = "C:\\Users\\Yakubu\\.boot2docker"
ISOURL = "https://api.github.com/repos/boot2docker/boot2docker/releases"
ISO = "C:\\Users\\Yakubu\\.boot2docker\\boot2docker.iso"
DiskSize = 20000
Memory = 2048
CPUs = 4
SSHPort = 2022
DockerPort = 0
**HostIP = "192.168.59.3"
DHCPIP = "192.168.59.99"
NetMask = [255, 255, 255, 0]
LowerIP = "192.168.59.103"
UpperIP = "192.168.59.254"
DHCPEnabled = true**
Serial = false
SerialFile = "\\\\.\\pipe\\boot2docker-vm"
Waittime = 300
Retries = 75

If all goes well, the init script wouldn't bother attempting to create a host-only adapter and you shouldn't run into this error
**Failed to create the host-only adapter**

**Comment by levgaas** [comment] 2015-07-29 14:05
@sakai135 After upgrading to 10240 build. 
`docker-machine_windows_amd64.exe -D create -d virtualbox --virtualbox-hostonly-cidr 192.168.56.1/24 dev` gives me author`s error

Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp

I have the adapter with specified IPv4 address(192.168.56.1) but every time when i run `docker-machine_windows_amd64.exe -D create -d virtualbox --virtualbox-hostonly-cidr 192.168.56.1/24 dev` new adapter is created with different ip

**Comment by mattjanssen** [comment] 2015-07-29 20:40
@cyclonebt How did you specify the already-existing adapter in the Vagrant config? I'm having the same issue and believe you solution will fix it.

**Comment by cyclonebt** [comment] 2015-07-29 21:18
Bring it up once with bridged networking, and it will show you the name of
the adapters when it asks you to select which one to use. Copy/paste the
name into the spec. Here's what mine looks like:

config.vm.network "public_network", bridge: "Realtek PCIe GBE Family
Controller", ip: "192.168.9.10"

On Wed, Jul 29, 2015 at 3:40 PM, Matt Janssen <notifications@github.com>
wrote:

> @cyclonebt <https://github.com/cyclonebt> How did you specify the
> already-existing adapter in the Vagrant config? I'm having the same issue
> and believe you solution will fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/1521#issuecomment-126088967>.
>



-- 

Scott Roberts, KB5TOR
<http://ksstorm.info/>*KSStorm.Info <http://kstorm.info/> - Severe Storm
Outlooks, Safety Information and Video*

Follow Storm Chaser Scott Roberts:
  <http://facebook.com/chasersroberts>  <http://twitter.com/KSStormInfo>
<http://plus.google.com/+KSStormInfo>  <http://youtube.com/ksstormmedia>

*Video/Photo Licensing: (844) KS-STORM*

**Comment by nathanleclaire** [comment] 2015-07-29 23:20
Hi all, just some update on this:

I have reproduced the issue around `VBoxManage hostonlyif create` on Windows 10 and can confirm that command is failing.

I've made a comment on the Virtualbox ticket tracker here: https://www.virtualbox.org/ticket/14040

I can't really think of any way to work around it until upstream fixes this bug, so I'm all ears if anyone has suggestions.

**Comment by nathanleclaire** [comment] 2015-07-30 20:32
Update:  We've reached out to some folks at Oracle to hopefully move this along as fast as we can.

**Comment by levgaas** [comment] 2015-07-30 20:56
@nathanleclaire , thank you =) we appreciate it

**Comment by aaronsturm** [comment] 2015-07-30 21:15
Thank you very much @nathanleclaire!

**Comment by andrewfaria** [comment] 2015-08-01 15:17
A short-term working patch was released last night. Tested and it works. https://www.virtualbox.org/ticket/14040#comment:36

**Comment by nathanleclaire** [comment] 2015-08-10 22:16
Update for everyone: I have this working again with the latest [VirtualBox test build](https://www.virtualbox.org/wiki/Testbuilds).  Now we just have to wait for the patch to land in a release.

**Comment by mattjanssen** [comment] 2015-08-10 22:39
:joy: Thanks @nathanleclaire

**Comment by dgageot** [comment] 2016-01-13 15:07
@hheimbuerger @sakai135 @henriiik can you try with docker-machine 0.5.6 and tell us if it's better?

**Comment by dgageot** [comment] 2016-01-26 17:01
This is fixed in https://github.com/docker/machine/pull/2797. `Failed to create the host-only adapter` is Virtualbox own way to tell us that the adapter is created but not yet listed. We now have a series of workarounds to fix this issue

**Closed by dgageot** 2016-01-26 17:02 UTC
Labels: driver/virtualbox

**Comment by zbilbo** [comment] 2016-02-13 20:36
not fixed at all...

tried VB 5.0.14, and different 5.0.15.xxxxxx.

same shit happening.

**Comment by howdoicomputer** [comment] 2016-02-14 03:48
I'm unable to get this working as well.

```
λ docker-machine create --driver virtualbox default
Running pre-create checks...
(default) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v1.10.1
(default) Downloading C:\Users\Tyler Hampton\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.10.1/boot2docker.iso...
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Error with pre-create check: "VirtualBox is configured with multiple host-only adapters with the same name \"HostInterfaceNetworking-VirtualBox NDIS 6.0 Miniport Driver\". Please remove one."
```

Windows 10
docker-machine 0.6.0
docker 1.10.0
VirtualBox 5.0.14

**Comment by frankbolviken** [comment] 2016-02-16 11:18
Not fixed.

**Comment by nathanleclaire** [comment] 2016-02-16 23:56
@frankbolviken Please file an issue with clear steps to reproduce and information about your host system, Machine version, and so on -- without any information issues cannot be fixed.

**Comment by zbilbo** [comment] 2016-02-18 17:59
@nathanleclaire see also https://github.com/docker/machine/issues/2972#issuecomment-183755968.

is in fact not related to Docker per se, but maybe someone might get somewhat tired of the Oracle shit...

**Comment by frankbolviken** [comment] 2016-02-18 20:52
Scratch my comment. Turns out that Cisco VPN client totally borks up all network stuff, and renders docker-machine useless after use. Have to reboot computer.

**Comment by snowyu** [comment] 2016-04-19 12:08
It occured on upgrade virtualbox.

Work around:

uninstall virtualbox and install virtualbox again.

**Comment by chxzqw** [comment] 2017-08-06 14:02
Same issue here.
The virtualBox comes with Docker toolkit is 5.0.14 at this moment then after I upgraded it onto 5.0.16 error appears.

**Comment by dascotech** [comment] 2017-08-27 18:48
Check comment #76 from the following - this worked for me.
https://www.virtualbox.org/ticket/14040 
**I was able to workaround by setting the following .exe's to Windows 8 compatibility mode:
Virtualbox.exe
VBoxManage.exe
VBoxHeadless.exe**

**Comment by eterceros** [comment] 2018-01-25 22:20
VirtualBox has a general tools section and it shows host network manager I deleted a duplicate ip one and then it worked for me

**Comment by AleCaste** [comment] 2018-01-30 23:45
This was driving me nuts.
It turned out that I had java version 1.7 on my system since I needed it for an specific old project.
After I installed java 1.8 this problem creating the host-only adapter went away.

**Comment by Dhanush77** [comment] 2019-01-13 05:18
I was driving nuts last 2 days with this problem. Finally found a solution.
1. The Antivirus was causing the issue
2, You need to disable to Antivirus services on your windows system (You will need Admin access or get this done from your company IT Person)
3. Reinstall Docker tool box and start it (Admin mode)
4. This works
