### ISSUE TITLE
Can not create generic machine with error : The handle is invalid

### ISSUE THREAD

**Issue by netroby** [docker/machine#3937] opened 2016-12-22 11:36 UTC
```
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
found compatible host: centos
Provisioning with centos...
No storagedriver specified, using devicemapper

(devdocker) Calling .GetMachineName
(devdocker) Calling .GetSSHHostname
(devdocker) Calling .GetSSHPort
(devdocker) Calling .GetSSHKeyPath
(devdocker) Calling .GetSSHKeyPath
(devdocker) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} huzhifeng [0xc2bd70] <nil>  []} 10.119.25.155 22 <nil>}
About to run SSH command:
sudo hostname devdocker && echo "devdocker" | sudo tee /etc/hostname
SSH cmd err, output: The handle is invalid.:
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo hostname devdocker && echo "devdocker" | sudo tee /etc/hostname
err     : The handle is invalid.
output  :

notifying bugsnag: [Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo hostname devdocker && echo "devdocker" | sudo tee /etc/hostname
err     : The handle is invalid.
output  :
]
PS C:\Users\huzhifeng> docker-machine rm -f devdocker
About to remove devdocker
```

**Comment by tronicum** [comment] 2016-12-24 20:55
please report verions (like docker-machine, etc).

**Comment by netroby** [comment] 2016-12-25 01:44
0.8.2 docker-machine, OS version Windows 10 14986 x64

**Comment by tronicum** [comment] 2016-12-25 04:00
target ("devdocker") OS? maybe stuff it uses is not within the image

**Comment by minhuyen** [comment] 2017-02-02 09:32
The same issue.

**Comment by Liciax** [comment] 2017-03-02 09:10
Hey, I had exactly the same issue. The error said that the problem is on ssh command, I presume you to be on PowerShell as I was. But, I figure out that some ssh command did not work on it (for instance ssh-copy-id). I change my terminal for GitBash, and it's work. I hope it will be the same for you.

Docker version 1.13.1
docker-machine version 0.9.0
Window 10 Professionnel x64
OS VM : Centos7

**Comment by budhrg** [comment] 2017-03-25 12:00
Hi, I am also hit with the same error. When having ssh binary (from cygwin or mingw), it is not reproducible but without it I am getting this issue.

Docker version 1.12.6
docker-machine version 0.9.0
Windows 10 Pro x64
VM OS: CentOS 7

Any update on its resolution ?

**Comment by gbraad** [comment] 2017-05-16 08:37
This seems to fail in `RedHatSSHCommander` when the term size is retrieved.

For some reason:
```
	fd := int(os.Stdin.Fd())
	termWidth, termHeight, err := terminal.GetSize(fd)
```
will result in an invalid filehandle.

While doing
```
        ///fd := int(os.Stdin.Fd())
	termWidth := 80
	termHeight := 25
```
allows me to run the code 'without' issues.

**Comment by gbraad** [comment] 2017-05-17 05:27
Can someone explain what is being solved in `RedHatSSHCommander` (`redhat.go`) with:

```
func (sshCmder RedHatSSHCommander) SSHCommand(args string) (string, error) {
	client, err := drivers.GetSSHClientFromDriver(sshCmder.Driver)
	if err != nil {
		return "", err
	}

	log.Debugf("About to run SSH command:\n%s", args)

	// redhat needs "-t" for tty allocation on ssh therefore we check for the
	// external client and add as needed.
	// Note: CentOS 7.0 needs multiple "-tt" to force tty allocation when ssh has
	// no local tty.
	var output string
	switch c := client.(type) {
	case *ssh.ExternalClient:
		c.BaseArgs = append(c.BaseArgs, "-tt")
		output, err = c.Output(args)
	case *ssh.NativeClient:
		output, err = c.OutputWithPty(args)
	}

	log.Debugf("SSH cmd err, output: %v: %s", err, output)
	if err != nil {
		return "", fmt.Errorf(`something went wrong running an SSH command
command : %s
err     : %v
output  : %s`, args, err, output)
	}

	return output, nil
}
```

Replacing the implementation with:
```
package provision

import (
	"github.com/docker/machine/libmachine/drivers"
)

type RedHatSSHCommander struct {
	Driver drivers.Driver
}

func (sshCmder RedHatSSHCommander) SSHCommand(args string) (string, error) {
	return drivers.RunSSHCommandFromDriver(sshCmder.Driver, args)
}
```
works as expected...

**Comment by gbraad** [comment] 2017-05-17 07:39
This is fixed with:

```
	fd := int(os.Stdout.Fd())
	termWidth, termHeight, err := terminal.GetSize(fd)
```

**Comment by gbraad** [comment] 2017-05-17 08:40
Tested with https://github.com/minishift/minishift on both b2d and CentOS based images.

**Closed** 2017-05-31 23:02 UTC
