### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by fiws** [docker/machine#4265] opened 2017-09-25 18:28 UTC
Last commit was 2 months ago. Issues and pull requests are piling up.

Is there an alternative to docker machine? Is this project deprecated / abandoned?

**Comment by Herbis** [comment] 2017-09-26 08:34
There's certainly low activity, but I've noticed a contributor requesting changes for a pull request just 4 days ago. 
Hopefully the low activity is just temporary.

**Comment by afbjorklund** [comment] 2017-10-01 12:19
It would be nice if new maintainers of Docker Machine could be found, since it is still useful sometimes...

There is https://github.com/docker/machine/blob/master/MAINTAINERS, but it seems to be outdated too.

**Comment by justincormack** [comment] 2017-10-01 13:29
In terms of "Is this project deprecated / abandoned?" - internally at Docker we are not using it very much as far as I know, although it is still recommended for desktop use for Windows 7. There are some PRs being merged still, so no it is not abandoned.

My view is that the problem is it tries to be too general, and the scope is very broad. Forcing so many things into the same API is hard work. We have introduced more focused projects such as infrakit for multi host production deployments, linuxkit for a maintainable and extensible replacement for boot2docker, and there are many other external projects that cover related areas.

It would be good to understand the use cases people have now for machine, what they prefer over other tools and what they see as missing or needing changing.

**Comment by afbjorklund** [comment] 2017-10-01 13:44
Our current use cases are:
- Windows 7 (as noted)
- RHEL 6-7, with KVM

It _would_ be possible to use Docker for Windows (with Windows 10),
or to use Docker Engine on Linux (with new kernel and root access).
But for the legacy versions and unprivileged users, it works just fine...

The easy transfer path to provisioning VMs in the cloud is a bonus, too.

**Comment by shin-** [comment] 2017-10-02 19:48
Hey folks,

I'm the primary maintainer of the project. Sorry if I've made it look like it was abandoned, I was gone for a few weeks and am juggling this with a couple other projects, which somewhat explains the month-long silence.
On the other hand, while we still want to maintain the project and make sure the people using it today can continue to do so as long as it is useful, we will not be adding any new feature to the project from here onward, as the Docker team tries to focus its efforts on other solutions (some of which @justincormack aptly describes [above](https://github.com/docker/machine/issues/4265#issuecomment-333376760)).
Bugfixes will continue to happen and we'll make patch releases as needed. Thank you for your understanding!

**Comment by afbjorklund** [comment] 2017-10-03 05:33
@shin- : No worries, glad to hear that it is still being maintained! It would be great if some new arrangement could be found to make KVM a more welcome citizen, but I suppose that is more of a discussion to be had ?

For the most part, it's enough to do the work in the drivers... It's only occasionally that something _new_ is needed - like `mount` or `GetPort()`, when things differ significantly from whatever VirtualBox is doing.

* #4018 (mount directory using sshfs)
* #4034 (avoid hard-coding port 2376)

Discussion is probably better off in a different forum.

**Comment by fiws** [comment] 2017-10-03 12:43
@shin- thanks for the feedback! 
I am only using docker-machine indirect, because [gitlab-runner](https://gitlab.com/gitlab-org/gitlab-runner/) is using it to provision its CI runners.

**Closed** 2017-10-11 00:26 UTC
