### ISSUE TITLE
Slow network checks and dhcp at machine startup, static ip?

### ISSUE THREAD

**Issue by krodelabestiole** [docker/machine#3078] opened 2016-02-18 00:56 UTC
hello

im on windows 10 and my docker machine (virtualbox driver) takes a bit more than 40 sec to start (without container)
it takes 5 sec to "check network to re-create if needed"
and 35 sec "waiting for an IP"
i guess it's not a normal behavior, it must be a timeout or something ?
i don't really need neither of this operations at startup. i don't need DHCP and i would prefer to set a static ip for my machine. (the only info i found about setting a static IP is a dirty one-ip-range-DHCP workaround hack which does not solve my problem)

```
VBoxManage list hostonlyifs
Name: VirtualBox Host-Only Ethernet Adapter
GUID: feb3aa05-59fc-4175-b04d-3c372fad153e
DHCP: Disabled
IPAddress: 192.168.99.1
NetworkMask: 255.255.255.0
IPV6Address: fe80:0000:0000:0000:105d:e9c2:cdbd:4799
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:00
MediumType: Ethernet
Status: Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
```

is it normal that DHCP looks disabled on this interface ? the machine's  IP is correctly assigned to 192.168.99.100 though.

does anyone have any idea about why it is taking so long or how i could get rid of this useless startup time ?

**Comment by nathanleclaire** [comment] 2016-04-22 18:48
> is it normal that DHCP looks disabled on this interface ? the machine's IP is correctly assigned to 192.168.99.100 though.

Yes, it's normal.

> i don't really need neither of this operations at startup. i don't need DHCP and i would prefer to set a static ip for my machine. (the only info i found about setting a static IP is a dirty one-ip-range-DHCP workaround hack which does not solve my problem)

This request seems a dupe of https://github.com/docker/machine/issues/1709

**Closed by nathanleclaire** 2016-04-22 18:48 UTC
Labels: driver/virtualbox

**Comment by Alvison** [comment] 2018-07-31 09:17
@krodelabestiole hi krodelabestiole , have you found a way to get rid of that useless startup time( waiting for ip) ? It is really  a waste of time !

**Comment by krodelabestiole** [comment] 2018-07-31 09:43
nope sorry. I can't remember having fixed this issue. I have switched to docker for windows (hyper-v) since then, then WSL.
