### ISSUE TITLE
Service Unavailable error on MacOSX

### ISSUE THREAD

**Issue by valentin69** [docker/machine#2283] opened 2015-11-13 12:43 UTC
Unable to connect from the MacOSX host.
Using DockerToolbox-1.9.0c
Every command fails with a Service Unavailable error.

$ docker-machine --version
docker-machine version 0.5.0 (04cfa58)
$ docker images
An error occurred trying to connect: Get https://192.168.99.100:2376/v1.21/images/json: Service Unavailable
$ docker-machine ls
NAME                     ACTIVE   DRIVER       STATE     URL                         SWARM
machine1                 *        virtualbox   Running   tcp://192.168.99.100:2376   

I can ssh in the machine : Docker is ok.

docker-machine ssh machine1
...
Boot2Docker version 1.9.0, build master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
Docker version 1.9.0, build 76d6bc9
docker@homebyme:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
hello-world         latest              0a6ba66e537a        4 weeks ago         960 B

**Comment by jeanlaurent** [comment] 2015-11-13 14:11
Closed as duplicate of #2282

**Closed by jeanlaurent** 2015-11-13 14:11 UTC
