### ISSUE TITLE
Ability to provision Windows hosts via VirtualBox

### ISSUE THREAD

**Issue by michaelsbradleyjr** [docker/machine#1734] opened 2015-08-19 18:10 UTC
I use a Mac laptop as my principal dev environment, and `docker-machine` makes it so very convenient to provision Docker-Linux hosts locally, using VirtualBox.

I would like to request a feature whereby Docker-Windows hosts can likewise be provisioned locally, i.e. on my Mac laptop, using VirtualBox.

**Comment by dgageot** [comment] 2016-01-26 15:17
Duplicate of https://github.com/docker/machine/issues/2907

**Closed by dgageot** 2016-01-26 15:17 UTC
Labels: kind/feature
