### ISSUE TITLE
Rename download scripts to be compatible with Compose

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#747] opened 2015-03-07 02:17 UTC
I love the ability to download Compose as:

```
curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
```

It would be great if Machine downloads are named accordingly as well.

**Comment by ehazlett** [comment] 2015-03-12 14:38
Thanks for reporting.  Duplicate of #494.

**Comment by ehazlett** [comment] 2015-03-12 14:39
We will get this updated -- it bugs me too ;)

**Closed by ehazlett** 2015-03-12 14:38 UTC
