### ISSUE TITLE
Docker Machine get stuck on IBM Softlayer 

### ISSUE THREAD

**Issue by wzymaster** [docker/machine#915] opened 2015-03-30 14:18 UTC
Here is a derived issue from  #863.

Sorry, I just download the pre-release of 0.2.0 and run docker-machine like below :

./docker-machine create --driver softlayer --softlayer-user leow --softlayer-api-key xxx  --softlayer-cpu 4 --softlayer-memory 8192 --softlayer-disk-size 0 --softlayer-domain imdemocloud.com --softlayer-hostname "leo-demo1" --softlayer-image CENTOS_LATEST_64 --softlayer-region hkg02 leo-demo1
INFO[0000] Creating SSH key...
INFO[0007] Getting Host IP
INFO[0032] Waiting for host to become available
INFO[0154] Waiting for host setup transactions to complete

Unfortunatley, it still get stuck at 'Waiting for host setup transaction to complete" step .

However, I do see this VM machine provisioned on SoftLayer and I can log in. It looks like a clean machine without docker.

Do I run something wrong here ? @hairyhenderson

The below is the build of docker-machine which I am using :

Zhongs-MacBook-Pro:Leo_Demo wzymaster$ ./docker-machine -v
docker-machine version 0.2.0 (45f08d9)

**Comment by ehazlett** [comment] 2015-03-30 17:36
Currently, only Ubuntu is supported.  Could you try with that and see if you still have the issue?

**Comment by ehazlett** [comment] 2015-03-30 20:10
I just created a machine on Softlayer fine with the defaults.

**Comment by hairyhenderson** [comment] 2015-03-30 21:34
@wzymaster - I'm thinking @ehazlett is right - you should use Ubuntu instead (just omit the `--softlayer-image` option and it'll default to the right image). But, can you retry with the `--debug` option (before the `create` subcommand) to make sure it's not something else?

**Comment by wzymaster** [comment] 2015-03-31 04:45
Here is what I tried but still hanging there after almost 40 minutes :  

Zhongs-MacBook-Pro:Leo_Demo wzymaster$ ./docker-machine create --driver softlayer \
>      --softlayer-user leow \
>      --softlayer-api-key xxxxxxxxxx \
>       --softlayer-cpu 4 \
>      --softlayer-memory 8192 \
>      --softlayer-disk-size  0 \
>      --softlayer-domain imdemocloud.com \
>      --softlayer-hostname "leo-demo"  \
>      --softlayer-region hkg02  \
>     leo-demo
INFO[0000] Creating SSH key...
INFO[0007] Getting Host IP
INFO[0030] Waiting for host to become available
INFO[0195] Waiting for host setup transactions to complete

Can you share me  your ./docker-machine cmd for a successful run ?  @ehazlett @hairyhenderson 

In fact, VM is provisioned on IBM SoftLayer but no docker is installed on it after I manually log in , like following :  

```shell
root@leo-demo:~# docker
The program 'docker' is currently not installed. You can install it by typing:
apt-get install docker
root@leo-demo:~# uname -a
Linux leo-demo 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@leo-demo:/etc# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by wzymaster** [comment] 2015-03-31 04:49
One more point:  I am running ./docker-machine on my MacBook (OS X 10.9.2) using Boot2Docker instead.

Is it ever verified on Boot2docker on macBook ?

**Comment by hairyhenderson** [comment] 2015-03-31 21:04
@wzymaster - I'm not sure what you mean, do you mean you're running the `docker-machine` binary inside the boot2docker VM? Otherwise, docker-machine has no interaction with boot2docker and should be fine.

Can you please re-run the command with the `--debug` option? There's likely some useful debug information that might help track down what's going wrong.

**Comment by wzymaster** [comment] 2015-03-31 21:10
Sorry for the confusion.  I mean the same cmd line works fine on a Linux Box(CentOS 6.6) but failed on my macBook installed with boot2docker.

**Comment by hairyhenderson** [comment] 2015-03-31 21:36
@wzymaster - Ah, I see.

**Comment by metcalfc** [comment] 2015-04-02 15:59
Seeing this as well with the latest rc.

Running with debug only yields a little more infromation.

```
...
DEBU[0132] Still waiting - active transaction is POWER_ON...
DEBU[0134] Still waiting - active transaction is POWER_ON...
DEBU[0136] Still waiting - active transaction is INSTALL_COMPLETE...
DEBU[0139] Still waiting - active transaction is START_SERVICE_SETUP...
DEBU[0141] Still waiting - active transaction is SERVICE_SETUP...
```

And then nothing. Visiting the SL console the host is up running, ssh is fine, etc.

**Comment by ehazlett** [comment] 2015-04-02 19:24
Hmm i can create SL instances fine.  Perhaps it's a region related issue?

**Comment by metcalfc** [comment] 2015-04-02 19:31
I tried dal01 and sjc01. Using the default API endpoint. Hourly billing. 



On April 2, 2015 at 12:25:02 PM PDT, Evan Hazlett <notifications@github.com> wrote:Hmm i can create SL instances fine. Perhaps it's a region related issue?  —Reply to this email directly or view it on GitHub.

**Comment by mbentley** [comment] 2015-04-09 13:40
I am also able to reproduce.  Here are the env vars I have set:

```
SOFTLAYER_API_KEY=<my key>
SOFTLAYER_USER=mbentley
SOFTLAYER_REGION=dal06
SOFTLAYER_DOMAIN=mbentley.dckrindy.io

```

And here is my output:

```
$ docker-machine -D create -d softlayer softlayer02
INFO[0000] Creating SSH key...
DEBU[0000] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/mbentley/.docker/machine/machines/softlayer02/id_rsa

Generating public/private rsa key pair.
Your identification has been saved in /Users/mbentley/.docker/machine/machines/softlayer02/id_rsa.
Your public key has been saved in /Users/mbentley/.docker/machine/machines/softlayer02/id_rsa.pub.
The key fingerprint is:
a6:1f:c8:49:50:b7:d5:b7:8e:fd:18:02:4f:40:4f:f9 mbentley@wafflemaker
The key's randomart image is:
+--[ RSA 2048]----+
|      . ..o...   |
|     . . o.oo .  |
|    .   .  ..o . |
|     .    . . E  |
|      . S  + +   |
|     o =    + +  |
|      = .    . + |
|       . .    . .|
|        .        |
+-----------------+
INFO[0006] Getting Host IP
INFO[0026] Waiting for host to become available
DEBU[0026] Still waiting - state is Stopped...
...
DEBU[0076] Still waiting - state is Stopped...
DEBU[0078] Still waiting - active transaction is POWER_ON...
...
DEBU[0132] Still waiting - active transaction is POWER_ON...
DEBU[0135] Still waiting - active transaction is INSTALL_COMPLETE...
DEBU[0138] Still waiting - active transaction is START_SERVICE_SETUP...
DEBU[0140] Still waiting - active transaction is SERVICE_SETUP...
DEBU[0143] Still waiting - active transaction is SERVICE_SETUP...
DEBU[0145] Still waiting - active transaction is SERVICE_SETUP...
```

I am using `dal06` because the default keeps complaining about not having SAN space and I haven't had a change to figure out why `SOFTLAYER_LOCAL_DISK` isn't working for me (I am probably just not giving it the right parameter) but the problem exists anyway so it isn't really the focus at this point. :smile:

**Comment by hairyhenderson** [comment] 2015-04-10 11:59
@mbentley - Interesting... Seems like you and @metcalfc are both seeing the polling stop after ~140 seconds...

I've only been testing this out in the `tor01` datacenter. When I get some time I'll see about testing in `dal06` and `hkg02`.

I might also have the loop simply time out if it takes too long. I'm thinking 5 or 10 minutes is reasonable...

**Comment by zekizeki** [comment] 2015-04-15 07:20
I can also reproduce this with both docker-machine 0.1.0 and 0.2.0  (e4c2173)

I'm running this from OS X 10.10.2

For both versions I am using the following env variables and command...

```
export SOFTLAYER_API_KEY=xxxxxxxx
export SOFTLAYER_USER=dockeruser
export SOFTLAYER_REGION=ams03
export SOFTLAYER_DOMAIN=robsmart.org
export SOFTLAYER_HOSTNAME=dm01

docker-machine -D create -d softlayer dm01
```

Debug output for 0.1.0 is ...
```
INFO[0000] Creating CA: /Users/robsmart/.docker/machine/certs/ca.pem 
INFO[0000] Creating client certificate: /Users/robsmart/.docker/machine/certs/cert.pem 
INFO[0000] Creating SSH key...                          
DEBU[0000] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/robsmart/.docker/machine/machines/dm01/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/robsmart/.docker/machine/machines/dm01/id_rsa.
Your public key has been saved in /Users/robsmart/.docker/machine/machines/dm01/id_rsa.pub.
The key fingerprint is:
91:3c:ae:21:99:32:cc:41:33:cc:58:eb:ef:e4:5f:c1 robsmart@silverfox.local
The key's randomart image is:
+--[ RSA 2048]----+
| ==              |
|..o+   . .       |
|  o     =        |
| + . o o o       |
|  * + . E        |
|   + . o .       |
|    o . .        |
|   +   .         |
|    o..          |
+-----------------+
INFO[0007] Getting Host IP                              
INFO[0032] Waiting for host to become available         
INFO[0259] Configuring host OS                          
DEBU[0259] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /Users/robsmart/.docker/machine/machines/dm01/id_rsa root@159.8.194.244 [ -f "$(which docker)" ] && [ -f "/etc/default/docker" ] || exit 1 
DEBU[0263] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /Users/robsmart/.docker/machine/machines/dm01/id_rsa root@159.8.194.244 [ -f "$(which docker)" ] && [ -f "/etc/default/docker" ] || exit 1 
DEBU[0265] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /Users/robsmart/.docker/machine/machines/dm01/id_rsa root@159.8.194.244 [ -f "$(which docker)" ] && [ -f "/etc/default/docker" ] || exit 1 
```

The last command repeats endlessly. Logging onto the VM I can see that docker has not been installed.

The debug output for 0.2.0 is...

```
docker-machine version 0.2.0 (e4c2173)
```

```
INFO[0000] Creating SSH key...                          
INFO[0007] Getting Host IP                              
INFO[0040] Waiting for host to become available         
DEBU[0042] Still waiting - state is Stopped...          
DEBU[0045] Still waiting - state is Stopped...          
DEBU[0047] Still waiting - state is Stopped...          
DEBU[0050] Still waiting - state is Stopped...          
DEBU[0054] Still waiting - state is Stopped...          
DEBU[0056] Still waiting - state is Stopped...          
DEBU[0059] Still waiting - state is Stopped...          
DEBU[0062] Still waiting - state is Stopped...          
DEBU[0065] Still waiting - state is Stopped...          
DEBU[0068] Still waiting - state is Stopped...          
DEBU[0071] Still waiting - state is Stopped...          
DEBU[0074] Still waiting - state is Stopped...          
DEBU[0077] Still waiting - state is Stopped...          
DEBU[0080] Still waiting - state is Stopped...          
DEBU[0083] Still waiting - state is Stopped...          
DEBU[0086] Still waiting - state is Stopped...          
DEBU[0088] Still waiting - state is Stopped...          
DEBU[0091] Still waiting - state is Stopped...          
DEBU[0094] Still waiting - state is Stopped...          
DEBU[0097] Still waiting - state is Stopped...          
DEBU[0100] Still waiting - state is Stopped...          
DEBU[0103] Still waiting - state is Stopped...          
DEBU[0106] Still waiting - state is Stopped...          
DEBU[0109] Still waiting - state is Stopped...          
DEBU[0112] Still waiting - state is Stopped...          
DEBU[0115] Still waiting - state is Stopped...          
DEBU[0118] Still waiting - state is Stopped...          
DEBU[0121] Still waiting - state is Stopped...          
DEBU[0124] Still waiting - state is Stopped...          
DEBU[0127] Still waiting - state is Stopped...          
DEBU[0130] Still waiting - state is Stopped...          
DEBU[0133] Still waiting - state is Stopped...          
DEBU[0135] Still waiting - state is Stopped...          
DEBU[0138] Still waiting - state is Stopped...          
DEBU[0142] Still waiting - state is Stopped...          
DEBU[0145] Still waiting - state is Stopped...          
DEBU[0148] Still waiting - state is Stopped...          
DEBU[0151] Still waiting - state is Stopped...          
DEBU[0154] Still waiting - state is Stopped...          
DEBU[0157] Still waiting - state is Stopped...          
DEBU[0160] Still waiting - state is Stopped...          
DEBU[0163] Still waiting - state is Stopped...          
DEBU[0165] Still waiting - state is Stopped...          
DEBU[0168] Still waiting - state is Stopped...          
DEBU[0171] Still waiting - state is Stopped...          
DEBU[0174] Still waiting - state is Stopped...          
DEBU[0177] Still waiting - state is Stopped...          
DEBU[0180] Still waiting - state is Stopped...          
DEBU[0183] Still waiting - state is Stopped...          
DEBU[0186] Still waiting - state is Stopped...          
DEBU[0189] Still waiting - state is Stopped...          
DEBU[0192] Still waiting - state is Stopped...          
DEBU[0195] Still waiting - state is Stopped...          
DEBU[0198] Still waiting - state is Stopped...          
DEBU[0201] Still waiting - state is Stopped...          
DEBU[0204] Still waiting - state is Stopped...          
DEBU[0207] Still waiting - state is Stopped...          
DEBU[0210] Still waiting - state is Stopped...          
DEBU[0213] Still waiting - state is Stopped...          
DEBU[0216] Still waiting - state is Stopped...          
DEBU[0218] Still waiting - state is Stopped...          
DEBU[0221] Still waiting - state is Stopped...          
DEBU[0224] Still waiting - state is Stopped...          
DEBU[0227] Still waiting - state is Stopped...          
DEBU[0230] Still waiting - state is Stopped...          
DEBU[0233] Still waiting - state is Stopped...          
DEBU[0236] Still waiting - state is Stopped...          
DEBU[0239] Still waiting - state is Stopped...          
DEBU[0242] Still waiting - state is Stopped...          
INFO[0244] Waiting for host setup transactions to complete 
DEBU[0246] Still waiting - active transaction is POWER_ON... 
DEBU[0249] Still waiting - active transaction is POWER_ON... 
DEBU[0251] Still waiting - active transaction is POWER_ON... 
DEBU[0254] Still waiting - active transaction is POWER_ON... 
DEBU[0257] Still waiting - active transaction is POWER_ON... 
DEBU[0260] Still waiting - active transaction is POWER_ON... 
DEBU[0263] Still waiting - active transaction is POWER_ON... 
DEBU[0266] Still waiting - active transaction is POWER_ON... 
DEBU[0269] Still waiting - active transaction is POWER_ON... 
DEBU[0271] Still waiting - active transaction is POWER_ON... 
DEBU[0274] Still waiting - active transaction is POWER_ON... 
DEBU[0277] Still waiting - active transaction is POWER_ON... 
DEBU[0280] Still waiting - active transaction is POWER_ON... 
DEBU[0283] Still waiting - active transaction is POWER_ON... 
DEBU[0286] Still waiting - active transaction is POWER_ON... 
DEBU[0289] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0292] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0295] Still waiting - active transaction is START_SERVICE_SETUP... 
DEBU[0297] Still waiting - active transaction is SERVICE_SETUP... 
DEBU[0300] Still waiting - active transaction is PUBLISH_SERVER_DATA... 
```

Again the vm is provisioned but Docker has not been installed despite the INSTALL_COMPLETE debug message above.

**Comment by hairyhenderson** [comment] 2015-04-15 11:44
@zekizeki - was there anything after the last line? The `INSTALL_COMPLETE` transaction isn't usually the last transaction - there's often a few transactions that happen afterwards.

**Comment by hairyhenderson** [comment] 2015-04-15 12:14
I'm seeing something interesting which may be related to this problem (or totally unrelated). I see much the same output as @zekizeki, but at the end:

```
...
DEBU[0274] Still waiting - active transaction is SERVICE_SETUP... 
DEBU[0277] Still waiting - active transaction is SERVICE_SETUP... 
DEBU[0279] Still waiting - active transaction is SERVICE_SETUP... 
DEBU[0290] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=30 -o LogLevel=quiet -p 22 -i /Users/hendersd/.docker/machine/machines/dmtest-tor01/id_rsa root@158.85.123.4 sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq curl 
```

At this point, the process just hangs. Trying to SSH in to the public IP address of the VM fails. In my particular case, we have a firewall on our public VLAN, so by default SSH doesn't work to that IP. Given that the ssh command is told to make 30 connection attempts, it's probably not hanging, just quietly timing out 30 times...

I'm going to add more debug output, and also try this out in a few other regions...

**Comment by hairyhenderson** [comment] 2015-04-15 12:48
Just tried this out in `ams01`, and it took considerably longer to finish the setup transactions (after 521 seconds!), but it did complete, and because we don't have any firewalls on VLANs in `ams01`, the SSH commands completed correctly and docker installed no problem.

Will try out a few other regions...

**Comment by hairyhenderson** [comment] 2015-04-15 13:03
Ok, `hkg02` works fine for me as well.

I have a feeling there's some difference in SL account permissions that's causing things to work fine for myself and @ehazlett, but not for everyone else on this thread.

**Comment by mbentley** [comment] 2015-04-15 15:40
I just tried to replicate starting two instances, one with my credentials and one with those from @ehazlett  and both instances hung.

Using my credentials:
```
...
DEBU[0153] Still waiting - active transaction is POWER_ON...
DEBU[0155] Still waiting - active transaction is INSTALL_COMPLETE...
DEBU[0158] Still waiting - active transaction is START_SERVICE_SETUP...
DEBU[0160] Still waiting - active transaction is SERVICE_SETUP...
DEBU[0163] Still waiting - active transaction is SERVICE_SETUP...
```

Using @ehazlett's:
```
...
DEBU[0138] Still waiting - active transaction is POWER_ON...
DEBU[0140] Still waiting - active transaction is INSTALL_COMPLETE...
DEBU[0143] Still waiting - active transaction is START_SERVICE_SETUP...
DEBU[0145] Still waiting - active transaction is SERVICE_SETUP...
DEBU[0148] Still waiting - active transaction is PUBLISH_SERVER_DATA..
```

All other environment variables are the same:
```
SOFTLAYER_API_KEY=removed
SOFTLAYER_USER=removed
SOFTLAYER_REGION=dal06
SOFTLAYER_DOMAIN=mbentley.dckrindy.io
```

**Comment by zekizeki** [comment] 2015-04-15 15:53
@hairyhenderson there was nothing after the line ...
```
DEBU[0300] Still waiting - active transaction is PUBLISH_SERVER_DATA...  
```
it just hung there, I left it overnight in the hope it might complete but no joy.

I tried it again on a different data center and it got as far as ...

```
DEBU[0328] Still waiting - active transaction is POWER_ON... 
DEBU[0331] Still waiting - active transaction is POWER_ON... 
DEBU[0334] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0337] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0340] Still waiting - active transaction is SERVICE_SETUP... 
```
then hung. 

In terms of permissions on the SL account, my user does have full admin permissions for everything.

**Comment by zekizeki** [comment] 2015-04-15 18:11
@hairyhenderson this might help a bit.

I watched the docker-machine process via a 'nettop -m tcp' command on my mac.

I can see it connecting out to the softlayer API server for the machine provisioning, however as soon as it starts to perform the SSH oparations it trys to connect to localhost:22 rather than the IP address of the softlayer VM which obviously won't work. Got to head off now but will do some debug later and see if i can figure out why it's doing that.

```
docker-machine.60691                                                                             319 KiB          83 KiB     0 B     682 B    8311 B
    tcp4 127.0.0.1:57855<->localhost:22                              lo0         SynSent           0 B             0 B       0 B       0 B       0 B     0.22 ms   128 KiB
```

**Comment by hairyhenderson** [comment] 2015-04-16 00:48
Totally weird... @zekizeki, my command was:

```
export SOFTLAYER_USER=xxx
export SOFTLAYER_API_KEY=xxx
machine -D create -d softlayer --softlayer-domain dhtest.local --softlayer-region "ams01" --softlayer-hostname "dmtest-ams01" dmtest-ams01
```

The localhost business seems very odd. Is it possible that you have an alias in /etc/hosts pointing to the same name as `--softlayer-hostname/SOFTLAYER_HOSTNAME`? It's a long-shot, but...

**Comment by hairyhenderson** [comment] 2015-04-16 00:49
I altered the SSH timeouts in #1006, which will help the driver return faster when there are connection issues. Just to rule out that remote possibility, would you guys mind re-testing with HEAD?

**Comment by zekizeki** [comment] 2015-04-16 07:42
@hairyhenderson OK so some progress, this is confirming my wierd observation from yesterday that docker-machine is trying to connect to localhost:22

So I tried running again with your commands with no success. It was once again trying to connect to localhost:22 and looping endlessly. So... I thought I'd give it what it wanted and enabled ssh logins on my Mac and boom... it stopped looping and jumped onto the next steps...  My premise is this is working for people who have ssh enabled on the machine they are running it from...

In the below trace this was stuck on the PUBLISH_SERVICE_DATA step until i enabled SSH

Some of the output about IP addresses is just extra debug i added. As you can see the machine setup still didn't fully complete for me but getting closer

```
DEBU[0219] Still waiting - active transaction is POWER_ON... 
DEBU[0223] Still waiting - active transaction is POWER_ON... 
DEBU[0226] Still waiting - active transaction is POWER_ON... 
DEBU[0229] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0232] Still waiting - active transaction is INSTALL_COMPLETE... 
DEBU[0235] Still waiting - active transaction is START_SERVICE_SETUP... 
DEBU[0237] Still waiting - active transaction is PUBLISH_SERVER_DATA... 
DEBU[0364] GetIP - IP stored is                         
DEBU[0364] GetIP - none stored, calling GetPublicIp     
DEBU[0365] Primary IP data is "159.8.10.126"            
DEBU[0365] Primary IP extracted is 159.8.10.126         
DEBU[0365] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=30 -o LogLevel=quiet -p 22 -i /Users/robsmart/.docker/machine/machines/dm00/id_rsa root@159.8.10.126 sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq curl 
Ign http://mirrors.service.networklayer.com trusty InRelease
Ign http://mirrors.service.networklayer.com trusty-updates InRelease
Ign http://mirrors.service.networklayer.com trusty-security InRelease
Hit http://mirrors.service.networklayer.com trusty Release.gpg
Hit http://mirrors.service.networklayer.com trusty-updates Release.gpg
Hit http://mirrors.service.networklayer.com trusty-security Release.gpg
Hit http://mirrors.service.networklayer.com trusty Release
Hit http://mirrors.service.networklayer.com trusty-updates Release
Hit http://mirrors.service.networklayer.com trusty-security Release
Hit http://mirrors.service.networklayer.com trusty/main Sources
Hit http://mirrors.service.networklayer.com trusty/restricted Sources
Hit http://mirrors.service.networklayer.com trusty/universe Sources
Hit http://mirrors.service.networklayer.com trusty/multiverse Sources
Hit http://mirrors.service.networklayer.com trusty/main amd64 Packages
Hit http://mirrors.service.networklayer.com trusty/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com trusty/universe amd64 Packages
Hit http://mirrors.service.networklayer.com trusty/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com trusty/main i386 Packages
Hit http://mirrors.service.networklayer.com trusty/restricted i386 Packages
Hit http://mirrors.service.networklayer.com trusty/universe i386 Packages
Hit http://mirrors.service.networklayer.com trusty/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com trusty/main Translation-en
Hit http://mirrors.service.networklayer.com trusty/multiverse Translation-en
Hit http://mirrors.service.networklayer.com trusty/restricted Translation-en
Hit http://mirrors.service.networklayer.com trusty/universe Translation-en
Hit http://mirrors.service.networklayer.com trusty-updates/main Sources
Hit http://mirrors.service.networklayer.com trusty-updates/restricted Sources
Hit http://mirrors.service.networklayer.com trusty-updates/universe Sources
Hit http://mirrors.service.networklayer.com trusty-updates/multiverse Sources
Hit http://mirrors.service.networklayer.com trusty-updates/main amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/universe amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/main i386 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/restricted i386 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/universe i386 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com trusty-updates/main Translation-en
Hit http://mirrors.service.networklayer.com trusty-updates/multiverse Translation-en
Hit http://mirrors.service.networklayer.com trusty-updates/restricted Translation-en
Hit http://mirrors.service.networklayer.com trusty-updates/universe Translation-en
Hit http://mirrors.service.networklayer.com trusty-security/main Sources
Hit http://mirrors.service.networklayer.com trusty-security/restricted Sources
Hit http://mirrors.service.networklayer.com trusty-security/universe Sources
Hit http://mirrors.service.networklayer.com trusty-security/multiverse Sources
Hit http://mirrors.service.networklayer.com trusty-security/main amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-security/restricted amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-security/universe amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-security/multiverse amd64 Packages
Hit http://mirrors.service.networklayer.com trusty-security/main i386 Packages
Hit http://mirrors.service.networklayer.com trusty-security/restricted i386 Packages
Hit http://mirrors.service.networklayer.com trusty-security/universe i386 Packages
Hit http://mirrors.service.networklayer.com trusty-security/multiverse i386 Packages
Hit http://mirrors.service.networklayer.com trusty-security/main Translation-en
Hit http://mirrors.service.networklayer.com trusty-security/multiverse Translation-en
Hit http://mirrors.service.networklayer.com trusty-security/restricted Translation-en
Get:1 http://mirrors.service.networklayer.com trusty-security/universe Translation-en [52.1 kB]
Ign http://mirrors.service.networklayer.com trusty/main Translation-en_US
Ign http://mirrors.service.networklayer.com trusty/multiverse Translation-en_US
Ign http://mirrors.service.networklayer.com trusty/restricted Translation-en_US
Ign http://mirrors.service.networklayer.com trusty/universe Translation-en_US
Fetched 52.1 kB in 3s (13.7 kB/s)
W: Failed to fetch http://mirrors.service.networklayer.com/ubuntu/dists/trusty-security/universe/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERRO[0369] Error creating machine: exit status 100      
WARN[0369] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0369] Error creating machine                       
```

**Comment by zekizeki** [comment] 2015-04-16 09:35
@hairyhenderson The problem is in the softlayer/driver.go file, d.IPAddress is never set and so in driver.go Create() method the ssh.WaitForTCP(d.IPAddress + ":22")   method passes in a blank string as the address. This must then default to localhost in the net library used in WaitForTCP.

In addition there are two methods called GetIP and getIP that otherwise have the same method signature and are called at different places. getIP takes into account whether the privatenetwork is to be used so this is the one that should be kept. neither however set d.IPAddress.

**Comment by hairyhenderson** [comment] 2015-04-16 11:27
@zekizeki - wow, nice find! :+1:

**Comment by hairyhenderson** [comment] 2015-04-16 11:30
@zekizeki - feel free to issue a PR and I'll take a look :)

**Comment by zekizeki** [comment] 2015-04-16 12:30
@hairyhenderson apologies I cancelled the first pull after some first timer commit issues, go fmt, signature etc. second pull request passes travis fine though. The fix for this issue is just a one liner.

**Comment by zekizeki** [comment] 2015-04-17 17:49
@wzymaster this should work for you now if you pull and build the latest.

**Comment by ehazlett** [comment] 2015-04-20 13:52
Closing as this appears to be fixed.  Feel free to re-open if the issue persists.  Thanks!

**Closed by ehazlett** 2015-04-20 13:52 UTC
Labels: driver:softlayer

**Comment by wzymaster** [comment] 2015-04-20 16:22
@zekizeki thanks for your update and wonder if this one is included in Docker-machine 0.2.0 or I have to pull the latest code to build a new binary myself ?

**Comment by zekizeki** [comment] 2015-04-20 19:06
@wzymaster I'm pretty sure it didn't make it in time unfortunately so you'll need to pull and build.

**Comment by ehazlett** [comment] 2015-04-20 19:44
@wzymaster yes you need from master.  if you just want a binary, you can use these (latest builds from master: https://docker-machine-builds.evanhazlett.com/latest/).  We may cut a point release if need be.  Thanks!
