### ISSUE TITLE
Cannot create Hyper-V VM under Windows 8.1

### ISSUE THREAD

**Issue by ecourtenay** [docker/machine#1163] opened 2015-05-13 09:32 UTC
I'm trying to use docker-machine 0.2.0 (x64)  to create an instance on my local development system with Hyper-V enabled. Running as a user with administrator access:

```
C:\Tools\docker> docker-machine create -d hyper-v dockervm
ERRO[0002] Error creating machine: Hyper-V PowerShell Module is not available
WARN[0002] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0002] Error creating machine
C:\Tools\docker>
```

A definition is created at $env:USERPROFILE\.docker\machine\machines\dockervm

I've had  a look at the source, but the test that's being used to find the Powershell module works on my system:

```
C:\Tools\docker> @(Get-Command Get-VM).ModuleName
Hyper-V
```

**Comment by rgardler** [comment] 2015-05-18 18:58
Are you running the docker-machine command as an admin?

**Comment by ecourtenay** [comment] 2015-05-18 19:43
Yeah, running from an elevated Powershell console

**Comment by rgardler** [comment] 2015-05-18 20:38
"Currently, Docker recommends that you install and use Docker Machine on Windows with msysgit. This will provide you with some programs that Docker Machine relies on such as ssh, as well as a functioning shell." - http://docs.docker.com/machine/

Can you try msysgit and see if you see the same issue (available from http://msysgit.github.io/)

**Comment by pmario** [comment] 2015-06-24 13:18
@ecourtenay is this still a problem. there have been several improvements in 0.3.0. 

You may also define the virtual switch. I had this problem too. The debug mode may tell you what's going wrong. Take care, to update your boot2docker image too.

`docker-machine create -d hyper-v --hyper-v-virtual-switch <your-switch-name-here>  dockervm`

**Comment by hideaki-t** [comment] 2015-08-27 12:55
I had the same issue on Windows 10 with 0.4.1.
In my case, the error came from a message from posh-git(Could not find ssh-agent)

**Comment by mfcollins3** [comment] 2015-10-18 15:06
I'm getting this problem with Windows 8.1. I think that the problem is that I have a PowerShell profile created that runs commands when a new PowerShell console is created and the commands output messages to stdout when the new PowerShell session starts. I think that the call to powershell.exe needs to include -NoProfile on the command line.

**Comment by twindagger** [comment] 2015-11-02 19:37
I had the same issue - @mfcollins3 pointed me in the right direction. Temporarily emptying my profile allowed me to create the machine.

**Comment by dgageot** [comment] 2016-01-13 15:00
Hello @ecourtenay @hideaki-t @mfcollins3 can you try on again with docker-machine 0.5.6?

**Comment by dgageot** [comment] 2016-02-12 01:46
Closing since the original issue was with docker-machine 0.2.0 and couldn't be replicated since

**Closed by dgageot** 2016-02-12 01:46 UTC
Labels: driver/hyperv, kind/quality
