### ISSUE TITLE
Save debug level logs temporarily to /tmp

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/machine#2992] opened 2016-02-04 21:43 UTC
When someone posts an issue with a driver (such as flakiness), and they run docker-machine _without_ `--debug`, we will not have full visibility into the events.

But if we actually store the detailed log output and save it to some random temp file on the filesystem and still show the user only the INFO level statements, they can send us the log file from /tmp/* when some flakiness occurs even though they're not in debug mode.

I'm not sure if this has come up before but it can make things a lot easier. When I publish a driver I am almost certain this will happen and I will tell them "please repro this with `--debug` flag and send me the output".

**Comment by nathanleclaire** [comment] 2016-04-22 18:28
Thanks, I like the idea and it's essentially a dupe of https://github.com/docker/machine/issues/1821

**Closed by nathanleclaire** 2016-04-22 18:28 UTC
Labels: area/cli, kind/enhancement
