### ISSUE TITLE
docker-machine create with Azure driver doesn't work with service principals

### ISSUE THREAD

**Issue by bsmithb2** [docker/machine#3493] opened 2016-06-10 00:45 UTC
Hi,

I'm trying to automate the creation of my docker host in the cloud. However using the following I end up with the interactive login asking me to go to aka.ms/devicelogin when I'm already logged in. How do I fix it?

```
azure config mode arm

azure login -u "serviceprincipalGUID" -p "serviceprincipalpassword" --service-principal --tenant "tenantid"
azure account list --> WORKS (logged into azure)
docker-machine ls--> WORKS (no machines)

docker-machine create -d azure   --azure-ssh-user ops   --azure-subscription-id <<SubID>>  machine   --> INTERACTIVE LOGIN REQUESTED HERE

```
Thanks,

Bradley

**Comment by ahmetalpbalkan** [comment] 2016-06-17 06:53
Duplicate of #3199

**Comment by ahmetalpbalkan** [comment] 2016-08-15 20:15
@bsmithb2 check my comment here: https://github.com/docker/machine/pull/3665#issuecomment-239915190
@nathanleclaire please close as this is duplicate.

**Closed** 2016-08-16 00:03 UTC
