### ISSUE TITLE
virtualbox: docker-machine hangs at ssh attempt when host can't support 64 bit VMs

### ISSUE THREAD

**Issue by jeffbrl** [docker/machine#1443] opened 2015-07-01 12:17 UTC
I'd like to see a more graceful exit with a helpful error message when the host can't run the 64 bit boot2docker image. Currently docker-machine hangs while it attempts to ssh into the virtualbox VM before eventually timing out. VBoxManage shows the machine in "running" state; however, it does not boot if CPU virtualization extensions are not present.

I noticed this problem using a Ubuntu 14.04 VM in VMware Workstation. I forgot to enable the "Virtualize Intel VT-x/EPT or AMD-V/RVI" checkbox in the VM's CPU settings.

**Comment by nathanleclaire** [comment] 2015-07-06 22:38
Hm, agreed.  I wonder if there's a way to detect the "feasibility" of booting successfully.

**Comment by jeffbrl** [comment] 2015-07-13 18:57
I've been studying the docs for VBoxManage. I don't see a way to determine a successful boot. Failure to ping is one indicator; however, there could be other reasons why the network stack isn't working.

**Comment by dgageot** [comment] 2015-10-30 14:54
@jeffbrl This should be fixed with [0.5.0-rc4](https://github.com/docker/machine/releases/tag/v0.5.0-rc4)
You will get an error message saying what the problem is.
Feel free to re-open in case it isn't.

**Closed by dgageot** 2015-10-30 14:54 UTC
Labels: driver/virtualbox

**Comment by jeffbrl** [comment] 2015-10-30 14:55
Great. Thanks, David.
