### ISSUE TITLE
service docker restart hangs when run on centos 7 ami

### ISSUE THREAD

**Issue by tommyoshaw** [docker/machine#1764] opened 2015-08-26 14:09 UTC
docker-machine version 0.4.0 (9d0dc7a)

Trying to start a machine based on : CentOS 7 x86_64 (2014_09_29) EBS HVM-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d2a117ba.2 (ami-c7d092f7)

All looks good until : systemctl restart docker

Hangs here and then exits with code 1.

ssh'ed into the instance the following process was still running whenever systemctl restart docker was called 

mkfs.ext4 -E nodiscard,lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/docker-202:1-8589003-base

Perhaps a timing/locking issue?  docker-engine install, systemctl reload and systemctl restart docker in quick succession.  

Using ubuntu ami until this is resolved.

Thanks.

**Comment by ehazlett** [comment] 2015-08-26 19:28
Looks like a duplicate of #1698

**Comment by kacole2** [comment] 2015-08-26 20:06
@ehazlett @tommyoshaw yes this is a duplicate. I have a feeling it has something to do with device-mapper. will need to investigate further.

**Comment by dgageot** [comment] 2015-10-14 11:35
Closing duplicate of #1698

**Closed by dgageot** 2015-10-14 11:35 UTC
Labels: area/provision
