### ISSUE TITLE
Symlinks corrupt in shared folders

### ISSUE THREAD

**Issue by ain** [docker/machine#2050] opened 2015-10-21 23:55 UTC
Symlinks that are in (nested) shared folder, get corrupt with `vmwarefusion` driver, e.g.:

Local symlink:
```
lrwxr-xr-x   1 ain  staff    20 Jul  3 20:46 recaptcha.yml -> recaptcha.yml.docker
```

Same symlink in container:
```
lrwxr-xr-x 1 501 dialout   20 Jul  3 18:46 recaptcha.yml -> cha.yml.docker
```

Platform info:
```
Mac OS X 10.11
VMWare Fusion Version 8.0.1 (3094680)

$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

$ docker-machine --version
docker-machine version 0.5.0-rc2 (6cac8cc)

$ docker-compose --version
docker-compose version: 1.4.2
```

**Comment by ain** [comment] 2015-10-22 00:02
Docker Compose `1.5.0 RC1` does not improve the behaviour.

**Comment by nathanleclaire** [comment] 2015-10-22 00:29
cc @frapposelli

**Comment by frapposelli** [comment] 2015-10-22 16:30
@ain wow, this is extremely weird, can you do me a `df -h` and `mount` from inside the boot2docker vm?

**Comment by ain** [comment] 2015-10-22 23:22
```
$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.5M    115.2M    781.3M  13% /
tmpfs                   498.0M    740.0K    497.3M   0% /dev/shm
/dev/sda1                18.2G      3.9G     13.3G  23% /mnt/sda1
cgroup                  498.0M         0    498.0M   0% /sys/fs/cgroup
vmhgfs-fuse             464.8G    361.3G    103.4G  78% /mnt/hgfs
vmhgfs-fuse             464.8G    361.3G    103.4G  78% /Users
/dev/sda1                18.2G      3.9G     13.3G  23% /mnt/sda1/var/lib/docker/aufs
none                     18.2G      3.9G     13.3G  23% /mnt/sda1/var/lib/docker/aufs/mnt/80f01b6dc0146584d68e686c2b6f4c0be8ff4800b2a411770b89b32faf3a0569
df: /var/run/docker/netns/80f01b6dc014: Permission denied
none                     18.2G      3.9G     13.3G  23% /mnt/sda1/var/lib/docker/aufs/mnt/9b9a64bf781d8760a06ee1cd151ca1f4a7cdd1f70b393b575dbf855f2c9ddeff
df: /var/run/docker/netns/9b9a64bf781d: Permission denied
none                     18.2G      3.9G     13.3G  23% /mnt/sda1/var/lib/docker/aufs/mnt/7c784a25adbee30fb12af1de21f7459bba596e355cb9eb6364207ccf6b5c9628
df: /var/run/docker/netns/7c784a25adbe: Permission denied
none                     18.2G      3.9G     13.3G  23% /mnt/sda1/var/lib/docker/aufs/mnt/08a863d6dd000904f840ea1f87ff6222a58d511fe4c89c2ba6233bcd021f23db
df: /var/run/docker/netns/08a863d6dd00: Permission denied
```

```
$ mount
tmpfs on / type tmpfs (rw,relatime,size=918000k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
vmhgfs-fuse on /mnt/hgfs type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
vmhgfs-fuse on /Users type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
none on /mnt/sda1/var/lib/docker/aufs/mnt/80f01b6dc0146584d68e686c2b6f4c0be8ff4800b2a411770b89b32faf3a0569 type aufs (rw,relatime,si=1df9f3808f8828fc,dio,dirperm1)
nsfs on /var/run/docker/netns/80f01b6dc014 type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/9b9a64bf781d8760a06ee1cd151ca1f4a7cdd1f70b393b575dbf855f2c9ddeff type aufs (rw,relatime,si=1df9f3808e6298fc,dio,dirperm1)
nsfs on /var/run/docker/netns/9b9a64bf781d type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/7c784a25adbee30fb12af1de21f7459bba596e355cb9eb6364207ccf6b5c9628 type aufs (rw,relatime,si=1df9f3808eb828fc,dio,dirperm1)
nsfs on /var/run/docker/netns/7c784a25adbe type nsfs (rw)
none on /mnt/sda1/var/lib/docker/aufs/mnt/08a863d6dd000904f840ea1f87ff6222a58d511fe4c89c2ba6233bcd021f23db type aufs (rw,relatime,si=1df9f3808e60c8fc,dio,dirperm1)
nsfs on /var/run/docker/netns/08a863d6dd00 type nsfs (rw)
```

**Comment by ain** [comment] 2015-10-23 21:48
Tried also with following versions, no improvement:
```
$ docker version
Client:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:29:07 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by ain** [comment] 2015-10-24 23:04
Another fact: absolute symlinks don't work either:

Actual:
```
lrwxr-xr-x  1 ain  staff    65 Oct 25 01:01 docker-blah-blah-vlah.yml -> /Users/ain/Documents/projects/docker-drubian/6/docker-compose.yml
```
Docker:
```
lrwxr-xr-x  1  501 dialout   65 Oct 24 23:01 docker-blah-blah-vlah.yml -> /ain/Documents/projects/docker-drubian/6/docker-compose.yml
```

**Comment by frapposelli** [comment] 2015-10-24 23:10
OK, I'm able to reproduce the problem, which is kinda weird:

```
GH-2050 ⟩ pwd
/Users/frapposelli/scratch/GH-2050
GH-2050 ⟩ ls -al
total 16
drwxr-xr-x   4 frapposelli  staff  136 Oct 25 01:00 .
drwxr-xr-x  29 frapposelli  staff  986 Oct 24 23:31 ..
lrwxr-xr-x   1 frapposelli  staff   20 Oct 25 01:00 recaptcha.yml -> recaptcha.yml.docker
-rw-r--r--   1 frapposelli  staff    5 Oct 25 01:00 recaptcha.yml.docker
GH-2050 ⟩ docker-machine ssh gh-2050 'ls -al /Users/frapposelli/scratch/GH-2050'
total 3
drwxr-xr-x    1 501      20             136 Oct 24 23:00 .
drwxr-xr-x    1 501      20             986 Oct 24 21:31 ..
lrwxr-xr-x    1 501      20              20 Oct 24 23:00 recaptcha.yml -> cha.yml.docker
-rw-r--r--    1 501      20               5 Oct 24 23:00 recaptcha.yml.docker
GH-2050 ⟩ docker-machine ssh gh-2050 'ls -al /mnt/hgfs/Users/frapposelli/scratch/GH-2050'
total 3
drwxr-xr-x    1 501      20             136 Oct 24 23:00 .
drwxr-xr-x    1 501      20             986 Oct 24 21:31 ..
lrwxr-xr-x    1 501      20              20 Oct 24 23:00 recaptcha.yml -> recaptcha.yml.docker
-rw-r--r--    1 501      20               5 Oct 24 23:00 recaptcha.yml.docker
```

Apparently the mount point `/Users` acts up while using `/mnt/hgfs` works correctly, this is most likely a bug, I will forward this internally to make sure we address it.

Right now a possible workaround is to prepend `/mnt/hgfs` to the source of any volume you mount.

**Comment by ain** [comment] 2015-10-24 23:24
I see. Good catch, thanks for reproducing @frapposelli!

**Comment by dburry** [comment] 2015-10-28 18:09
I've run into this issue as well.  For now @frapposelli 's workaround seems to work by modifying my `docker-compose.yml` from:
```
  volumes:
    - .:/app
```
to:
```
  volumes:
    - /mnt/hgfs${PWD}:/app
```

**Comment by dgageot** [comment] 2015-11-02 14:32
Hi @frapposelli Any news?

**Comment by adambiggs** [comment] 2015-11-04 16:29
+1 this is affecting my team as well.

**Comment by frapposelli** [comment] 2015-11-04 22:13
Not yet, I'll update you guys as soon as I have news.

**Comment by NickClark** [comment] 2016-01-05 22:48
:+1: Waiting on this as well...

**Comment by ain** [comment] 2016-02-10 15:30
Any updates here?

**Comment by ain** [comment] 2016-02-10 16:22
@dburry any ideas on how would mount the users home (`~`) without hardcoding it?

**Comment by dburry** [comment] 2016-02-11 00:51
@ain I would imagine one might be able to substitute ${HOME} instead of ${PWD} in my example above... it's just an environment variable referring to the home or current directory, respectively.

**Comment by nathanleclaire** [comment] 2016-02-11 00:55
@ain If you use Compose you can do `.:/foo` notation in volumes block and it will always expand (I think to the directory where the Compose file itself is located).  Docker CLI always takes absolute paths so most do something like `docker run -v $(pwd):/foo` if they are scripting it.

**Comment by ain** [comment] 2016-02-11 08:50
@dburry I'd think `HOME` is not referring to home on host, but the guest. The idea I got from your suggestion tho is to pass in `ENV` variable with the backreference to `/mnt/hgfs/Users…` somehow…

**Comment by ain** [comment] 2016-02-11 08:54
@nathanleclaire no they are not expanding and that is actually the essence of this ticket. The only way to access host is to go over `/mnt/hgfs/Users…`.

**Comment by SeerUK** [comment] 2016-03-02 10:13
Also having this issue, but this current workaround is simply not feasible. We have mixed platforms on our team on both Linux and OS X, we are using Docker precisely to avoid having to put in system-specific things like that.

Has there been any kind of update on this one? Does it happen with any other drivers? I've only been able to test on VMWare Fusion currently.

**Comment by ain** [comment] 2016-03-02 10:25
@SeerUK this and #1789 are the main blockers for us at Interactive Pioneers so we're still running on VirtualBox and docker-osx-dev (for performance) for OS X based development environment.

**Comment by SeerUK** [comment] 2016-03-02 10:51
From what I can tell, if you are using relative paths you can work around the issue by padding the path with several `./././././`s, it seems that it cuts off some characters from the start of the symlink's target. So if you pad it out it might work.

This will then mean it at least works on both Linux and OS X systems alike, but is still not an ideal solution. I'm considering just buying parallels and being done with it...

**Comment by SeerUK** [comment] 2016-03-02 14:15
As an update to this, I've done some playing around in the machine itself, I've discovered that if you were to unmount the `/Users` mount, and remount it like so:

```
$ mount --bind /mnt/hgfs/Users /Users
```

It seems to resolve the issue. This has led me to investigating the command that is used to perform the mount when the VM is started in the VMWare Fusion driver. It looks something more like either:

```
$ sudo /usr/local/bin/vmhgfs-fuse -o allow_other .host:/Users /Users
```

or

```
$ sudo mount -t vmhgfs -o uid=$(id -u),gid=$(id -g) .host:/Users /Users
```

I wonder if we were to change how this bind command is executed, or perhaps add an extra conditional statement at the start (like how these 2 are currently separated), if that would resolve the issue.

**Comment by SeerUK** [comment] 2016-03-07 23:50
@frapposelli What do you think of the above solution? I've created a [PR](https://github.com/docker/machine/pull/3140) for it, and it has been working now for me since I started using a build of docker-machine that includes the aforementioned fix, after several docker-machine and host machine reboots.

I'm quite keen to see this issue be resolved, as I'm currently having to tell my team to build docker-machine from my branch just to get it working, as we've already invested in VMWare Fusion for our OS X devs.

Any update would be greatly appreciated! :)

**Comment by frapposelli** [comment] 2016-03-07 23:52
@SeerUK seems like a reasonable workaround, I've just LGTM'd your PR.

**Comment by SeerUK** [comment] 2016-03-07 23:53
Excellent, thank you. This is my first contribution, I'm assuming now we wait for a Docker member to merge the PR if it also looks good to them?

**Comment by nathanleclaire** [comment] 2016-03-08 00:45
@SeerUK Just merged it :+1: Thanks

**Closed** 2016-03-08 00:45 UTC
Labels: driver/vmwarefusion, kind/bug, kind/question
