### ISSUE TITLE
Machine create fails with latest Docker

### ISSUE THREAD

**Issue by dminkovsky** [docker/machine#4156] opened 2017-06-29 01:18 UTC
Hello

docker-machine version 0.12.0, build 45c69ad

`docker-machine create` fails now:

```
docker-machine -D create \
    --driver google \
    --google-project project \
    --google-zone us-east1-d \
    --google-machine-type n1-standard-1 \
    --google-disk-size 20 \
    --google-preemptible \
    build-vm2
```
The machine is created and Docker is installed, but it won't start. The problem appears to be a related to a new version of Docker getting installed by a new version of the install script over at https://get.docker.com. My installs went from 17.05.0-ce to 17.06.0-ce, and with that change, Docker installs but does not start.

    Jun 29 00:50:08 build-vm2 docker[5705]: `docker daemon` is not supported on Linux. Please run `dockerd` directly

or 

    Jun 29 00:56:12 build-vm2 dockerd[6407]: Error starting daemon: error initializing graphdriver: driver not supported

Unless I change:

    /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=google

to 

    /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=google

in `/etc/systemd/system/docker.service.d/10-machine.conf`.

**Comment by thanhhx-zinza** [comment] 2017-06-29 04:54
Same problem here
```
docker-machine create 
    --driver=digitalocean
    --digitalocean-access-token=XXX 
    --digitalocean-size=2gb
    machinename
```
Yesterday the same command worked fine with docker version 17.05.0-ce
Today my new machine's docker won't start (17.06.0-ce)
I've tried multiple time.

**Comment by gnomus** [comment] 2017-06-29 08:23
I can confirm this too:

```
dm create -d digitalocean \
--digitalocean-access-token XXX \
--digitalocean-size 4gb machine
```

**Comment by therealppa** [comment] 2017-06-29 12:45
Is there any idea for a workaround?

**Comment by acouette** [comment] 2017-06-29 12:47
I have the same issue.

docker version : Docker version 17.06.0-ce
docker-machine version : 0.12.0, build 45c69ad

`docker-machine create --driver amazonec2 --amazonec2-region eu-west-1 --amazonec2-instance-type t2.small --amazonec2-access-key XXX --amazonec2-secret-key XXX test-create-machine`

Jun 29 12:26:56 ip-172-31-10-149 systemd[1]: Starting Docker Application Container Engine...
Jun 29 12:26:56 ip-172-31-10-149 docker[5234]: `docker daemon` is not supported on Linux. Please run `dockerd` directly

> `docker daemon` is not supported on Linux. Please run `dockerd` directly

**Comment by thanhhx-zinza** [comment] 2017-06-29 12:50
I temporary downgraded docker to 17.05.0-ce on the same machine and everything work fine.

**Comment by gnomus** [comment] 2017-06-29 12:51
I was able to get it working with this PR
https://github.com/docker/machine/pull/4128

Just compile docker-machine with this fix and everything works again

**Comment by dminkovsky** [comment] 2017-06-29 13:02
@gnomus super, that's interesting! I wonder why it was working for 17.05.0-ce, though. 

@therealppa haahaha awesome! I was wondering how I might get the old version of that script, or whether the live script takes params to install older version. web.archive.org definitely didn't not occur to me.

**Comment by therealppa** [comment] 2017-06-29 13:06
@dminkovsky I don't think it will work forever, if you look into the script it doesn't actually specify the version anywhere... Still, right now it works.

**Comment by kurrestahlberg** [comment] 2017-06-29 13:22
@therealppa @dminkovsky A longer term fix is to change the line 457 of the script from
```
$sh_c 'apt-get install -y -q docker-ce'
```
to 
```
$sh_c "apt-get install -y -q docker-ce=17.05.0~ce-0~$lsb_dist-$dist_version"
```

Hopefully the fixed version of docker-machine is released soon.

**Comment by dminkovsky** [comment] 2017-06-29 14:27
@fabio-barile what about the `--storage-driver aufs` arg? Mine wouldn't start unless I got rid of that, too.

**Comment by JustEra** [comment] 2017-06-29 15:40
@dminkovsky I had the same problem on a autoscaling ci with gitlab, got the aufs problem + dockerd problem, had to solve it with specifying overlay in the storage driver.

**Comment by lusitania** [comment] 2017-06-29 15:59
@JustEra beyond the storage driver issue I'm also seeing verification errors for certificates created by gitlab-runner (9.3.0). Have you been running into the same issue or am I the only one?
```
http: TLS handshake error from ...:
 tls:
  failed to verify client's certificate: x509:
   certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "unknown")
```
```
ERROR: Error creating machine:
 Error checking the host:
  Error checking and/or regenerating the certs:
   There was an error validating certificates for host "...":
    remote error: tls: bad certificate  driver=amazonec2 name=...
```

**Comment by aleks-m** [comment] 2017-06-29 16:13
This fixed storage-driver issue for me (just removed that parameter). Apply on top of https://github.com/docker/machine/pull/4128 and re-build:
```
diff --git a/libmachine/provision/systemd.go b/libmachine/provision/systemd.go
index 90d02603..05d63bb5 100644
--- a/libmachine/provision/systemd.go
+++ b/libmachine/provision/systemd.go
@@ -53,7 +53,7 @@ func (p *SystemdProvisioner) GenerateDockerOptions(dockerPort int) (*DockerOptio

        engineConfigTmpl := `[Service]
 ExecStart=
-ExecStart=/usr/bin/` + arg + ` -H tcp://0.0.0.0:{{.DockerPort}} -H unix:///var/run/docker.sock --storage-driver {{.EngineOptions.StorageDriver}} --tlsverify --tlscacert {{.AuthOptions.CaCertRemotePath}} --tlscert {{.AuthOptions.ServerCertRemotePath}} --tlskey {{.AuthOptions.ServerKeyRemotePath}} {{ range .EngineOptions.Labels }}--label {{.}} {{ end }}{{ range .EngineOptions.InsecureRegistry }}--insecure-registry {{.}} {{ end }}{{ range .EngineOptions.RegistryMirror }}--registry-mirror {{.}} {{ end }}{{ range .EngineOptions.ArbitraryFlags }}--{{.}} {{ end }}
+ExecStart=/usr/bin/` + arg + ` -H tcp://0.0.0.0:{{.DockerPort}} -H unix:///var/run/docker.sock --tlsverify --tlscacert {{.AuthOptions.CaCertRemotePath}} --tlscert {{.AuthOptions.ServerCertRemotePath}} --tlskey {{.AuthOptions.ServerKeyRemotePath}} {{ range .EngineOptions.Labels }}--label {{.}} {{ end }}{{ range .EngineOptions.InsecureRegistry }}--insecure-registry {{.}} {{ end }}{{ range .EngineOptions.RegistryMirror }}--registry-mirror {{.}} {{ end }}{{ range .EngineOptions.ArbitraryFlags }}--{{.}} {{ end }}
```

**Comment by vincent99** [comment] 2017-06-29 17:40
For anyone who wants a specific older version, we (Rancher) maintain slightly modified get.docker.com scripts to install each one:

http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

**Comment by narration-sd** [comment] 2017-06-30 00:40
@fabio-barile above is entirely correct. How 'testing' lets things be emitted, can't imagine.

More information here: https://github.com/docker/for-linux/issues/11#issuecomment-312143765

**Comment by systemmonkey42** [comment] 2017-06-30 06:42
+1
I check back every day for a new docker-machine release... This bug is killing me :-)

For now, I add /etc/systemd/system/docker.service.d/20-machine.conf which overrides 10-machine.conf with the correct command line.   That way further docker-machine command which would normally break it, doesn't.  Of course the longer it takes for this to be fixed in the release, the more work I have putting everything back!

**Comment by FrenchBen** [comment] 2017-06-30 15:47
Thanks for the great breakdown of details on the issue - We're looking into it to try and figure out what went wrong.

**Comment by seemethere** [comment] 2017-06-30 16:36
So this is not related to the install script at `get.docker.com` but rather related to the version comparison not working correctly and with 17.06.0-ce being the first to officially deprecate `docker daemon` that is why we are seeing failures.

This PR (docker/machine#4128) seems to remedy this issue and I'll have a PR up by late afternoon that adds tests for the other comparison functions so that we don't run into something like this again.

**Comment by narration-sd** [comment] 2017-06-30 16:59
@seemethere  Sounds good, thanks.  Like to hear about the test.

The diff on one of the PRs appeared a little odd to me, but think you guys will have taken care of that.

**Comment by shin-** [comment] 2017-06-30 22:36
The 0.12.1 release fixes this bug. Thanks everyone for your patience and your help.

**Closed** 2017-06-30 22:36 UTC
Labels: area/provision, kind/bug

**Comment by dminkovsky** [comment] 2017-07-01 23:49
@shin- thanks for the quick fix! Looking forward to using it.

**Comment by dminkovsky** [comment] 2017-07-02 12:17
@shin- it the `docker daemon` -> `dockerd` part, but Docker still doesn't start on the machine due to 

    dockerd[6407]: Error starting daemon: error initializing graphdriver: driver not supported

**Comment by dminkovsky** [comment] 2017-07-02 12:30
@shin- I was able to get around the storage driver issue by adding `--engine-storage-driver=overlay (https://github.com/docker/machine/issues/3895#issuecomment-270934728). So here's my whole `docker-machine` invocation.

```
docker-machine -D create \
    --driver google \
    --google-project $project \
    --google-zone $zone \
    --google-machine-type $type \
    --google-disk-size $size \
    --google-preemptible \
    --engine-storage-driver=overlay \
    $name
```

Without `--engine-storage-driver=overlay` it still fails with 

    dockerd[6407]: Error starting daemon: error initializing graphdriver: driver not supported

as before and as in #3895

**Comment by cadavre** [comment] 2017-07-07 13:39
@shin- unfortunately 0.12.1 didn't fixed this for me.

```
$ docker -v
Docker version 17.06.0-ce, build 02c1d87
$ docker-machine -v
docker-machine version 0.12.1, build c8b17e8
```

I'm creating an `amazonec2` machine with `--amazonec2-region=eu-central-1` which creates an `ami-fe408091` for me.

The output from `docker-machine create` is:

```
Running pre-create checks...
Creating machine...
(test-d-m) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

Output from launched machine is:

```
$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: inactive (dead) (Result: exit-code) since Fri 2017-07-07 13:34:47 UTC; 36s ago
     Docs: https://docs.docker.com
  Process: 5522 ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacer
 Main PID: 5522 (code=exited, status=1/FAILURE)

Jul 07 13:34:46 test-d-m systemd[1]: docker.service: Unit entered failed state.
Jul 07 13:34:46 test-d-m systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 07 13:34:47 test-d-m systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 07 13:34:47 test-d-m systemd[1]: Stopped Docker Application Container Engine.
Jul 07 13:34:47 test-d-m systemd[1]: docker.service: Start request repeated too quickly.
Jul 07 13:34:47 test-d-m systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by dminkovsky** [comment] 2017-07-07 14:41
Did you see the log that explained why it crashed?

**Comment by drujensen** [comment] 2017-07-07 14:48
@dminkovsky Thanks for the workaround.  I decided to use `overlay2` since its a latest version of the driver instead.  

Do you know if there a workaround for `docker-machine rm {instance-name}` as well?  I'm getting an error related to `EOF` and it leaves remnants of key pairs on the AWS cloud preventing me from recreating the instance.

**Comment by cadavre** [comment] 2017-07-07 14:49
Sorry, I removed my message after I debugged hard and noticed it's actually due to what @dminkovsky wrote:

> Without `--engine-storage-driver=overlay` it still fails with
`dockerd[6407]: Error starting daemon: error initializing graphdriver: driver not supported`
as before and as in #3895

Do we have any issue for this one particular case of using AUFS engine storage?

**Comment by dminkovsky** [comment] 2017-07-07 18:32
@cadavre 

> Do we have any issue for this one particular case of using AUFS engine storage?

I've seen https://github.com/docker/machine/issues/3895, which is open and which you also referenced.

**Comment by dminkovsky** [comment] 2017-07-07 19:00
@drujensen 

>  I decided to use overlay2 since its a latest version of the driver instead.

Oh cool, thanks, I didn't know that.

> Do you know if there a workaround for docker-machine rm {instance-name} as well?

Not sure, I haven't had that bug. I use `docker-machine rm -f` when the machine has been terminated and won't respond. With `-f`, `docker-machine` removes the VM and associated disks even if it can't reach the box.

**Comment by shin-** [comment] 2017-07-07 23:20
@dminkovsky Can you create a new issue for this? It's unrelated to the `dockerd`/`docker daemon` issue, so we should treat it separately as well. And please indicate what OS you're provisioning as well :)

**Comment by dminkovsky** [comment] 2017-07-09 19:51
@shin- i'm all good. docker-machine is working 100% right now for me. are you referring to the overlay2 thing?

**Comment by drujensen** [comment] 2017-07-09 22:07
My other issue regarding removing machines was addressed in pr #4187. Thx.

**Comment by shin-** [comment] 2017-07-10 18:32
@dminkovsky Sorry - yes, the one you mention [here](https://github.com/docker/machine/issues/4156#issuecomment-312488506)

**Comment by brandontamm** [comment] 2017-07-17 15:09
@shin - After experiencing the issue in https://github.com/docker/machine/issues/4168, I attempted to re-create my staging server and found a slough of issues with  `docker-machine create` that has been reported in multiple recent tickets:
- https://github.com/docker/machine/issues/4156
- https://github.com/docker/machine/issues/4166
- https://github.com/docker/machine/issues/4189
- https://github.com/docker/machine/issues/4197
- https://github.com/docker/machine/issues/4198

Are these all related? Start tracking these here? I can confirm that this issue is still happening today.

**Comment by costa** [comment] 2017-07-19 08:21
@shin- docker-machine v0.12.1 exhibits the same issue still

**Comment by thomanh** [comment] 2017-07-22 04:58
same issue with docker-machine v0.12.2

**Comment by Ajwah** [comment] 2017-07-26 22:56
I have the same issue on aws:
when running following command:

```
docker-machine create --amazonec2-access-key $(aws --profile $ENV configure get aws_access_key_id) \
                          --amazonec2-secret-key $(aws --profile $ENV configure get aws_secret_access_key) \
                          --amazonec2-region $EC2_REGION \
                          --amazonec2-vpc-id $VPC_ID \
                          --amazonec2-subnet-id $SUBNET_ID \
                          --amazonec2-zone $ZONE \
                          --amazonec2-instance-type $INSTANCE_TYPE \
                          --amazonec2-private-address-only=$PRIVATE_ADDRESS_ONLY \
                          --amazonec2-monitoring=$CLOUDWATCH_ENABLED \
                          --amazonec2-root-size $ROOT_DISK_SIZE \
                          --amazonec2-use-ebs-optimized-instance=$EBS_OPTIMIZED \
                          --amazonec2-volume-type $VOLUME_TYPE \
                          --amazonec2-tags $TAGS \
                          --driver amazonec2 $LATEST_DOCKER_MACHINE_NAME
```

# RESULT 
 
```
Running pre-create checks...
Creating machine...
(**************) Launching instance...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

# MORE DETAIL

```
systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: inactive (dead) (Result: exit-code) since Wed 2017-07-26 22:20:37 UTC; 39s ago
     Docs: https://docs.docker.com
  Process: 5200 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docke
 Main PID: 5200 (code=exited, status=1/FAILURE)

Jul 26 22:20:37 ************ systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 26 22:20:37 ************ systemd[1]: Failed to start Docker Application Container Engine.
Jul 26 22:20:37 ************ systemd[1]: docker.service: Unit entered failed state.
Jul 26 22:20:37 ************ systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 26 22:20:37 ************ systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 26 22:20:37 ************ systemd[1]: Stopped Docker Application Container Engine.
Jul 26 22:20:37 ************ systemd[1]: docker.service: Start request repeated too quickly.
Jul 26 22:20:37 ************ systemd[1]: Failed to start Docker Application Container Engine.
```

# RESULT WHEN DOING MANUAL START OF DOCKER SERVICE

```
systemctl start docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

# EXTRA OUTPUT

```
journalctl -xe
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has finished shutting down.
Jul 26 22:21:55 ************** systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.socket has finished shutting down.
Jul 26 22:21:55 ************** systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.socket has begun shutting down.
Jul 26 22:21:55 ************** systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.socket has begun starting up.
Jul 26 22:21:55 ************** systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.socket has finished starting up.
--
-- The start-up result is done.
Jul 26 22:21:55 ************** systemd[1]: docker.service: Start request repeated too quickly.
Jul 26 22:21:55 ************** systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Jul 26 22:21:55 ************** systemd[1]: docker.socket: Unit entered failed state.
lines 3665-3703/3703 (END)
````

**Comment by eamontaaffe** [comment] 2017-07-27 01:33
I'm still getting the same issue with version 0.12.1.

![screen shot 2017-07-27 at 11 32 00 am](https://user-images.githubusercontent.com/7099155/28650430-4881b948-72bf-11e7-950a-f84f860eea1f.png)

**Comment by FrenchBen** [comment] 2017-07-27 17:23
Please update to the latest release found on github: 
https://github.com/docker/machine/releases/tag/v0.12.2

@eamontaaffe @ajwah @costa

**Comment by soniczhangbrauz** [comment] 2017-08-02 04:18
Still getting the same issue with 0.12.2
![screen shot 2017-08-02 at 2 17 29 pm](https://user-images.githubusercontent.com/22284385/28857516-6d81c620-778d-11e7-8ae5-e989814f7679.png)

**Comment by oleynikd** [comment] 2017-08-02 16:05
Thank you @dminkovsky I was getting this error on 0.12.2 today as well!!! Seems like `10-machine.conf` file does not get overridden during update

**Comment by dminkovsky** [comment] 2017-08-02 16:34
You're welcome!

I specify "overlay" in the command line option for storage engine and since
the my machines boot.

ср, 2 авг. 2017 г. в 12:05, Denis <notifications@github.com>:

**Comment by cadavre** [comment] 2017-08-02 16:36
If using systems with kernel >4.4 I suggest using `overlay2`.

**Comment by dminkovsky** [comment] 2017-08-02 16:37
I wasn't able to get the machine to use overlay2, and the use case for this
fortunately was just building/CD

ср, 2 авг. 2017 г. в 12:36, Seweryn Zeman <notifications@github.com>:

**Comment by datesss** [comment] 2017-08-03 17:34
Also getting this error on 0.12.2 :-(

**Comment by vuongggggg** [comment] 2017-08-27 04:42
When I try to create machine in D.O, i got the same prolem (Docker v17.06.1-ce build 874a737, Docker machine v0.12.0). I just pasted the link that may be help you to solve it: https://forums.docker.com/t/failed-to-start-docker-application-container-engine/35594/2

**Comment by kassanmoor** [comment] 2017-08-29 21:28
this still opened!

**Comment by AkhilNairAmey** [comment] 2017-09-22 14:09
I still see this issue with `docker-machine 0.12.2`.  I moved forwards by uninstalling docker on the provisioned machine (`sudo apt purge docker-ce && sudo apt autoremove`) and used correct [Rancher install script](http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions) for my version as listed above.

For some reason, this still fails to start docker, but rebooting the machine then solves it.

**Comment by jhartma** [comment] 2017-09-23 09:47
Can confirm, still the same error

**Comment by kassanmoor** [comment] 2017-09-28 16:27
@jhartma I guess is necessary upgrade to latest release (linux image) and works

**Comment by jhartma** [comment] 2017-09-29 04:45
@kassanmoor seems my AMI didn't support it on AWS, I got it to work with the default one
