### ISSUE TITLE
Cannot use unix socket URL with none driver

### ISSUE THREAD

**Issue by bsuh** [docker/machine#643] opened 2015-02-27 01:00 UTC
I use ssh & socat to port forward a remote /var/run/docker.sock as a local unix socket.
I add this local unix socket using the none driver.

docker-machine ls output:
```
NAME    ACTIVE   DRIVER         STATE     URL                                             SWARM
dev              vmwarefusion   Running   tcp://192.168.2.130:2376
vultr   *        none                     unix:///Users/bsuh/.remote-sockets/vultr.sock
```

docker-machine env output:
```
docker-machine env vultr
set -x DOCKER_TLS_VERIFY yes
set -x DOCKER_CERT_PATH /Users/bsuh/.docker/machine/machines/vultr
set -x DOCKER_HOST unix:///Users/bsuh/.remote-sockets/vultr.sock
```

It tries to use TLS on a Unix socket URL.

**Comment by therealprologic** [comment] 2015-02-27 01:23
I find this doesn't work for the local host either.

e.g:

```#!bash
$ docker-machine create --url=unix:///var/run/docker.sock local
INFO[0000] "local" has been created and is now the active machine. 
INFO[0000] To point your Docker client at it, run this in your shell: $(docker-machine env local) 

$ docker $(docker-machine config local) ps
FATA[0000] An error occurred trying to connect: Get https:///var/run/docker.sock/v1.17/containers/json: tls: oversized record received with length 20527 
```

However if you remove all the TLS parameters (*by hand*):

```#!bash
$ docker-machine config local
--tls --tlscacert=/home/prologic/.docker/machine/machines/local/ca.pem --tlscert=/home/prologic/.docker/machine/machines/local/cert.pem --tlskey=/home/prologic/.docker/machine/machines/local/key.pem -H="unix:///var/run/docker.sock"

$ docker -H="unix:///var/run/docker.sock" ps
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS                                                NAMES
93281745b138        hipache:latest        "supervisord -n"       31 minutes ago      Up 31 minutes       6379/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   prologic_hipache_1   
35f998e3964b        crux/bitlbee:latest   "/entrypoint.sh /sta   31 minutes ago      Up 31 minutes       0.0.0.0:6667->6667/tcp                               prologic_bitlbee_1   
de8dd0ae9d01        crux/devpi:latest     "/usr/bin/devpi-serv   31 minutes ago      Up 31 minutes       0.0.0.0:3141->3141/tcp                               prologic_devpi_1     
```

**Comment by nathanleclaire** [comment] 2015-02-27 01:53
I'm working on a PR that should fix this.

**Comment by therealprologic** [comment] 2015-02-27 01:55
Excellent :)

**Comment by ehazlett** [comment] 2015-02-27 14:56
I'm not a fan of adding this.  Why not just use `$(docker-machine unset -u)`?  See also, https://github.com/docker/machine/pull/646#issuecomment-76406008

**Comment by nathanleclaire** [comment] 2015-02-27 21:11
@ehazlett That won't work for @bsuh's case.  I'm not sure if #646 is exactly the right solution, but I do think we need to sketch out what we feel like the purpose of the none driver is a little bit further.  Perhaps @bfirsh could elaborate on what he sees as the purpose of it.  After all, if you add a remote host with the `none` driver, you can't start, stop, etc. that either.  Unix sockets strike me as valid "hosts" so I'm not sure why we wouldn't support them.

**Comment by ehazlett** [comment] 2015-03-02 18:24
I'm not saying we shouldn't support unix sockets.  Personally i think the `none` driver should be renamed to "testing" as I think it's misleading.  I agree we need to decide how to support sockets.  Either we mandate adding an ssh key or decide if we want the commands to error out.

**Comment by thaJeztah** [comment] 2015-12-23 10:43
Having machine support a "local" daemon might help this use case: https://github.com/docker/machine/issues/2601 apparently (haven't tested) PyCharm uses docker-machine in order to obtain settings for connecting to the daemon; http://blog.jetbrains.com/pycharm/2015/12/using-docker-in-pycharm/

Also note this issue, which may be a duplicate / related: https://github.com/docker/machine/issues/1435

(perhaps name the driver "local" for this?)

**Comment by bfirsh** [comment] 2015-12-28 14:11
The only reason the "none" driver exists is because the Docker client originally configured itself from Machine. Don't think it's useful any longer.

**Comment by nathanleclaire** [comment] 2015-12-28 18:37
@bfirsh Some have been finding it useful (check out https://github.com/docker/machine/issues/2270#issue-116565799) but I think in general we should probably EOL it as it causes more confusion than it solves problems.

**Comment by dgageot** [comment] 2016-01-26 16:42
Duplicate of https://github.com/docker/machine/issues/1435

**Closed by dgageot** 2016-01-26 16:42 UTC
Labels: driver/none, kind/enhancement
