### ISSUE TITLE
Create brew.sh package

### ISSUE THREAD

**Issue by kevinsimper** [docker/machine#478] opened 2015-02-03 15:05 UTC
It could be cool to install machine by using brew.sh, as it would be easy to update.

But don't know if it should download compiled source or compile it itself?

**Comment by ehazlett** [comment] 2015-02-03 15:42
There is a formula from #130.  I think we just need to make sure it's updated and get it in the official docs if desired.  @bfirsh thoughts?

**Comment by ehazlett** [comment] 2015-02-26 16:32
Closing as a duplicate of #130

**Closed by ehazlett** 2015-02-26 16:32 UTC
