### ISSUE TITLE
VirtualBox IP addresses change, making TLS certificates invalid

### ISSUE THREAD

**Issue by bfirsh** [docker/machine#568] opened 2015-02-20 12:27 UTC
```
Sending build context to Docker daemon
FATA[0000] Post https://192.168.99.100:2376/v1.16/build?rm=1&t=docker-compose: x509: certificate is valid for 192.168.99.101, not 192.168.99.100
```

VirtualBox picks IP addresses with DHCP and I think it's given the machine a different address. :(

**Comment by ehazlett** [comment] 2015-02-20 23:21
@bfirsh thx -- this is a duplicate of #531.  Would you mind commenting in #531 how exactly you ran into this issue?  I cannot for the life of me get this re-created (i've changed IPs in the VM etc with no luck).  My suspicion is that the b2d certs are interfering but I cannot confirm.

**Closed by ehazlett** 2015-02-20 23:21 UTC
Labels: bug

**Comment by wisechoice** [comment] 2015-06-04 13:45
I think I have the same problem. Many sites report invalid cert from Windows7 guest. Twitter for example, but then others ok.

**Comment by ehazlett** [comment] 2015-06-04 18:58
@wisechoice what version of machine are you using?  This should be fixed in 0.2.

**Comment by wisechoice** [comment] 2015-06-04 19:38
My apologies @ehazlett. Disregard

**Comment by ehazlett** [comment] 2015-06-05 13:52
@wisechoice thx

**Comment by pyhedgehog** [comment] 2016-09-09 13:54
Workaround: `docker-machine provision`.
