### ISSUE TITLE
Can't generate Centos Docker machine on Digital Ocean DO

### ISSUE THREAD

**Issue by mirkoebert** [docker/machine#3632] opened 2016-08-02 16:21 UTC
The problem is reproducible.
I use following command:
`dm create --driver digitalocean --digitalocean-image centos-7-2-x64 --digitalocean-size 1gb --digitalocean-access-token $DOTOKEN testMeR2
`
The droplet start up. The the docker demon dies on start-up.
```
docker-machine create --driver digitalocean --digitalocean-image centos-7-2-x64 --digitalocean-size 1gb --digitalocean-access-token $DOTOKEN testMeR
Running pre-create checks...
Creating machine...
(testMeR) Creating SSH key...
(testMeR) Creating Digital Ocean droplet...
(testMeR) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with cents...

Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo systemctl -f start docker
err : exit status 6
output : Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.
```
With Ubuntu (default at DO) it works fine. DO Support says, that there is no problem at the DO side.

**Comment by tassels** [comment] 2016-08-02 17:03
I tested this myself using the latest docker/docker-machine software on my mac and got a slightly different error:

`$ docker-machine create --driver digitalocean --digitalocean-image centos-7-2-x64 --digitalocean-size 1gb --digitalocean-access-token $DO_WORK Docker-Machine-Test 
Creating CA: /Users/Eris/.docker/machine/certs/ca.pem 
Creating client certificate: /Users/Eris/.docker/machine/certs/cert.pem 
Running pre-create checks... 
Creating machine... 
(Docker-Machine-Test) Creating SSH key... 
(Docker-Machine-Test) Creating Digital Ocean droplet... 
(Docker-Machine-Test) Waiting for IP address to be assigned to the Droplet... 
Waiting for machine to be running, this may take a few minutes... 
Detecting operating system of created instance... 
Waiting for SSH to be available... 
Detecting the provisioner... 
Provisioning with centos... 
Copying certs to the local machine directory... 
Copying certs to the remote machine... 
Setting Docker configuration on the remote daemon... 
Error creating machine: Error running provisioning: exit status 6`

Not sure of the cause, but it's happening after the Droplet is successfully provisioned on our end.

**Comment by djleeam** [comment] 2016-08-02 17:40
#3624

**Comment by jverhoeven** [comment] 2016-08-03 17:33
I can confirm it has been fixed with #3624. Next official release may be some time off, so if you build docker-machine from current master branch it will work with RHEL 7.2 (I just tested it). I assume the same holds for Centos. Referencing #3636 as well, since that is the same issue.

**Comment by nathanleclaire** [comment] 2016-08-03 21:36
It's been fixed on master if I understand the issue correctly

**Comment by nathanleclaire** [comment] 2016-08-03 21:36
(I am considering an 0.8.1 release for this fix, but might tie it to a Docker 1.12.1 if one comes up in the next few weeks -- it's just easier that way due to also needing to release Toolbox, etc.)

**Closed by nathanleclaire** 2016-08-03 21:36 UTC

**Comment by richardkeit** [comment] 2016-08-04 01:45
@jverhoeven @nathanleclaire - hoping you could spare a few minutes on where I can find a reference on how to build/compile from a commit rather than downloading from the release tags.
Really keen to confirm this on #3636

**Comment by nathanleclaire** [comment] 2016-08-04 23:20
@richardkeit You could `git clone https://github.com/docker/machine; cd machine; USE_CONTAINER=1 make build-x` -- that will spit out cross-compiled binaries into `bin` directory

**Comment by richardkeit** [comment] 2016-08-08 12:00
hi @nathanleclaire - the build failed with 

> go build github.com/docker/machine/vendor/github.com/vmware/govmomi/vim25/types: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed


https://gist.github.com/richardkeit/04ff58aa86df6a45f6cc52c2d3c12bf2 [url](https://gist.github.com/richardkeit/04ff58aa86df6a45f6cc52c2d3c12bf2)

**Comment by jverhoeven** [comment] 2016-08-08 12:43
Hi @richardkeit: In Nathan's instructions 'USE_CONTAINER=true' should be 'export USE_CONTAINER=true'

**Comment by nathanleclaire** [comment] 2016-08-08 22:53
> Hi @richardkeit: In Nathan's instructions 'USE_CONTAINER=true' should be 'export USE_CONTAINER=true'

No, it should be fine with just `USE_CONTAINER=true make build-x`, since that indicates to the `make` process that environment variable `USE_CONTAINER` should be set to `true`.

The error is definitely a bit odd -- are you compiling on a machine with limited resources?  A couple GBs of memory at least is definitely recommended for build

**Comment by richardkeit** [comment] 2016-08-08 23:41
@nathanleclaire , @jverhoeven - just a quick revert - I used a higher spec'ed instance and it completed successfully using:

`USE_CONTAINER=true make build-x`

**Comment by hholst80** [comment] 2016-09-09 20:38
I got the same problem with a `docker-machine` client on Windows 10 and Centos 7:

```
Henrik@zenbook MINGW64 ~
$ docker-machine create --driver generic --generic-ip-address=$SOME_IP_ADDRESS --generic-ssh-user holst hentos
Running pre-create checks...
Creating machine...
(hentos) No SSH key specified. Connecting to this machine now and in the future will require the ssh agent to contain the appropriate key.
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with centos...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: exit status 6

Henrik@zenbook MINGW64 ~
$ docker-machine --version
docker-machine.exe version 0.7.0, build a650a40

Henrik@zenbook MINGW64 ~
$
```

**Comment by nathanleclaire** [comment] 2016-09-12 17:12
@hholst80 That version of Machine does not contain the fix.  Please try 0.8.1.
