### ISSUE TITLE
digitalocean provisioning ubuntu-16-04-x64

### ISSUE THREAD

**Issue by hlobil** [docker/machine#3459] opened 2016-05-27 17:20 UTC
```
docker-machine create \
     --driver digitalocean \
     --digitalocean-image ubuntu-16-04-x64 \
     --digitalocean-size 1gb \
     --digitalocean-ipv6 \
     --digitalocean-private-networking \
     production
```

Running pre-create checks...
Creating machine...
(production) Creating SSH key...
(production) Creating Digital Ocean droplet...
(production) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Error creating machine: Error running provisioning: Something went wrong running an SSH command!
command : sudo apt-get update
err     : exit status 100
output  : Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/

**Comment by nathanleclaire** [comment] 2016-05-31 20:58
Dupe of https://github.com/docker/machine/issues/3358#issuecomment-222292664

**Closed by nathanleclaire** 2016-05-31 20:58 UTC
