### ISSUE TITLE
Creating .docker from scratch results in a permissions error

### ISSUE THREAD

**Issue by moxiegirl** [docker/machine#1595] opened 2015-07-27 19:14 UTC
```
docker-machine create --driver virtualbox docker-vm
Error creating machine config dir: mkdir /Users/mary/.docker/machine/certs: permission denied
```

**Comment by moxiegirl** [comment] 2015-07-27 19:30
On further investigation, it looks like the `~/.docker/machine` directory gets created as being owned by user `root`, which prevents Machine from adding additional sub-directories.  We suspect this might be a Toolbox issue.  cc @jeffdm @ehazlett @nathanleclaire

**Comment by moxiegirl** [comment] 2015-07-27 19:40
@nathanleclaire confirmed.  After installing the Toolbox without running `docker-machine` I have this:

```
$ tree .docker
.docker
└── machine
    └── cache
        └── boot2docker-virtualbox.iso
```

**Comment by timfallmk** [comment] 2015-07-27 22:20
Confirmed. Ownership appears to be `root:root`

**Comment by ehazlett** [comment] 2015-07-29 18:54
Ideally the toolbox should let machine handle the directory creation since it could change in the future, etc. IMO

**Comment by moxiegirl** [comment] 2015-07-29 21:16
@jeffdm do you want to move this to Toolbox?

**Comment by nathanleclaire** [comment] 2015-08-05 23:36
Closing as this is a Toolbox issue.

**Closed by nathanleclaire** 2015-08-05 23:36 UTC

**Comment by ericandrewlewis** [comment] 2015-09-15 19:09
@nathanleclaire can you link to the Toolbox issue? Thanks!
