### ISSUE TITLE
provisioning error on debian 8

### ISSUE THREAD

**Issue by cpuguy83** [docker/machine#1866] opened 2015-09-16 19:54 UTC
Provisioning on debian jessie yields an error, though everything does seem to work just fine.
```
$ docker-machine create -d digitalocean \
  --engine-install-url https://experimental.docker.com \
  --digitalocean-image "debian-8-x64" \
  swarm-demo-1
Creating SSH key...
Creating Digital Ocean droplet...
SSH cmd error!
command: sudo systemctl enable docker
err    : exit status 1
output : Synchronizing state for docker.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d docker defaults
Executing /usr/sbin/update-rc.d docker enable
Failed to execute operation: File exists
```

**Comment by nathanleclaire** [comment] 2015-09-16 23:05
cc @ehazlett

**Comment by ehazlett** [comment] 2015-09-17 17:27
Duplicate of #1705.  We will get this fixed for 0.5

**Closed by ehazlett** 2015-09-17 17:27 UTC
