### ISSUE TITLE
17.06.0-ce Ubuntu 16.04 install: "Failed to start Docker Application Container Engine"

### ISSUE THREAD

**Issue by corbathegeek** [docker/machine#4177] opened 2017-07-05 22:33 UTC
```bash
corba@myubuntu:~$ sudo apt install docker-ce 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker-ce
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 0 B/20.5 MB of archives.
After this operation, 96.2 MB of additional disk space will be used.
Selecting previously unselected package docker-ce.
(Reading database ... 339943 files and directories currently installed.)
Preparing to unpack .../docker-ce_17.06.0~ce-0~ubuntu_amd64.deb ...
Unpacking docker-ce (17.06.0~ce-0~ubuntu) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up docker-ce (17.06.0~ce-0~ubuntu) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─debian-style-config.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-07-05 15:27:09 PDT; 48ms ago
     Docs: https://docs.docker.com
  Process: 11884 ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 11884 (code=exited, status=1/FAILURE)

Jul 05 15:27:09 L4692197 systemd[1]: Failed to start Docker Application Container Engine.
Jul 05 15:27:09 L4692197 systemd[1]: docker.service: Unit entered failed state.
Jul 05 15:27:09 L4692197 systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu17) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
corba@myubuntu:~$ 
```

from journalctl -xe:

```
Jul 05 15:27:10 L4692197 docker[11980]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Jul 05 15:27:10 L4692197 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 15:27:10 L4692197 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Jul 05 15:27:10 L4692197 systemd[1]: docker.service: Unit entered failed state.
Jul 05 15:27:10 L4692197 systemd[1]: docker.service: Failed with result 'exit-code'.
Jul 05 15:27:11 L4692197 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jul 05 15:27:11 L4692197 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Jul 05 15:27:11 L4692197 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Jul 05 15:27:11 L4692197 systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun shutting down.
Jul 05 15:27:11 L4692197 systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Jul 05 15:27:11 L4692197 systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Jul 05 15:27:11 L4692197 systemd[1]: docker.service: Start request repeated too quickly.
Jul 05 15:27:11 L4692197 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Jul 05 15:27:11 L4692197 systemd[1]: docker.socket: Unit entered failed state.
Jul 05 15:27:13 L4692197 sudo[10200]: pam_unix(sudo:session): session closed for user root
Jul 05 15:28:03 L4692197 pkexec[12241]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Jul 05 15:28:03 L4692197 pkexec[12241]: pam_systemd(polkit-1:session): Cannot create session: Already running in a session
Jul 05 15:28:03 L4692197 pkexec[12241]: peterc: Executing command [USER=root] [TTY=unknown] [CWD=/home/peterc] [COMMAND=/us
Jul 05 15:30:01 L4692197 CRON[12698]: pam_unix(cron:session): session opened for user root by (uid=0)
Jul 05 15:30:01 L4692197 CRON[12699]: (root) CMD (. /home/peterc/.bashrc && cronic /home/peterc/bin/checkAvahiDaemonCpu.sh)
Jul 05 15:30:01 L4692197 CRON[12698]: pam_unix(cron:session): session closed for user root
Jul 05 15:30:43 L4692197 pulseaudio[5147]: [pulseaudio] shm.c: shm_open() failed: No such file or directory
Jul 05 15:30:43 L4692197 pulseaudio[5147]: [pulseaudio] shm.c: shm_open() failed: No such file or directory
lines 2737-2800/2800 (END)
```

**Comment by systemmonkey42** [comment] 2017-07-07 01:32
This is a duplicate of #4156 

Please update to docker machine 0.12.1 or later.

**Closed** 2017-07-07 19:20 UTC

**Comment by liaozd** [comment] 2017-08-04 03:31
update to docker machine 0.12.1 doesn't work for me. 
(4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by AntonBikineev** [comment] 2017-08-24 10:57
didn't help either..

**Comment by vuongggggg** [comment] 2017-08-27 04:34
I've got the same problem when I setup droplet in DigitalOcean. 
```
Aug 27 04:29:09 docker-app-machine systemd[1]: Failed to start Docker Application Container Engine.
Aug 27 04:29:09 docker-app-machine systemd[1]: docker.service: Unit entered failed state.
Aug 27 04:29:09 docker-app-machine systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 27 04:29:10 docker-app-machine systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 27 04:29:10 docker-app-machine systemd[1]: Stopped Docker Application Container Engine.
Aug 27 04:29:10 docker-app-machine systemd[1]: docker.service: Start request repeated too quickly.
Aug 27 04:29:10 docker-app-machine systemd[1]: Failed to start Docker Application Container Engine.
Aug 27 04:29:15 docker-app-machine systemd[1]: Stopped Docker Application Container Engine.
Aug 27 04:29:15 docker-app-machine systemd[1]: docker.service: Start request repeated too quickly.
Aug 27 04:29:15 docker-app-machine systemd[1]: Failed to start Docker Application Container Engine.
```
May be this article will help you all: https://forums.docker.com/t/failed-to-start-docker-application-container-engine/35594/2

**Comment by michaelkrog** [comment] 2017-10-05 09:45
I have the same issue with one node on Ubuntu 16.04 with 17.09 on a test cluster.

The nodes in the swarm have been unable to reach each other for a few days and now the master shut down and is not able to start again. A reinstall of docker-ce does not help.

**Comment by bcatalin** [comment] 2017-10-25 18:12
same problem here

**Comment by D0048** [comment] 2017-11-16 01:21
Same here.

**Comment by mifurm** [comment] 2017-11-16 19:34
Same story in here. All the upgrades done. :(

**Comment by Vaitt-Joy** [comment] 2017-12-12 03:24
the same today i try stop the docker ,then i try to start ,so the error...

**Comment by jiapei100** [comment] 2017-12-16 10:00
same here with a different kernel:
4.14.5-041405-generic

**Comment by muguang** [comment] 2017-12-19 07:40
same here

**Comment by liberjiang** [comment] 2018-11-07 09:29
same here
