### ISSUE TITLE
machine url panics 

### ISSUE THREAD

**Issue by cjellick** [docker/machine#256] opened 2015-01-09 20:53 UTC
### Description of problem:
If no machine is active, ```machine url``` panics

### Machine version:
Running latest of master of machine

### Environment details:
Running machine on Mac OSX Yosemite

### How reproducible:
Very

### Steps to Reproduce:
1. Get into a state where you have no active machine. Easiest is to just not create a machine. But I think deleting the active machine should also do the trick.
2. Run ```machine url``` with no machine/host specified

### Actual Results:
machine panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xe90c2]

goroutine 1 [running]:
github.com/docker/machine/hosts.(*Host).GetURL(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/cjellick/go/src/github.com/docker/machine/hosts/host.go:249 +0x92
main.cmdUrl(0xc20809c180)
	/Users/cjellick/go/src/github.com/docker/machine/commands.go:377 +0x41
github.com/codegangsta/cli.Command.Run(0x699510, 0x3, 0x0, 0x0, 0x7017b0, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cjellick/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xe42
github.com/codegangsta/cli.(*App).Run(0xc20809c000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/Users/cjellick/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:130 +0xb81
main.main()
	/Users/cjellick/go/src/github.com/docker/machine/main.go:36 +0x3ea

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc208068100, 0x7c2580)
	/usr/local/Cellar/go/1.4/libexec/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208068100)
	/usr/local/Cellar/go/1.4/libexec/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/Cellar/go/1.4/libexec/src/text/template/parse/lex.go:191 +0x1ac
~/go/src/github.com/docker/machine$ mvim main.go
~/go/src/github.com/docker/machine$ mvim /usr/local/Cellar/go/1.4/libexec/src/text/template/parse/lex.go
```

### Expected Results:
Graceful failure and meaningful user-friendly error message.

**Comment by sthulb** [comment] 2015-01-09 22:04
This happens on all commands actually...

**Comment by nathanleclaire** [comment] 2015-01-10 00:41
Indeed.  Dupe of #222 I think.

**Comment by sthulb** [comment] 2015-01-11 12:34
@cjellick Is this something you're working on?

**Comment by cjellick** [comment] 2015-01-12 13:07
@sthulb I started working on it on Friday, but got into a bit of yak shaving.

**Comment by sthulb** [comment] 2015-01-12 14:03
@cjellick OK... I think I narrowed it down to a problem with the first return in `GetActive` from the store. It just returns `nil, nil`

**Comment by cjellick** [comment] 2015-01-12 14:38
@sthulb your PR (#262) cover it then? I'd be duplicating effort if I pursued a fix further at this point, right?

**Comment by sthulb** [comment] 2015-01-12 14:53
@cjellick It should cover it.

**Comment by ehazlett** [comment] 2015-01-20 21:52
Closing as #262 is merged.

**Closed by ehazlett** 2015-01-20 21:52 UTC
