### ISSUE TITLE
Start some ec2 machine in parallel, log some api errors....

### ISSUE THREAD

**Issue by rossbachp** [docker/machine#796] opened 2015-03-17 07:17 UTC
If I create some ec2 swarm machine in parallel:

```
export NUM_WORKER=3
for i in $(seq $NUM_WORKER) ; do
>     docker-machine create --driver amazonec2 \
>       --amazonec2-access-key=${AWS_access_key} \
>       --amazonec2-ami=ami-898dd9b9 \
>       --amazonec2-instance-type=t2.micro \
>       --amazonec2-region=us-west-2 \
>       --amazonec2-root-size=16 \
>       --amazonec2-secret-key=${AWS_secret_key} \
>       --amazonec2-vpc-id=vpc-2748f942 \
>       --amazonec2-zone=a \
>       --swarm \
>       --swarm-discovery=token://$SWARM_TOKEN \
>       ec2-swarm-0$i &
>   done
[1] 31680
[2] 31681
[3] 31682

```

it's log some failures....

```
$ docker-machine ls
ERRO[0000] error getting state for host ec2-swarm-01: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
ERRO[0000] error getting state for host ec2-swarm-02: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
ERRO[0000] error getting state for host ec2-swarm-03: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
ERRO[0001] error getting URL for host ec2-swarm-01: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
INFO[0023] Waiting for SSH on 54.69.29.90:22            
INFO[0023] Waiting for SSH on 54.69.230.35:22           
ERRO[0001] error getting URL for host ec2-swarm-02: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
ERRO[0001] error getting URL for host ec2-swarm-03: Problem with AWS API call: Non-200 API response: code=400 message=The request must contain the parameter InstanceId
 
INFO[0023] Waiting for SSH on 54.69.255.39:22           
NAME               ACTIVE   DRIVER       STATE     URL                       SWARM
amazonec2-03                amazonec2    Running   tcp://52.11.94.202:2376   
dev                         virtualbox   Stopped                             
ec2-swarm-01                amazonec2    Error                               ec2-swarm-master
ec2-swarm-02                amazonec2    Error                               ec2-swarm-master
ec2-swarm-03                amazonec2    Error                               ec2-swarm-master
ec2-swarm-master   *        amazonec2    Running   tcp://52.10.167.59:2376   ec2-swarm-master (master)
$ INFO[0175] Configuring Swarm...                         
INFO[0184] "ec2-swarm-01" has been created and is now the active machine. 
INFO[0184] To point your Docker client at it, run this in your shell: $(docker-machine env ec2-swarm-01) 
INFO[0187] Configuring Swarm...                         
INFO[0189] Configuring Swarm...                         
INFO[0195] "ec2-swarm-02" has been created and is now the active machine. 
INFO[0195] To point your Docker client at it, run this in your shell: $(docker-machine env ec2-swarm-02) 
INFO[0198] "ec2-swarm-03" has been created and is now the active machine. 
INFO[0198] To point your Docker client at it, run this in your shell: $(docker-machine env ec2-swarm-03) 
```

but after 3 minutes all machines are created...

```
$ docker-machine ls
NAME               ACTIVE   DRIVER       STATE     URL                       SWARM
amazonec2-03                amazonec2    Running   tcp://52.11.94.202:2376   
dev                         virtualbox   Stopped                             
ec2-swarm-01                amazonec2    Running   tcp://54.69.255.39:2376   ec2-swarm-master
ec2-swarm-02                amazonec2    Running   tcp://54.69.29.90:2376    ec2-swarm-master
ec2-swarm-03       *        amazonec2    Running   tcp://54.69.230.35:2376   ec2-swarm-master
ec2-swarm-master            amazonec2    Running   tcp://52.10.167.59:2376   ec2-swarm-master (master)
[1]   Done                    docker-machine create --driver amazonec2 --amazonec2-access-key=${AWS_access_key} --amazonec2-ami=ami-898dd9b9 --amazonec2-instance-type=t2.micro --amazonec2-region=us-west-2 --amazonec2-root-size=16 --amazonec2-secret-key=${AWS_secret_key} --amazonec2-vpc-id=vpc-2748f942 --amazonec2-zone=a --swarm --swarm-discovery=token://$SWARM_TOKEN ec2-swarm-0$i
[2]-  Done                    docker-machine create --driver amazonec2 --amazonec2-access-key=${AWS_access_key} --amazonec2-ami=ami-898dd9b9 --amazonec2-instance-type=t2.micro --amazonec2-region=us-west-2 --amazonec2-root-size=16 --amazonec2-secret-key=${AWS_secret_key} --amazonec2-vpc-id=vpc-2748f942 --amazonec2-zone=a --swarm --swarm-discovery=token://$SWARM_TOKEN ec2-swarm-0$i
[3]+  Done                    docker-machine create --driver amazonec2 --amazonec2-access-key=${AWS_access_key} --amazonec2-ami=ami-898dd9b9 --amazonec2-instance-type=t2.micro --amazonec2-region=us-west-2 --amazonec2-root-size=16 --amazonec2-secret-key=${AWS_secret_key} --amazonec2-vpc-id=vpc-2748f942 --amazonec2-zone=a --swarm --swarm-discovery=token://$SWARM_TOKEN ec2-swarm-0$i
```

```
$ $(docker-machine env --swarm ec2-swarm-master)
$ docker info
Containers: 5
Nodes: 4
 ec2-swarm-master: 52.10.167.59:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 992.4 MiB
 ec2-swarm-03: 54.69.230.35:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 992.4 MiB
 ec2-swarm-01: 54.69.255.39:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 992.4 MiB
 ec2-swarm-02: 54.69.29.90:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 992.4 MiB
```

**Comment by igoratencompass** [comment] 2015-06-11 08:54
Same here except I'm running the commands manually:

$ docker-machine create --driver amazonec2 --swarm --swarm-discovery token://$TOKEN --amazonec2-region "eu-west-1" --amazonec2-root-size "8" --amazonec2-vpc-id vpc-xxxxxxxx --amazonec2-zone "b" swarm-node-21
INFO[0002] Launching instance...                        
INFO[0026] Waiting for SSH on 52.17.161.105:22

which never finishes and just sits there stuck. I can see the instances have been created and running in EC2 console but they don't get any name assigned for some reason. And this only happens if I launch a swarm node in different zone from the one the master is in. Is this maybe not supported?

**Comment by ehazlett** [comment] 2015-06-11 14:19
@rossbachp that looks like the AWS api responding with issues.  I wonder if it was trying to throttle the requests or something?  Could you try it without parallel to see if you have the same issues?

@igoratencompass this sounds like perhaps a security group issue.  machine will create the group (with appropriate permissions) if it doesn't exist.  Otherwise, it uses the existing group.

**Comment by igoratencompass** [comment] 2015-06-13 08:26
Well the security group docker-machine has been created with tcp ports 22, 2376 and 3376 opened to the world. Anything missing?

**Comment by igoratencompass** [comment] 2015-06-13 08:29
AND it has been assigned to the 2 instances that failed too.

**Comment by ehazlett** [comment] 2015-06-16 13:17
@igoratencompass hmm that looks ok.  could you try another region perhaps?

**Comment by igoratencompass** [comment] 2015-07-03 05:19
Thought I would leave a feedback on this one. I found the problem, it was the subnet in the second zone of the eu-west-1 that was left without NAT Internet gateway. So nothing to do with docker-machine. The swarm cluster was successfully created in other regions.

**Comment by nathanleclaire** [comment] 2015-07-06 19:13
This issue has split into several different directions without very coherent steps to reproduce a specific issue, so please re-open if you can narrow the focus down a little bit.  Thanks!

**Closed by nathanleclaire** 2015-07-06 19:13 UTC
