### ISSUE TITLE
Unable to work with Virtualbox 5

### ISSUE THREAD

**Issue by zeleznypa** [docker/machine#1498] opened 2015-07-10 06:38 UTC
Today the Oracle announce, that new version of [Virtualbox](https://www.virtualbox.org) is released. Unfortunately this version is incompatible with docker-machine. Previously builded virtualbox instance won't start by `docker-machine run dev` and exit with code 1. Same when creating new instance

```bash
$ docker-machine create -d virtualbox dev
Creating VirtualBox VM...
Creating SSH key...
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by gkze** [comment] 2015-07-10 16:38
:+1: bump, running into this as well

**Comment by nathanleclaire** [comment] 2015-07-10 17:50
A fix for this has been submitted at https://github.com/docker/machine/pull/1496

**Comment by andrewshawcare** [comment] 2015-07-10 22:48
For anyone who comes across this issue and wants docker-machine up again before the issue is resolved (and are using brew cask to manage VirtualBox):

1. `brew cask uninstall virtualbox`
2. `brew cask install virtualbox43691406`

**Comment by kudos** [comment] 2015-07-15 23:03
@andrewshawcare you also need to `brew tap caskroom/versions` to get older Virtualbox versions.

**Comment by doxxx** [comment] 2015-07-16 12:11
This is working for me with Kitematic 0.7.5 that contains docker-machine 0.3.1-rc1.

**Comment by Endron** [comment] 2015-07-20 13:08
Another workaround would be using boot2docker.
Works for me on Mac OS X

**Comment by pnovotnak** [comment] 2015-07-23 23:31
Bump. As stated by @andrewshawcare @kudos, installing an older version of VirtualBox did the trick.

**Comment by nathanleclaire** [comment] 2015-07-23 23:32
Hi all, please try Docker Machine latest (currently 0.3.1) and re-open if you have any issues.  This should be fixed.  Thanks!

**Closed by nathanleclaire** 2015-07-23 23:32 UTC

**Comment by Endron** [comment] 2015-07-24 08:17
Works for me.

:+1:  thank you guys!

**Comment by nathanleclaire** [comment] 2015-07-24 18:34
Thanks @Endron <3

**Comment by oblalex** [comment] 2015-08-02 12:09
`virtualbox43691406 ` just crashed my mac. Used `4.3.30 r101610` and seems like it's working.

**Comment by suchkultur** [comment] 2015-08-16 20:00
Same error message using `docker-machine version 0.4.1 (e2c88d6)` and Virtualbox `5.0.2`. This occurs after installing docker using the new docker toolbox package on current MacOSX.

**Comment by anentropic** [comment] 2015-08-17 17:51
uninstalling VirtualBox (5.0.2), rebooting and reinstalling VirtualBox fixed it for me

**Comment by bradparks** [comment] 2015-08-25 13:00
This problem is still happening with Docker 1.8.1.b (DockerToolbox-1.8.1b.pkg) downloaded today (Aug 25) with VirtualBox 5.0.2 (VirtualBox-5.0.2-102096-OSX) on OSX 10.10.4.

So for anyone new to Docker (like myself) who tries to get Docker running, it may be failing and not giving them a nice error message. The only way I found this out was by googling!
