### ISSUE TITLE
virtualbox: Hangs on Waiting for VM to start

### ISSUE THREAD

**Issue by dave-tucker** [docker/machine#986] opened 2015-04-09 17:39 UTC
Tried starting a VM via `docker-machine start` and it hung on:
````
INFO[0000] Waiting for VM to start...
````
Check the VirtualBox GUI and the VM state was `aborted`.
The underlying cause here was that my VM image was corrupted, but as a user I'd expect machine to be aware of this and provide an appropriate error message.

**Comment by ehazlett** [comment] 2015-04-10 13:11
Hmm I haven't seen that before -- thanks for reporting.  How were you able to tell it was corrupted?

**Comment by dave-tucker** [comment] 2015-04-10 16:42
I was guessing at "corrupted". On manual start of the VM from the virtualbox GUI it got mid-way through the boot process and then the state changed to "aborted". A little digging suggests it could be related to a [bug in virtualbox](https://www.virtualbox.org/ticket/13874)....

Still, it would be great for machine to notify the user about these type of errors when they occur.

**Comment by ms-clovis** [comment] 2015-04-11 16:20
This happens in with boot2docker image also. If you stop the vm for the image and choose stop (instead of option sending signal to stop, it will show aborted and probably not restart from virtual machine or boot2docker cli. Recommended fix (and it worked for me) is simply rebooting windows or whatever os you are running boot2docker on. Hope this helps.

**Comment by sshaw** [comment] 2015-04-26 14:14
Same problem after installing from `https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64`:

```
~ >docker-machine create --driver virtualbox dev
INFO[0000] Creating CA: /Users/sshaw/.docker/machine/certs/ca.pem
INFO[0000] Creating client certificate: /Users/sshaw/.docker/machine/certs/cert.pem
INFO[0001] Creating SSH key...
INFO[0001] Image cache does not exist, creating it at /Users/sshaw/.docker/machine/cache...
INFO[0001] No default boot2docker iso found locally, downloading the latest release...
INFO[0001] Downloading latest boot2docker release to /Users/sshaw/.docker/machine/cache/boot2docker.iso...
INFO[0024] Creating VirtualBox VM...
INFO[0034] Starting VirtualBox VM...
INFO[0035] Waiting for VM to start...
```

`VBoxHeadless` is running. 

In my case opening VirtualBox shows the `dev` image as *Running* and the docker ASCII art + command prompt in the Preview section.

* OS X 10.9.5
* docker-machine 0.2.0
* VirtualBox 4.3.25 r98716

**Comment by sshaw** [comment] 2015-04-26 14:25
Also note that the [aforementioned bug](https://www.virtualbox.org/ticket/13874) was supposed to be fixed in `4.3.24` but I was running `4.3.25`. Tried with `4.3.26` too, same problem.

**Comment by DavideDelVecchio** [comment] 2015-04-26 21:05
Same thing here I'm on 
* OS X 10.9.5
* VirtualBox v4.3.26-r98988
* docker-machine 0.2.0 
when running 

docker-machine create  --driver virtualbox mymachine

it hangs

**Comment by ehazlett** [comment] 2015-04-27 21:33
@sshaw @DavideDelVecchio can you post the output of both `VBoxManager list hostonlyifs` and `netstat -nr`?

**Comment by sshaw** [comment] 2015-04-28 04:23
```
~ >VBoxManage list hostonlyifs
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0
```
```
~ >netstat -nr
Routing tables
Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           25        1     en0
127                127.0.0.1          UCS             0      126     lo0
127.0.0.1          127.0.0.1          UH              2  1772668     lo0
127.94.0.1         127.94.0.1         UH              0        0     lo0
127.94.0.2         127.94.0.2         UH              0        0     lo0
192.168.1          link#4             UCS             1        0     en0
...
192.168.1.130      127.0.0.1          UHS             0       88     lo0
192.168.99         link#9             UC              1        0 vboxnet
```


Note that deleting the route and replacing it with:

```
route add -net  192.168.99 -interface vboxnet0
```

still results in a route to the interface `vboxnet`.

Maybe this is the problem?

**Comment by pugnascotia** [comment] 2015-04-28 08:51
I saw the same behaviour last night - I installed the latest VirtualBox from the official website, installed docker and docker-machine via brew, and it hung on "Waiting for VM to start". I didn't get a chance to try rebooting the machine.

**Comment by DavideDelVecchio** [comment] 2015-04-28 09:39
I finally got it work this way 
I have previously installed Kitematic that hanged upon startup 
installed then docker-machine via brew and had "Waiting for VM to start"
then removed all the VMs and installed docker-machine this way
curl -L https://github.com/docker/machine/releases/download/v0.2.0/docker-machine_darwin-amd64  > /usr/local/bin/docker-machine
chmod +x  /usr/local/bin/docker-machine
docker-machine create --driver virtualbox mymachine
I have all my route on interface on vboxnet as well

**Comment by ehazlett** [comment] 2015-04-29 13:16
@sshaw thanks for the feedback. if the route (as shown in the table) is using `vboxnet` and not the `vboxnet0` interface, this looks like the issue.  i was able to reproduce this behavior by manually removing my routing entries.  i'm not sure why this would be messed with -- are you using any VPN software by chance?  @pugnascotia are you using vpn?

**Comment by pugnascotia** [comment] 2015-04-29 13:23
Nope, no VPN for me. I'll try to dig into this more.

**Comment by sshaw** [comment] 2015-04-29 13:42
@ehazlett yes, seems so but when I delete the route do:

```
route add -net  192.168.99 -interface vboxnet0
```

The route gets added as `vboxnet`. Does this happen for you?

**Comment by ehazlett** [comment] 2015-04-29 15:01
@sshaw the way i was to fix was to delete the route and then `ifconfig vboxnet0 down` and `ifconfig vboxnet0 up`.  the route was back up and i was able to connect.

**Comment by ehazlett** [comment] 2015-04-29 16:06
@sshaw ok this is a difference between OS X and Linux -- on Linux it shows as the exact name but on OS X i see it as `vboxnet`.

**Comment by sshaw** [comment] 2015-04-29 16:22
Ah yes, I thought you were testing on OS X too...

**Comment by mattes** [comment] 2015-05-04 17:54
+1

**Comment by robtec** [comment] 2015-05-05 20:34
@sshaw can confirm deleting `vboxnet` then adding the `vboxnet0` results in `vboxnet` present, again

**Comment by robtec** [comment] 2015-05-05 20:48
So before I added a VM via boot2docker
```
Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.0.1        UGSc           72        1     en1
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH            256    17176     lo0
169.254            link#5             UCS             0        0     en1
192.168.0          link#5             UCS             1        0     en1
192.168.0.1/32     link#5             UCS             1        0     en1
192.168.0.1        c4:27:95:b5:13:9   UHLWIir        74       24     en1   1141
192.168.0.15/32    link#5             UCS             0        0     en1
192.168.0.255      ff:ff:ff:ff:ff:ff  UHLWbI          0        1     en1
192.168.99  
```
and after...

```
Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.0.1        UGSc           34        7     en1
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              3    21645     lo0
169.254            link#5             UCS             0        0     en1
192.168.0          link#5             UCS             0        0     en1
192.168.0.1/32     link#5             UCS             1        0     en1
192.168.0.1        c4:27:95:b5:13:9   UHLWIir        36       24     en1    383
192.168.0.15/32    link#5             UCS             0        0     en1
192.168.59         link#11            UC              1        0 vboxnet
192.168.59.103     8:0:27:bc:84:0     UHLWIi          1       19 vboxnet   1196
192.168.99         link#10            UCSc            1        0 vboxnet
```

The new `192.168.59.103` entry looks different to the `192.168.99`

Hope this helps :+1:

**Comment by robcowie** [comment] 2015-05-12 16:03
Does anyone have a definitive explanation or solution to this? It's become an issue for me and I know so little about virtualbox and docker that I an unable proceed.

**Comment by ehazlett** [comment] 2015-05-13 14:06
@robcowie unfortunately we are still investigating.  it appears to be how virtualbox is handling multiple host only interfaces.  i've been able to debug where virtualbox will not give out an IP address via its built in DHCP when there are multiple host only interfaces.  i would try removing all of the the host only interfaces and then re-run machine.

**Comment by ljrittle** [comment] 2015-05-13 18:03
FWIW, I tried this: " i would try removing all of the the host only
interfaces and then re-run machine." with machine-0.2 and vbox 4.3.26 on an
OS X machine without luck.

@robcowie <https://github.com/robcowie> unfortunately we are still
> investigating. it appears to be how virtualbox is handling multiple host
> only interfaces. i've been able to debug where virtualbox will not give out
> an IP address via its built in DHCP when there are multiple host only
> interfaces. i would try removing all of the the host only interfaces and
> then re-run machine.
>

**Comment by craigbrad** [comment] 2015-05-15 21:49
+1

**Comment by nagendersoma** [comment] 2015-05-16 20:51
I just tried docker-machine for the first time (OSX, virtualbox) and hit this issue.  Running following cmds resolved the issue. 
ifconfig vboxnet0 down
ifconfig vboxnet0 up

One observation : when I use vagrant to configure new VMs, it uses adapter-2 host-only interface  with adpater-type Intel PRO/1000MT.   The vm creation goes smooth.
With docker-machines, I see host-only adapter-type is set to paravirtualized-virtio.   
Is this difference potentially causing any issues ?

**Comment by sflxn** [comment] 2015-05-18 02:27
Just wanted to leave my experience with this issue.  I was having this problem on my Macbook Air but not on my Macbook Pro.  I assume it is some software configuration.  Anyway, I pulled the latest code on my Macbook Air and built it.  I had no problems with the latest code.  I have not compared the difference between the code.  Btw, when I pulled the latest code, I had to delete the Azure and DigitialOcean drivers  before I could build it.

**Comment by ehazlett** [comment] 2015-05-18 13:36
@nagendersoma thanks for the feedback!

we've narrowed it down to the hostonlyif and the VirtualBox dhcp service.

@craigbrad @robcowie @pugnascotia could you try changing your interface type to `Intel PRO/1000MT` and see if that works any better?

**Comment by adamrothman** [comment] 2015-05-18 19:13
@ehazlett I've tried setting Adapter 2 to Intel PRO/1000 MT (both Desktop and Server) with no luck. `docker-machine start docker-vm` hangs on `Waiting for VM to start...` as before.

For what it's worth, this only happens on my Mac mini. I haven't had any trouble creating VMs on my MacBook Pro.

**Comment by adamrothman** [comment] 2015-05-18 19:48
Confirmed that completely uninstalling VirtualBox 4.3.28 (using the .tool in the DMG) and installing VirtualBox 4.3.26 fixes the issue. Weird.

**Comment by adamrothman** [comment] 2015-05-18 20:03
Just kidding. Downgrading to VirtualBox 4.3.26 only fixed the issue on my MacBook Pro. Still not working on my Mac mini.

**Comment by adamrothman** [comment] 2015-05-18 20:24
Building the latest `docker-machine` from source, restarting the Mac mini, and re-creating the image worked.

**Comment by craigbrad** [comment] 2015-05-18 21:24
@ehazlett I had no luck with that, however I did manage to get it working eventually by removing all of my host only interfaces and routes then creating a new machine. It seemed to take a while to connect though.

**Comment by ehazlett** [comment] 2015-05-19 14:40
@adamrothman this would make sense -- we've been able to narrow the issue to the vbox dhcp server   which would make sense.

**Comment by efrecon** [comment] 2015-05-20 09:25
I also have started to run into this issue. It's intermittent, running in debug mode seems to help sometimes (but nothing 100%). Is there any way to circumvent the issue, restarting the VirtualBox DHCP server or similar? I am trying to automate this from [machinery](https://github.com/efrecon/machinery) and would prefer squeezing that bug away before the next release.

**Comment by efrecon** [comment] 2015-05-20 12:45
For what it is worth, I thought that I would mention some of the steps that I have taken while trying to sort this out. It turned out that I had both an old virtual box DHCP server running and an old `vboxnetX` interface lying around (probably in part because I have run `vagrant` on the same machine).  Getting rid of those seems to help a little bit.

To get the list of running DHCP servers, you can run:

    VBoxManage list dhcpservers

And you can remove them through issuing (adapt to the proper `vboxnetX` interfaces) and repeat as many times as necessary.

    VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0

In the process, I also removed the old interfaces using (adapt again):

    VBoxManage remove --netname HostInterfaceNetworking-vboxnet0

**Comment by codecakes** [comment] 2015-05-20 13:37
i removed the dhcpserver as directed above and then added the following:

```
VBoxManage list dhcpservers

NetworkName:    intnet0
IP:             192.168.66.1
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.66.2
upperIPAddress: 192.168.66.255
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.99.1
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.2
upperIPAddress: 192.168.99.255
Enabled:        Yes
```

Haven't restarted the machine though.
and its stuck at 

```
INFO[0000] Creating SSH key...
INFO[0000] Creating VirtualBox VM...
INFO[0015] Starting VirtualBox VM...
INFO[0016] Waiting for VM to start...
```

Does rebooting help anyone?

**Comment by efrecon** [comment] 2015-05-20 14:00
Sometimes...

**Comment by ehazlett** [comment] 2015-05-20 15:39
@efrecon could you try this build and see if it's any better? https://public.evanhazlett.com/docker-machine/vbox-intel-nic/

**Comment by philm** [comment] 2015-05-20 17:10
@ehazlett - your build worked for me (with Virtualbox 4.3.28 and OS X 10.10.4).

**Comment by dueyfinster** [comment] 2015-05-20 17:47
@ehazlett  your build worked for me - VirtualBox 4.3.28 / Mac OS X 10.10.3

**Comment by efrecon** [comment] 2015-05-20 22:33
@ehazlett, I was able to create a dozen of virtual machines without a glitch with your build ([machinery](https://github.com/efrecon/machinery) makes this kind of testing easy!). I am on Ubuntu and running VirtualBox 4.3.28 also. I have another machine that have had similar problems in the past, I'll try on that one tomorrow.

Note however that the ssh port to get into the machine is `22` with your build, but is reported as something else by `docker-machine inspect`. I guess that you know, but I thought that I would mention it just in case.

What is the estimated time frame for the release of 0.3?

**Comment by adamrothman** [comment] 2015-05-20 22:56
@ehazlett I just did a fresh install of VirtualBox 4.3.28 and downloaded your build. Got this:

```
$ docker-machine create --driver virtualbox docker-vm
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
Error creating machine: No IP address found 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:a4:ca:bc brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fea4:cabc/64 scope link 
       valid_lft forever preferred_lft forever

You will want to check the provider to make sure the machine and associated resources were properly removed.
```

I am going to try restarting.

**Comment by adamrothman** [comment] 2015-05-20 23:41
My routing tables got all messed up as a result of these shenanigans so I deleted the bad entries, re-added them, and everything is working with VirtualBox 4.3.26 so I'm going to leave it alone.

**Comment by eyakcn** [comment] 2015-05-21 02:47
I think it's because there exist boot2docker-vm, after I remove all the virtual machines, then everything works

**Comment by efrecon** [comment] 2015-05-21 10:00
@ehazlett, your build is also working on the other host that I had problems on. It is running a lower build number of VirtualBox 4.3.28, still on Ubuntu LTS.

**Comment by codecakes** [comment] 2015-05-21 13:04
@ehazlett 's build works for me on Ubuntu v 14.04 LTS 64 bit

**Comment by Chukwunonso** [comment] 2015-05-21 15:26
@ehazlett just confirm that your build works for me.

**Comment by CyrilPeponnet** [comment] 2015-05-21 22:47
I also confirm that the binary from https://public.evanhazlett.com/docker-machine/vbox-intel-nic/docker-machine_darwin-amd64 fixes the issue with vBox 4.3.26 under OSX 10.10.3 (even if I managed to create the first vm with the release binary).

**Comment by ehazlett** [comment] 2015-05-22 14:29
Thanks for the feedback all!  I'll get that fixed merged!

**Comment by ehazlett** [comment] 2015-05-22 14:36
FYI issued #1218 to get that fix merged.

**Comment by pugnascotia** [comment] 2015-05-22 14:47
Cool - I've been moving house so I didn't get a chance to try the fix.
Great work!

On 22 May 2015 at 15:36, Evan Hazlett <notifications@github.com> wrote:

> FYI issued #1218 <https://github.com/docker/machine/pull/1218> to get
> that fix merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/machine/issues/986#issuecomment-104675868>.
>



-- 
Rory Hunter

**Comment by ehazlett** [comment] 2015-05-22 15:02
@pugnascotia thx!

**Comment by rafabene** [comment] 2015-05-22 16:24
When this fix will be released ?

**Comment by marioidival** [comment] 2015-05-25 13:45
When this fix will be released ?

**Closed** 2015-05-26 15:04 UTC
Labels: driver:virtualbox

**Comment by paulm-jones** [comment] 2015-05-26 21:58
@ehazlett your build works for me too

**Comment by ehazlett** [comment] 2015-05-27 14:40
@paulm-jones thanks for the feedback!

**Comment by mrjcleaver** [comment] 2015-05-27 14:46
@ehazlett - sorry, (and until the release comes out,) how do I install your build?

I'm on OS X.

**Comment by ehazlett** [comment] 2015-05-27 15:46
@mrjcleaver you can grab the latest master build from https://docker-machine-builds.evanhazlett.com/latest/ and place somewhere on your `PATH`.  You will also need to make it executable (`chmod +x`).  Thanks!

**Comment by marioidival** [comment] 2015-05-27 18:09
@ehazlett Working to me :+1: 
Thanks!

**Comment by marioidival** [comment] 2015-05-27 18:11
![captura de tela 2015-05-27 as 15 10 17](https://cloud.githubusercontent.com/assets/1129263/7843803/98279376-0482-11e5-8164-66ea81571835.png)

**Comment by ianlintner-wf** [comment] 2015-10-13 15:33
I have been having to use the --native-ssh flag with everything, but it works. (Debug is just there for testing)
e.g. 
docker-machine -D --native-ssh create --driver=virtualbox default
docker-machine -D --native-ssh=true ssh default
docker-machine -D --native-ssh=true env default

**Comment by slank** [comment] 2015-10-16 18:59
+1 @ianlintner-wf 

@ehazlett's build doesn't fix the problem for me, but --native-ssh=true does.

**Comment by nathanleclaire** [comment] 2015-10-16 20:35
@ianlintner-wf FYI, setting the `MACHINE_NATIVE_SSH` environment variable will allow you to avoid having to type `--native-ssh` every time as well.

@slank @ianlintner-wf What's your `~/.ssh/config` file like?

**Comment by slank** [comment] 2015-10-16 21:42
After some testing, it seems to be related to my having `ControlMaster auto` as a default in my SSH config. If I disable it, everything works. Oddly, SSH still uses a master if I explicitly set `ControlMaster no` in a `Host localhost` block so I can't really work around the problem without substantial sacrifice.

Looking at the debug output from `create` with `ControlMaster enabled`, I see that the final SSH attempt may connect successfully but hangs indefinitely. I don't know how `exec.Cmd` handles forks, nor whether `ControlMaster` triggers one, but it looks suspiciously like SSH process isn't exiting the way it's expected to.

**Comment by wkonkel** [comment] 2015-10-30 04:21
I just ran into the "Starting VM" hanging issue and it wasn't the ```~/.ssh/config ControlMaster``` problem a lot of people seem to be having. 

I eventually discovered that I had accidentally commented out ```127.0.0.1 localhost``` from my /etc/hosts and it was defaulting to the IPv6 ```::1 localhost```. Adding 127.0.0.1 back fixed the "Starting VM" problem instantly.

**Comment by abbinv** [comment] 2015-11-03 11:18
For me it was because visualization was not enabled in my bios. Enabled it and issue was resolved.

**Comment by default-writer** [comment] 2021-03-22 05:02
> I have been having to use the --native-ssh flag with everything, but it works. (Debug is just there for testing)
> e.g.
> docker-machine -D --native-ssh create --driver=virtualbox default
> docker-machine -D --native-ssh=true ssh default
> docker-machine -D --native-ssh=true env default
> eval "$(docker-machine --native-ssh=true env default)"
> 
> Mac OSX 10.11 El Capitan
> docker-machine version 0.4.1 ([e2c88d6](https://github.com/docker/machine/commit/e2c88d6dac7e06db34c7f0e00c32801cc3adcbbf))
> 
> I have had nothing but problems after upgrading from boot2docker
> I also have vmware running as well as I am comparing performance for dev.
> 
> I created a simple shell wrapper script for my needs in a path.
> 
> #!/bin/bash
> eval docker-machine --native-ssh=true "$@"

The trampoline works!

docker-machine **--native-ssh** create --driver hyperv --hyperv-virtual-switch docker-machine-switch default
