### ISSUE TITLE
github-api-token does not work

### ISSUE THREAD

**Issue by kurtharriger** [docker/machine#2765] opened 2016-01-06 16:14 UTC
From what I can tell version 0.5.5 should have support for --git-api-token but it does not appear to be working for me.  Perhaps I'm mistaken and these changes did not make it into the last release or am I doing something else wrong? 

```
% docker-machine --github-api-token=<redacted> create -d virtualbox shinybox
Running pre-create checks...
(shinybox) You are using version 4.3.14r95030 of VirtualBox. If you encouter issues, you might want to upgrade to version 5 at https://www.virtualbox.org
(shinybox) No default Boot2Docker ISO found locally, downloading the latest release...
Error creating machine: Error with pre-create check: Error getting a version tag from the Github API response.
You may be getting rate limited by Github.

% docker-machine --version
docker-machine version 0.5.5, build
```

**Comment by dgageot** [comment] 2016-01-06 16:23
Hi @kurtharriger I can't reproduce the issue. Can you double check your token? Also could you try the official binaries, not those provided by brew?

**Comment by kurtharriger** [comment] 2016-01-06 16:36
Upgraded, verified token and still same issue.

As a workaround can I manually download the .iso file and save it somewhere specific. Where should I save it so that it docker-machine will find it locally and not attempt to download it again? 

```
% docker-machine --version
docker-machine version 0.5.5, build 02c4254

% docker-machine --github-api-token=$GITHUB_TOKEN create -d virtualbox shinybox
Running pre-create checks...
(shinybox) No default Boot2Docker ISO found locally, downloading the latest release...
Error creating machine: Error with pre-create check: Error getting a version tag from the Github API response.
You may be getting rate limited by Github.

% curl  https://api.github.com/user\?access_token\=$GITHUB_TOKEN
{
  "login": "kurtharriger",
...
}
```

**Comment by dgageot** [comment] 2016-01-06 16:44
It works without using the token right ?

Le mer. 6 janv. 2016 à 17:36, Kurt Harriger <notifications@github.com> a
écrit :

**Comment by kurtharriger** [comment] 2016-01-06 16:50
No, our network at work always seems to be rate limited.  Probably some script running somewhere that isn't using an auth token so we always need to provide an authentication token to github. 

It appears [docker toolbox](https://www.docker.com/docker-toolbox) has everything bundled in it so I downloaded and installed that and it copied the boot2docker.iso into the needed places to get it going.

**Comment by babelfish** [comment] 2016-01-14 21:40
I'm having the same issue when using the same token as in the following rate limit request:

```
curl https://api.github.com/rate_limit\?access_token\=<redacted>
{
  "resources": {
    "core": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1452811101
    },
    "search": {
      "limit": 30,
      "remaining": 30,
      "reset": 1452807561
    }
  },
  "rate": {
    "limit": 5000,
    "remaining": 5000,
    "reset": 1452811101
  }
}
```

**Comment by dgageot** [comment] 2016-01-18 08:19
Related to https://github.com/docker/machine/issues/2296?

**Comment by dgageot** [comment] 2016-01-26 16:49
Duplicate of https://github.com/docker/machine/issues/2296

**Closed by dgageot** 2016-01-26 16:49 UTC
Labels: area/b2d, kind/bug

**Comment by sjackman** [comment] 2016-02-03 21:06
I'm getting this error as well now. It worked fine yesterday. I don't think I'm being rate limited. I provided a `--github-api-token`, but it didn't help.

```
❯❯❯ docker-machine --github-api-token=redacted create --driver virtualbox default
Running pre-create checks...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
Error creating machine: Error with pre-create check: Error getting a version tag from the Github API response.
You may be getting rate limited by Github.
❯❯❯ docker-machine --version
docker-machine version 0.5.6, build 61388e9
```

**Comment by sjackman** [comment] 2016-02-03 21:11
Here's a workaround inspired by @kurtharriger 
```sh
curl -o ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v1.10.0-rc3/boot2docker.iso
```
