### ISSUE TITLE
script error during DOCKER_OPTS injection

### ISSUE THREAD

**Issue by noodlehaus** [docker/machine#445] opened 2015-01-30 10:17 UTC
hi. i'm trying to use machine with openstack, and when it gets to the point where the `DOCKER_OPTS` are being injected into the host, the following error occurs.

```
DEBU[0154] Command: %s[sudo sh -c 'echo "export DOCKER_OPTS=\'--tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376\'" | sudo tee -a /etc/default/docker']  MachineId=8ce46b4a-8931-432a-9431-a5e6b42eacfe
DEBU[0154] executing: ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 22 -i /Users/noodlehaus/.docker/machines/34ce975260d8831c577ce7db92a257a6/id_rsa stack@10.64.252.30 sudo sh -c 'echo "export DOCKER_OPTS=\'--tlsverify --tlscacert=/etc/docker/ca.pem --tlskey=/etc/docker/server-key.pem --tlscert=/etc/docker/server.pem --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376\'" | sudo tee -a /etc/default/docker' 
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
ERRO[0156] Error creating machine: exit status 1        
WARN[0156] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0156] Error creating machine
```

This is on OS X.

**Comment by sthulb** [comment] 2015-01-30 10:34
This is probably linked with #434

**Comment by ehazlett** [comment] 2015-01-30 14:07
@sthulb I don't think so.  #434 is for the `ssh` command while this is during provisioning.

**Comment by ehazlett** [comment] 2015-01-30 14:14
@ggiamarchi any idea here?

**Comment by LaynePeng** [comment] 2015-02-16 09:10
This bug is caused by \' cannot work. Please change two  \' to  " \" .

**Comment by LaynePeng** [comment] 2015-02-16 09:31
It is caused by \' . Change it to \" will work.

**Comment by LaynePeng** [comment] 2015-02-16 10:09
I did the fix myself:

index a28fc68..61537ae 100644
--- a/host.go
+++ b/host.go
@@ -246,7 +246,7 @@ DOCKER_TLS=no`, opts, caCertPath, serverKeyPath, serverCertP
                daemonOpts = fmt.Sprintf("--host=unix:///var/run/docker.sock --h
                daemonOptsCfg = "/etc/default/docker"
                opts := fmt.Sprintf("%s %s", defaultDaemonOpts, daemonOpts)
-               daemonCfg = fmt.Sprintf("export DOCKER_OPTS='%s'", opts)
+               daemonCfg = fmt.Sprintf("export DOCKER_OPTS=\\\"%s\\\"", opts)
        }

        return &DockerConfig{

**Comment by ehazlett** [comment] 2015-02-16 15:36
@noodlehaus can you confirm the above works?

**Comment by cjellick** [comment] 2015-02-18 18:02
+1 Experienced the same bug and the above fixed it.

**Comment by noodlehaus** [comment] 2015-02-18 18:03
yes this fixed it for me as well.

**Comment by ehazlett** [comment] 2015-02-19 03:51
thx @noodlehaus @cjellick 

@LaynePeng do you want to create a PR from the above?

**Comment by LaynePeng** [comment] 2015-02-19 05:12
Sure.

**Comment by ehazlett** [comment] 2015-02-23 15:05
Closing as #559 was merged.

**Closed by ehazlett** 2015-02-23 15:05 UTC
Labels: bug, driver:openstack
