### ISSUE TITLE
[virtualbox] Multiple machines have the same IP address

### ISSUE THREAD

**Issue by arun-gupta** [docker/machine#1996] opened 2015-10-16 22:19 UTC
Through some (don't remember) combination of stop/restart Docker Machine, duplicate IP addresses are assigned to two machines now. `docker-machine ls` shows:

```
> docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376   
lab       *        virtualbox   Running   tcp://192.168.99.100:2376  
```

Ouch, this is totally broken!

**Comment by kacole2** [comment] 2015-10-22 23:24
shut one down and bring it back up... does that solve the issue?

**Comment by dgageot** [comment] 2015-11-02 15:10
Other users have reported, this duplicate ip assignment.
But we lack more evidences of how it happens.

@arun-gupta Closing for now, re-open if you manage to reproduce it.

**Closed by dgageot** 2015-11-02 15:10 UTC
Labels: driver/virtualbox

**Comment by dgageot** [comment] 2015-11-03 08:14
Duplicate of #1892
