### ISSUE TITLE
Allow specification of key name for openstack.

### ISSUE THREAD

**Issue by sky-shiny** [docker/machine#1738] opened 2015-08-20 09:50 UTC
I would like to be able to specify the key name for a docker machine provisioned on openstack, rather than getting the name-guid format by default.

**Comment by fturiot** [comment] 2015-09-12 17:00
yes because some openstack provider limit key quantity

**Comment by ggiamarchi** [comment] 2015-09-18 14:47
That means you'll need also to give the SSH private key to docker machine. One way to achieve that would be to add two new flags.

| CLI option                       | Environment variable   | Default |
|----------------------------------|------------------------|---------|
| `--openstack-keypair-name`       | `OS_KEYPAIR_NAME`      | (generated) |
| `--openstack-private-key-file`   | `ÒS_PRIVATE_KEY_FILE`  | (generated) |

Both should be specified to use the desired keypair.

@sky-shiny @fturiot  WDYT ?

**Comment by fturiot** [comment] 2015-09-27 18:34
Thanks

**Comment by sebmoule** [comment] 2015-11-25 14:55
This 2 parameters really exists ? it seams that I can't find them 

i work with docker-machine version 0.5.1 (7e8e38e)

thanks

**Comment by fsoppelsa** [comment] 2015-12-12 22:36
@ggiamarchi why a private key?

What's the spec? If `openstack-keypair-name` is specified, then instead of generate and add a new Keypair, we use the one already present (in `nova keypair-list`) no?

**Comment by fsoppelsa** [comment] 2015-12-14 05:52
@ggiamarchi @nathanleclaire I have a working implementation for this BUT how do we want to handle the machine removal?

Now, if I create a machine ***m*** with existing keypair ***k*** in Nova, when I remove m, dm removes also k.

If we want k to be shared among different machines, we could add a new field to specify that the keypair should not be removed, or add a suffix to the name (dirty)... Ideas? @sebmoule @sky-shiny

**Comment by sebmoule** [comment] 2015-12-14 06:48
I don't know how dm stock internal info (is it just the .docker/machines/ repository ?

But i agree if you create a machine with existing key dm must not delete it and we need a way to flag this info somewhere

Sébastien

**Comment by nathanleclaire** [comment] 2015-12-15 22:53
As @ggiamarchi says here https://github.com/docker/machine/issues/1738#issuecomment-141473539, in an implementation where an SSH key is specified for use with the created machine, it's expected that the user takes care of creating it (and destroying if need be).  This has been the implicit expected behavior so far from drivers.

**Comment by fsoppelsa** [comment] 2015-12-15 23:34
Yes I followed the spec in https://github.com/docker/machine/issues/1738#issuecomment-141473539 

Now machine removal in OpenStack driver includes the key removal from Nova. I have a simpler idea than hacking `config.json`. We could by default ***not*** remove the keypair from Nova, but do that only if a force option like `--openstack-remove-keypair` is specified to `dm rm`.

WDYT?

**Comment by fsoppelsa** [comment] 2015-12-17 17:04
@sebmoule can you try that PR and see if it works for you?

**Comment by sebmoule** [comment] 2015-12-18 09:16
@fsoppelsa sorry for asking this, but can you tell me how can I get the PR version for testing ?

**Comment by fsoppelsa** [comment] 2015-12-18 19:11
Just clone https://github.com/fsoppelsa/machine and build the binary

**Comment by fsoppelsa** [comment] 2016-01-09 10:34
@sebmoule now it's merged

**Comment by fsoppelsa** [comment] 2016-01-26 09:36
@nathanleclaire @jeanlaurent probably you can close, due to the previous merge.

**Comment by nathanleclaire** [comment] 2016-01-28 03:37
Thanks @fsoppelsa !

**Closed by nathanleclaire** 2016-01-28 03:37 UTC
Labels: driver/openstack

**Comment by sebmoule** [comment] 2016-05-09 14:17
I confirm no problem anymore! Thanks!
