### ISSUE TITLE
[DigitalOcean driver] Inconsistent / incorrect state displayed after stop

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#215] opened 2015-01-05 04:50 UTC
Assume a DigitalOcean machine has been created with the default settings and is now the active host.

Now run:

```console
$ machine stop
```

You can monitor the output of `machine ls` reporting this droplet's status in the terminal with something like:

```console
$ while true; do out=$(machine ls); clear; echo "$out"; sleep 1; done
```

(or just run `machine ls` a few times)

**RESULT:** The droplet periodically (frequently) reports its status as "Running" instead of "Stopped", when this should not be the case at all.

**Comment by bfirsh** [comment] 2015-01-05 15:34
:+1: Stop should wait until the machine has stopped.

**Comment by ehazlett** [comment] 2015-01-05 22:16
This looks like it might be an issue with the DO API.  I've had an instance off for 10 min and I get "active" for the state from the API about 5% of the time.

**Comment by ehazlett** [comment] 2015-01-05 22:22
I can also reproduce with `curl` directly against their API.  Opening an issue with them.

**Comment by ehazlett** [comment] 2015-01-14 16:41
DO states the issue is resolved and a quick test confirms.  Closing.

**Comment by nathanleclaire** [comment] 2015-01-14 16:41
:cake: :clap: :tada:

**Closed by ehazlett** 2015-01-14 16:41 UTC
