### ISSUE TITLE
Mac OSX, DNS isn't refresh when changing wifi network

### ISSUE THREAD

**Issue by kureikain** [docker/machine#2323] opened 2015-11-18 00:40 UTC
When I'm at home and booting docker with  `docker-machine start default`, it uses DNS of my LAN, Let's say 192.168.1.1

Then when I came to work, the DNS (in /etc/resolve.conf) stays same, and the DNS is no longer valid at work. But the docker machine (run in Virtual Box) doesn't automatically update DNS to reflect new network config.

As a result, any build command will fail because the container cannot fetch package due to invalid DNS.

Right now I manually restart with `docker-machine restart default` and it works, however it will be great if DNS can be updated automatically when the host change/switch network.

**Comment by nathanleclaire** [comment] 2015-11-18 01:33
Thanks for the report @kureikain .

Dupe of: https://github.com/docker/machine/issues/2095

I need to look into why this DNS resolution change happens.  I'm not sure if it's related to VBox or to TinyCore.

**Closed by nathanleclaire** 2015-11-18 01:33 UTC
