### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2156] opened 2015-11-04 00:52 UTC
- [x] bump version numbers
 - [x] update create section
 - [ ] refine documentation about writing own driver #1822

**Comment by jeffellin** [comment] 2015-11-16 19:13
@dmp42 is there a PR for this? I am looking for some docs around driver creation.

**Comment by nathanleclaire** [comment] 2015-11-16 19:17
Not so far, but eventually we will have a guide covering creating a driver plugin in more depth.

**Comment by jeffellin** [comment] 2015-11-16 19:19
Is there any samples/reference info anywhere?  Do I have to do anything beyond compiling a driver binary?

**Comment by nathanleclaire** [comment] 2015-11-16 19:21
@jeffellin If the driver binary compiles with Machine master and is available through `PATH` it should be usable through `docker-machine create -d foo`.

**Comment by jeffellin** [comment] 2015-11-18 18:37
@nathanleclaire how would you recommend dealing with the docker machine dependencies?  Should I vendorize docker machine?  Will the docker-machine vendorized dependencies be pulled in from its own vendor directory?

**Comment by jeffellin** [comment] 2015-11-20 23:34
@nathanleclaire vendorizing seemed to work well.  

https://github.com/jeffellin/machine-cloudformation/tree/vendorize

**Comment by nathanleclaire** [comment] 2015-11-21 00:03
Ah, cloudformation driver, interesting.  Good to hear vendorizing worked out for you.

**Comment by nathanleclaire** [comment] 2015-11-21 00:04
Make sure to add to `AVAILABLE_DRIVER_PLUGINS.md` whenever you feel comfortable.

**Comment by jeffellin** [comment] 2015-11-21 00:06
as you know I have some outstanding pull requests for ec2 driver,   I
figure rather than continuing to extend that driver for some advanced use
cases initiating cloud formation would be better.  This way I can do just
about anything. Create load balancers, dns entries.  We might even have a
use case where we ant to create an entire VPC.

**Comment by nathanleclaire** [comment] 2015-11-21 00:16
Sure, there might be some things we actually do want in scope of the EC2 driver though, so don't count it out.  If we feel like it's out of scope, we'll let you know.

**Comment by jakirkham** [comment] 2015-11-23 15:05
Really interested in seeing some docs/trivial examples of how to create a driver.

**Comment by dgageot** [comment] 2016-01-26 14:43
Closing. Duplicate of https://github.com/docker/machine/issues/1822

**Closed by dgageot** 2016-01-26 14:43 UTC
Labels: kind/docs
