### ISSUE TITLE
[VirtualBox] Outbound networking fails when changing WiFi networks

### ISSUE THREAD

**Issue by iBobik** [docker/machine#2095] opened 2015-10-27 07:10 UTC
When I change network location (switch to different WiFi on MacBook) Docker Machine always losts connectivity until I restart it (`docker-machine restart default`).

```bash
Bobik-MBP:kmtravel Bobik$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.8.3, build master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
Docker version 1.8.3, build f4bf5c7
docker@default:~$ ping github.com
PING github.com (192.30.252.131): 56 data bytes
64 bytes from 192.30.252.131: seq=0 ttl=63 time=69.194 ms
64 bytes from 192.30.252.131: seq=1 ttl=63 time=160.706 ms
64 bytes from 192.30.252.131: seq=2 ttl=63 time=176.462 ms
64 bytes from 192.30.252.131: seq=3 ttl=63 time=27.249 ms
64 bytes from 192.30.252.131: seq=4 ttl=63 time=26.200 ms
^C
--- github.com ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 26.200/91.962/176.462 ms
```

Now, I switched my MBP to another WiFi network.

```bash
docker@default:~$ ping github.com
ping: bad address 'github.com'
docker@default:~$ exitexit status 1
Bobik-MBP:kmtravel Bobik$ docker-machine restart default
Starting VM...
Restarted machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Bobik-MBP:kmtravel Bobik$ eval "$(docker-machine env default)"
Bobik-MBP:kmtravel Bobik$ docker-machine ssh default
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.8.3, build master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
Docker version 1.8.3, build f4bf5c7
docker@default:~$ ping github.com
PING github.com (192.30.252.131): 56 data bytes
64 bytes from 192.30.252.131: seq=0 ttl=63 time=28.657 ms
64 bytes from 192.30.252.131: seq=1 ttl=63 time=93.236 ms
64 bytes from 192.30.252.131: seq=2 ttl=63 time=55.862 ms
^C
--- github.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 28.657/59.251/93.236 ms
docker@default:~$ 
```

**Comment by nathanleclaire** [comment] 2015-10-29 19:23
Yeah, unfortunately it's a known issue.  It's related to VirtualBox networking.  We'll continue looking into it, thanks.

**Comment by nathanleclaire** [comment] 2015-11-18 01:42
Dupe of: https://github.com/docker/machine/issues/1857

**Closed by nathanleclaire** 2015-11-18 01:42 UTC
Labels: driver/virtualbox
