### ISSUE TITLE
Driver 'none' should work when a non-TLS URL is provided

### ISSUE THREAD

**Issue by gordontyler** [docker/machine#2355] opened 2015-11-19 16:02 UTC
I have a Docker host configured with insecure access on port 2375. I can access it using `docker -H torneosth1:2375 ps` with no other DOCKER_* env vars set. I would like to register this host in docker-machine to make it easier to switch between various hosts.

However, after registering the host using the 'none' driver (`docker-machine create -d none --url tcp://torneosth1:2375 torneosth1`), when I try to make it the active machine, it fails with the following:

```
Error running connection boilerplate: Error checking and/or regenerating the certs: There was an error validating certificates for host "torneosth1:2375": open C:\Users\GTyler\.docker\machine\machines\torneosth1\server.pem: The system cannot find the file specified.
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

It would appear that docker-machine assumes that all hosts are secured with TLS. This host is on an internal network and will never be Internet-accessible -- it doesn't need TLS. The 'none' driver should accept an option to indicate whether the host should be accessed using TLS.

**Comment by gordontyler** [comment] 2015-11-19 16:04
As a corollary, it would be useful if the 'none' driver also accepted options providing paths to the certificates needed for a TLS connection, so that docker-machine could install the files in the correct location.

**Comment by dgageot** [comment] 2016-01-26 16:43
Duplicate of https://github.com/docker/machine/issues/1532

**Closed by dgageot** 2016-01-26 16:43 UTC
Labels: driver/none
