### ISSUE TITLE
Error creating machine with hyperv driver in 0.5.1

### ISSUE THREAD

**Issue by factormystic** [docker/machine#2362] opened 2015-11-19 19:39 UTC
Not sure what the problem is, hopefully this debug output is useful:

Creating the machine:
```
C:\users\me\utilities\docker-machine> .\docker-machine.exe --debug create --driver=hyperv dev
Docker Machine Version: 0.5.1 (7e8e38e)
Found binary path at .\docker-machine-driver-hyperv.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:52290
() Calling RPCServerDriver.GetVersion
Using API Version 1
() Calling RPCServerDriver.SetConfigRaw
() Calling RPCServerDriver.GetMachineName
(flag-lookup) Calling RPCServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RPCServerDriver.Close
Successfully made call to close driver server
Found binary path at .\docker-machine-driver-hyperv.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:52295
() Calling RPCServerDriver.GetVersion
Using API Version 1
() Calling RPCServerDriver.SetConfigRaw
() Calling RPCServerDriver.GetMachineName
(dev) Calling RPCServerDriver.GetMachineName
(dev) Calling RPCServerDriver.DriverName
(dev) Calling RPCServerDriver.GetCreateFlags
(dev) Calling RPCServerDriver.SetConfigFromFlags
Running pre-create checks...
(dev) Calling RPCServerDriver.PreCreateCheck
(dev) Calling RPCServerDriver.GetConfigRaw
(dev) Calling RPCServerDriver.GetConfigRaw
Creating machine...
(dev) Calling RPCServerDriver.Create
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile @(Get-Command Get-VM).ModuleName
(dev) DBG | [stdout =====>] : Hyper-V
(dev) DBG |
(dev) DBG | [stderr =====>] :
(dev) OUT | Creating SSH key...
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile @(Get-VMSwitch).Name
(dev) OUT | Creating VM...
(dev) DBG | [stdout =====>] : Hyper-V: Internal Switch
(dev) DBG | Hyper-V: USB Ethernet
(dev) OUT | Using switch Hyper-V: Internal Switch
(dev) DBG | New Virtual Switch-wifi
(dev) DBG |
(dev) DBG | [stderr =====>] :
(dev) OUT | Creating VHD
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile New-VHD -Path 'C:\Users\me\.docker\machine\machines\dev\fixed.vhd' -SizeBytes 10MB -Fixed
(dev) DBG | [stdout =====>] :
(dev) DBG |
(dev) DBG | ComputerName            : me-PC
(dev) DBG | Path                    : C:\Users\me\.docker\machine\machines\dev\fixed.vhd
(dev) DBG | VhdFormat               : VHD
(dev) DBG | VhdType                 : Fixed
(dev) DBG | FileSize                : 10486272
(dev) DBG | Size                    : 10485760
(dev) DBG | MinimumSize             :
(dev) DBG | LogicalSectorSize       : 512
(dev) DBG | PhysicalSectorSize      : 512
(dev) DBG | BlockSize               : 0
(dev) DBG | ParentPath              :
(dev) DBG | DiskIdentifier          : 4ED944D5-A8AF-42E7-97C2-2D9C92850F74
(dev) DBG | FragmentationPercentage : 0
(dev) DBG | Alignment               : 1
(dev) DBG | Attached                : False
(dev) DBG | DiskNumber              :
(dev) DBG | Number                  :
(dev) DBG |
(dev) DBG |
(dev) DBG |
(dev) DBG |
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Convert-VHD -Path 'C:\Users\user\.docker\machine\machines\dev\fixed.vhd' -DestinationPath 'C:\Users\me\.docker\machine\machines\dev\disk.vhd' -VHDType Dynamic
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Resize-VHD -Path 'C:\Users\me\.docker\machine\machines\dev\disk.vhd' -SizeBytes 20000MB
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile New-VM -Name dev -Path 'C:\Users\me\.docker\machine\machines\dev' -MemoryStartupBytes 1024MB
(dev) DBG | [stdout =====>] :
(dev) DBG | Name State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
(dev) DBG | ---- ----- ----------- ----------------- ------   ------             -------
(dev) DBG | dev  Off   0           0                 00:00:00 Operating normally 7.0
(dev) DBG |
(dev) DBG |
(dev) DBG |
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Set-VMDvdDrive -VMName dev -Path 'C:\Users\me\.docker\machine\machines\dev\boot2docker.iso'
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Add-VMHardDiskDrive -VMName dev -Path 'C:\Users\me\.docker\machine\machines\dev\disk.vhd'
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Connect-VMNetworkAdapter -VMName dev -SwitchName 'Hyper-V: Internal Switch'
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] :
(dev) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Start-VM -Name dev
(dev) OUT | Starting  VM...
(dev) DBG | [stdout =====>] :
(dev) DBG | [stderr =====>] : Start-VM : 'dev' failed to start.
Error creating machine: Error in driver during machine creation: exit status 1
```

Confirm it's there but stopped for reasons unknown:
```
C:\users\me\utilities\docker-machine> .\docker-machine.exe ls
error getting URL for host dev: IP not found
NAME   ACTIVE   DRIVER   STATE     URL   SWARM
dev    -        hyperv   Stopped
```

Confirm hyperv can see it:
```
C:\users\me\utilities\docker-machine> get-vm dev

Name State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
---- ----- ----------- ----------------- ------   ------             -------
dev  Off   0           0                 00:00:00 Operating normally 7.0
```

Starting it myself:
```
C:\users\me\utilities\docker-machine> start-vm dev

C:\users\me\utilities\docker-machine> get-vm dev

Name State   CPUUsage(%) MemoryAssigned(M) Uptime           Status             Version
---- -----   ----------- ----------------- ------           ------             -------
dev  Running 11          1024              00:00:04.2660000 Operating normally 7.0
```

Confirm that now it's running:
```
C:\users\me\utilities\docker-machine> .\docker-machine.exe ls
error getting URL for host dev: IP not found
NAME   ACTIVE   DRIVER   STATE     URL   SWARM
dev    *        hyperv   Running
```

**Comment by nathanleclaire** [comment] 2015-11-19 23:34
cc @ahmetalpbalkan

**Comment by jamesmeen** [comment] 2015-11-24 12:48
Possibly a duplicate of my issue #2267

**Comment by ahmetalpbalkan** [comment] 2015-11-30 21:21
@nathanleclaire friendly reminder: I don't own a windows machine, I have never used hyper-v or hyper-v docker-machine driver, and I am not the maintainer of hyper-v driver. :)

**Comment by dgageot** [comment] 2016-01-26 16:21
This is fixed in 1cd6a37

**Comment by nathanleclaire** [comment] 2016-01-27 01:41
We can close this then?

**Closed by nathanleclaire** 2016-01-27 01:41 UTC
Labels: driver/hyperv
