### ISSUE TITLE
`none` driver is broken

### ISSUE THREAD

**Issue by metasim** [docker/machine#2270] opened 2015-11-12 14:57 UTC
## Synopsis

I have several manually configured docker servers that I added to my `docker-machine` inventory using the `none` driver:

```
# This is using v0.4.1
$ docker-machine create --driver=none --url=tcp://myhost.domain.tld:2376 myhost
# Then copy certificates and keys to various places under ~/.docker/machine/machines
```

I can then switch between a local VM image and my staging/production servers, as expected

```
$ eval "$(docker-machine env myhost)"
$ docker-machine ls
NAME          ACTIVE   DRIVER       STATE     URL                                         SWARM
myhost      *        none                   tcp://myhost.domain.tld:2376   
```
 
After upgrading to docker-machine 0.5.0, when I run `env` I get this:

```
$ docker-machine -D env myhost
Docker Machine Version: 0.5.0 (HEAD)
Found binary path at /usr/local/bin/docker-machine-driver-none
Launching plugin server for driver none
Plugin server listening at address 127.0.0.1:64831
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(devops01) Calling RpcServerDriver.GetState
Error running connection boilerplate: myhost is not running. Please start it in order to use the connection settings
```

If I try recreating the entry I still get the same error.

Would love some ideas on how to further debug this aside from rolling back to 0.4.1.

## Client
```
$ uname -a
Darwin mymac 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64 
```

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:17:48 UTC 2015
 OS/Arch:      darwin/amd64
```

## Server

```
$ uname -a
Linux myserver 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by nathanleclaire** [comment] 2015-11-13 01:13
I think we merged in / worked on some code to fix the `state.Running` check, have you tried a master build?

**Comment by metasim** [comment] 2015-11-15 23:43
@nathanleclaire I'm not a Go developer, so need to learn what's involved to be able to do that. Will probably just wait until the next official release. In the mean time I've rolled back to 0.4.1.

**Comment by nathanleclaire** [comment] 2015-11-17 19:14
@metasim Please try the 0.5.1 release and follow up to either close this or report that you still have issues.  It contains the mentioned fix.

**Comment by tavisto** [comment] 2015-11-23 23:18
I have been having the same issue. I found a workaround if you already have all the certs in the specific machine folder, which I believe was the default before. Edit the config.json of the machine  to point to the CA and client keys for that specific machine instead of the global machine ones. 

e.g (where $machine_name == the name of your machine you are working on)

    AuthOptions: {
            CertDir: /Users/$USER/.docker/machine/certs,
            CaCertPath: /Users/$USER/.docker/machine/certs/ca.pem,
            CaPrivateKeyPath: /Users/$USER/.docker/machine/certs/ca-key.pem,
            ...

would become

    AuthOptions: {
            CertDir: /Users/$user/.docker/machine/machines/$machine_name,
            CaCertPath: /Users/taitken/.docker/machine/machines/$machine_name/ca.pem,
            CaPrivateKeyPath: /Users/$USER/.docker/machine/machines/$machine_name/ca-key.pem,
            ...

Once I did this I was able to use my custom CA.

**Comment by metasim** [comment] 2015-11-24 14:10
@tavisto  +1!!!

**Comment by nathanleclaire** [comment] 2015-11-24 17:06
@tavisto Great info, thanks for posting.  I think I have a better feel for the underlying issue now.

**Comment by marcellodesales** [comment] 2015-12-18 18:45
I'm having the problem of "remote error: handshake failure even if docker ps properly communicates with host (machine 0.5.4)" https://github.com/docker/machine/issues/2628

**Comment by jeanlaurent** [comment] 2015-12-23 09:22
@metasim can you check #2667 and describe the way you see the `none` driver works for your case ?

**Comment by metasim** [comment] 2015-12-24 17:04
Done! :-)

**Comment by dgageot** [comment] 2016-01-26 16:43
Duplicate of https://github.com/docker/machine/issues/2667

**Closed by dgageot** 2016-01-26 16:43 UTC
Labels: driver/none, kind/upgrade

**Comment by li0nel** [comment] 2018-04-07 09:07
One solution to clone a machine and keep `docker-machine ssh` usage:

1. `cp -R ~/.docker/machine/machines/my_machine . && cp ~/.docker/machine/certs/* ./my_machine/certs`
2. `sed -i.bak 's/machine\/certs/machine\/machines\/my_machine\/certs/' ./my_machine/config.json`
3. `sed -i.bak 's/your_username/your_teammate_username/' ./my_machine/config.json`
4. `tar -zcf my_machine.tar.gz my_machine` and share with teammates

[https://hackernoon.com/finally-you-can-share-docker-machines-without-a-script-8f946d050f7
](https://hackernoon.com/finally-you-can-share-docker-machines-without-a-script-8f946d050f7
)
