### ISSUE TITLE
Pretty graphs for code architecture

### ISSUE THREAD

**Issue by dmp42** [docker/machine#2079] opened 2015-10-24 06:08 UTC
cc @docker/machine-maintainers 

<img width="924" alt="screen shot 2015-10-23 at 11 00 12 pm" src="https://cloud.githubusercontent.com/assets/332946/10709259/d7684ed6-79da-11e5-81ff-e66b371dcf77.png">

@jeanlaurent wdyt?

Would that kind of tooling be helpful to refactor / visualize / clean code?

**Comment by dmp42** [comment] 2015-10-24 06:12
<img width="561" alt="screen shot 2015-10-23 at 11 11 36 pm" src="https://cloud.githubusercontent.com/assets/332946/10709280/7c08139a-79db-11e5-9641-fef4ae1686e2.png">
<img width="779" alt="screen shot 2015-10-23 at 11 11 41 pm" src="https://cloud.githubusercontent.com/assets/332946/10709281/7c1b4096-79db-11e5-841a-301a4efcfab7.png">
<img width="820" alt="screen shot 2015-10-23 at 11 11 46 pm" src="https://cloud.githubusercontent.com/assets/332946/10709282/7c22bb8c-79db-11e5-8dea-7572c9c242ee.png">

**Comment by nathanleclaire** [comment] 2015-10-26 20:06
It's cool, but I don't think it will increase product quality.

Our issues are 90% around:

1. Bugs caused by / related to providers, especially `virtualbox`
2. UX blemishes and non-robustness in case of error, e.g. https://github.com/docker/machine/issues/2086

I don't feel like we have a code architecture problem in general and @dgageot has been taking good steps to making the codebase more testable with just the source in hand, so I'm pretty optimistic there.

**Comment by dgageot** [comment] 2015-11-24 17:18
Let's close this one @dmp42 :-)

**Closed by dgageot** 2015-11-24 17:18 UTC
Labels: kind/quality

**Comment by dmp42** [comment] 2015-11-24 18:12
Noooooooooooo :)
