### ISSUE TITLE
Github API Token option not working

### ISSUE THREAD

**Issue by mattfysh** [docker/machine#3488] opened 2016-06-08 22:50 UTC
Tried both ways (env and CLI option) - separately and together:

`MACHINE_GITHUB_API_TOKEN=X docker-machine -D --github-api-token=X create dev --driver virtualbox`

```
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50099
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:50103
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(dev) Calling .GetMachineName
(dev) Calling .DriverName
(dev) Calling .GetCreateFlags
(dev) Calling .SetConfigFromFlags
Running pre-create checks...
(dev) Calling .PreCreateCheck
(dev) DBG | COMMAND: /usr/local/bin/VBoxManage --version
(dev) DBG | STDOUT:
(dev) DBG | {
(dev) DBG | 5.0.20r106931
(dev) DBG | }
(dev) DBG | STDERR:
(dev) DBG | {
(dev) DBG | }
(dev) No default Boot2Docker ISO found locally, downloading the latest release...
Error with pre-create check: "Error getting a version tag from the Github API response.\nYou may be getting rate limited by Github."
Opting out of crash reporting.
```

**Comment by mattfysh** [comment] 2016-06-08 22:57
I've also curl'd the defaultUrl from b2d.go with and without token - with token works, without token is returning rate limit exceeded error (due to single external IP address)

**Comment by nathanleclaire** [comment] 2016-06-08 23:23
It's dupe of https://github.com/docker/machine/issues/2296 I think

**Closed by nathanleclaire** 2016-06-08 23:23 UTC
