### ISSUE TITLE
ls not working

### ISSUE THREAD

**Issue by runseb** [docker/machine#2040] opened 2015-10-21 11:59 UTC
Hi, while testing 0.5.0-rc2 I am facing an issue with 'ls' not working.

    $ docker-machine -D ls
    Docker Machine Version: 0.5.0-rc2 (6cac8cc)
    Launching plugin server for driver 
    Driver "" not found. Do you have the plugin binary accessible in your PATH?

All binaries from the release file are in my PATH. I successfully created a machine with:

    $ docker-machine create -d virtualbox foobar

env works and I am able to use docker normally.

ls returns the error above.

**Comment by dgageot** [comment] 2015-10-21 14:19
Hi @runseb, I can't reproduce this issue. Can you provide more context? OS, are there other machines already created? Can you triple check the path?...

**Comment by runseb** [comment] 2015-10-21 14:51
Hi,

OSX 10.8.5
Virtualbox 4.3.30 (latest update)

I downloaded the rc2 zip from github release page.
Unzip
Moved all binaries to somewhere /usr/local/bin

    $ docker-machine
docker-machine                         docker-machine-driver-exoscale         docker-machine-driver-none             docker-machine-driver-virtualbox
docker-machine-driver-amazonec2        docker-machine-driver-generic          docker-machine-driver-openstack        docker-machine-driver-vmwarefusion
docker-machine-driver-azure            docker-machine-driver-google           docker-machine-driver-rackspace        docker-machine-driver-vmwarevcloudair
docker-machine-driver-digitalocean     docker-machine-driver-hyperv           docker-machine-driver-softlayer        docker-machine-driver-vmwarevsphere
    $ docker-machine -v
docker-machine version 0.5.0-rc2 (6cac8cc)

I do have an existing docker-machine virtualbox VM.

I create a new one with:

    $ docker-machine create -d virtualbox toto
    docker-machine env toto
    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.100:2376"
    export DOCKER_CERT_PATH="/Users/sebgoa/.docker/machine/certs" 
    export DOCKER_MACHINE_NAME="toto"
    # Run this command to configure your shell: 
    # eval "$(docker-machine env toto)"
    sebimac:network sebgoa$ eval "$(docker-machine env toto)" 
    sebimac:network sebgoa$ docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    sebimac:network sebgoa$ docker-machine -D ls
    Docker Machine Version: 0.5.0-rc2 (6cac8cc)
    Launching plugin server for driver 
    Driver "" not found. Do you have the plugin binary accessible in your PATH?

I can rm the machine.

If I remove my ~/.docker directory it works fine :)

**Comment by dgageot** [comment] 2015-10-21 15:26
Thank you @runseb. It feels the issue comes from compatibility pb between both versions of `docker-machine` but I didn't manage to reproduce the problem.

Can you share the content of every `config.json` you have under `~/.docker/machine/machines/`?

**Comment by nathanleclaire** [comment] 2015-10-21 19:24
Yes, to know what machines you have, and their `config.json`, is critical to solve this problem.

**Comment by runseb** [comment] 2015-10-21 19:26
I will try to reproduce, but I nuked the entire ~/.docker and removed all VMs....so I can't give that info to you right now :(
I was on docker-machine 0.1.0 though...so bit old.

**Comment by nathanleclaire** [comment] 2015-10-21 21:34
Ah, yeah, there can be some issues with versions going back that far.  Going to close this issue but thanks for reporting @runseb

**Closed by nathanleclaire** 2015-10-21 21:34 UTC
Labels: kind/bug, status/0-triage
