### ISSUE TITLE
Can a single docker host be managed by multiple docker-machine instances?

### ISSUE THREAD

**Issue by prudhvi-chaganti** [docker/machine#3052] opened 2016-02-12 23:53 UTC
Using docker-machine on my system (S1), i created a docker host on AWS using amazon-ec2 driver. I have another system (S2) on which i installed docker-machine. Used generic driver and pointed docker-machine to manage the docker host on AWS. From this point onwards, i am unable to access the docker host from S1. Any suggestions on how to get this working?

**Comment by jeanlaurent** [comment] 2016-02-13 02:06
Using the generic driver on an existing host, will reset the credentials and check docker is probably installed.

What you want to do is to share the credentials of an existing machine in another workstation. This is in the roadmap, but not done atm.

The known workaround for this, is to copy the content of your `~/.docker/machines/MACHINENAME` folder from one workstation to the other, you may have to update the path of some files in the `config.json`. Not ideal.

Closing as duplicate of https://github.com/docker/machine/issues/179

**Closed by jeanlaurent** 2016-02-13 02:06 UTC
