### ISSUE TITLE
Error while creating default machine by start.sh

### ISSUE THREAD

**Issue by mif007** [docker/machine#1862] opened 2015-09-16 03:35 UTC
**System**: Windows 8.1 Pro
**Docker Toolbox**: 1.8.2
**Docker Machine**: 0.4.1
**VirtualBox (installed by Docker Toolbox)**: 5.0.4
**Git (installed by Docker Toolbox)**: 2.5.0

Run start.sh and get
```
Creating Machine default...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
  Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
Looks like something went wrong... Press any key to continue...
```
**VBoxStartup.log**: https://gist.github.com/mif007/7ac45b8e13d225cddc06

**Comment by cemrich** [comment] 2015-09-16 14:51
I had a similar issue I fixed by deinstalling virtualbox and installing the latest [Virtualbox testbuild](https://www.virtualbox.org/wiki/Testbuilds). See https://github.com/docker/machine/issues/1716 for a detailed description.

**Comment by mif007** [comment] 2015-09-17 02:45
Testbuild didn't help. And now virtualbox crashes when launched

**Comment by nathanleclaire** [comment] 2015-11-13 01:43
It's a duplicate of other issues which have to do with VirtualBox start -- e.g. https://github.com/docker/machine/issues/2047 please post info there.

**Closed by nathanleclaire** 2015-11-13 01:43 UTC
Labels: driver/virtualbox, kind/bug
