### ISSUE TITLE
OEL 7 isn't supported for the 'generic' driver

### ISSUE THREAD

**Issue by djsly** [docker/machine#1361] opened 2015-06-15 20:29 UTC
version: Docker Machine 0.3.0rc2

Oracle 7 /etc/os-release format isn't compatible

```
NAME="Oracle Linux Server"
VERSION="7.0"
ID="ol"
VERSION_ID="7.0"
PRETTY_NAME="Oracle Linux Server 7.0"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:oracle_linux:7.0:GA:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.0
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.0
```
results in
```
Error creating machine: OS type not recognized
```

**Comment by nathanleclaire** [comment] 2015-06-16 05:51
Yes, if Machine doesn't recognize the underlying OS, it will not be able to import the machine.  I think Oracle is based on RHEL, so maybe writing a provisioner for it would be not too bad (see for instance the CentOS and Fedora provisioners).  Perhaps this behavior could be better documented?

**Comment by heichblatt** [comment] 2016-01-25 13:01
+1

OEL is just a Red Hat derivative, maybe the Red Hat provisioner could be reused in some way?

**Comment by nathanleclaire** [comment] 2016-01-27 01:33
Most likely -- if they're largely the same a provisioner is usually quite easy to implement by embedding the existing RedHat provisioner (CentOS and Fedora do this IIRC).

**Comment by ezarko** [comment] 2016-04-05 19:13
Issue #3164 seems to be a duplicate of this.

**Closed** 2016-04-13 21:50 UTC
Labels: area/provision, driver/generic, kind/enhancement
