### ISSUE TITLE
docker-machine status outputs to stderr

### ISSUE THREAD

**Issue by lambdafu** [docker/machine#2920] opened 2016-01-25 21:47 UTC
Srsly?

```
$ docker-machine status dev 2> /dev/null 
$ docker-machine status dev > /dev/null 
Running
```

**Comment by jeanlaurent** [comment] 2016-01-26 10:04
Sounds like a duplicate of #2587, with v0.6.1-rc1 it is fixed.

Please re-open if this occurs on the latest version.

**Closed by jeanlaurent** 2016-01-26 10:04 UTC
Labels: area/cli
