### ISSUE TITLE
Error setting machine configuration from flags provided: unexpected EOF

### ISSUE THREAD

**Issue by jamromia** [docker/machine#3059] opened 2016-02-15 14:51 UTC
I followed the supposed solution of https://github.com/docker/machine/issues/2661 by upgrading to 0.6.0 from version 0.5.3 I had on Ubuntu 14.04 and keep getting above error and also tried with 0.5.6 with same results. A colleague copied and tested the same command on his MacOSX machine and it works with 0.5.3 so nothing wrong with my command. My command 
docker-machine -D create --driver amazonec2 --amazonec2-access-key $AWS_ACCESS_KEY_ID --amazonec2-secret-key $AWS_SECRET_ACCESS_KEY --amazonec2-vpc-id <> --amazonec2-subnet-id <> --amazonec2-zone a --amazonec2-region eu-west-1 --amazonec2-instance-type t2.small test.instance

and full output is:

Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver amazonec2
Plugin server listening at address 127.0.0.1:50036
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver amazonec2
Plugin server listening at address 127.0.0.1:43585
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(test.instance) Calling .GetMachineName
(test.instance) Calling .DriverName
(test.instance) Calling .GetCreateFlags
(test.instance) Calling .SetConfigFromFlags
(test.instance) DBG | 2016/02/15 14:48:12 DEBUG: Request ec2/DescribeSubnets Details:
(test.instance) DBG | ---[ REQUEST POST-SIGN ]-----------------------------
(test.instance) DBG | POST / HTTP/1.1
(test.instance) DBG | Host: ec2.eu-west-1.amazonaws.com
(test.instance) DBG | User-Agent: aws-sdk-go/1.0.2 (go1.5.3; linux; amd64)
(test.instance) DBG | Content-Length: 98
(test.instance) DBG | Authorization: AWS4-HMAC-SHA256 
(test.instance) DBG | Content-Type: application/x-www-form-urlencoded; charset=utf-8
((test.instance) DBG | X-Amz-Date: 20160215T144812Z
(test.instance) DBG | Accept-Encoding: gzip
(test.instance) DBG | 
(test.instance) DBG | Action=DescribeSubnets&Filter.1.Name=subnet-id&Filter.1.Value.1=subnet-515dbb35&Version=2015-10-01
(test.instance) DBG | -----------------------------------------------------
(test.instance) DBG | 2016/02/15 14:48:13 DEBUG: Response ec2/DescribeSubnets Details:
(test.instance) DBG | ---[ RESPONSE ]--------------------------------------
(test.instance) DBG | HTTP/1.1 200 OK
(test.instance) DBG | Transfer-Encoding: chunked
(test.instance) DBG | Content-Type: text/xml;charset=UTF-8
(test.instance) DBG | Date: Mon, 15 Feb 2016 14:48:13 GMT
(test.instance) DBG | Server: AmazonEC2
(test.instance) DBG | Vary: Accept-Encoding
(test.instance) DBG | 
(test.instance) DBG | dd
(test.instance) DBG | <?xml version="1.0" encoding="UTF-8"?>
(test.instance) DBG | <DescribeSubnetsResponse xmlns="http://ec2.amazonaws.com/doc/2015-10-01/">
(test.instance) DBG |     <requestId>5d2585e1-8160-4595-834f-c8d00e5094fc</requestId>
(test.instance) DBG |     <subnetSet/>
(test.instance) DBG | </DescribeSubnetsResponse>
(test.instance) DBG | 0
(test.instance) DBG | 
(test.instance) DBG | 
(test.instance) DBG | -----------------------------------------------------
(test.instance) DBG | panic: runtime error: index out of range
(test.instance) DBG | 
(test.instance) DBG | goroutine 9 [running]:
(test.instance) DBG | github.com/docker/machine/drivers/amazonec2.(*Driver).SetConfigFromFlags(0xc820212000, 0x7f444b789b60, 0xc8200301e8, 0x0, 0x0)
(test.instance) DBG | 	/go/src/github.com/docker/machine/drivers/amazonec2/amazonec2.go:341 +0x15e2
(test.instance) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).SetConfigFromFlags(0xc82010d560, 0xc8202663b0, 0x24c93a8, 0x0, 0x0)
(test.instance) DBG | 	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:213 +0x60
(test.instance) DBG | reflect.Value.call(0x1392060, 0x1813590, 0x13, 0x1846f40, 0x4, 0xc82028ded8, 0x3, 0x3, 0x0, 0x0, ...)
(test.instance) DBG | 	/usr/local/go/src/reflect/value.go:432 +0x120a
(test.instance) DBG | reflect.Value.Call(0x1392060, 0x1813590, 0x13, 0xc82028ded8, 0x3, 0x3, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/reflect/value.go:300 +0xb1
(test.instance) DBG | net/rpc.(*service).call(0xc8201157c0, 0xc8201140c0, 0xc820220080, 0xc820117a80, 0xc8202160c0, 0x103d7e0, 0xc8202663b0, 0x16, 0x10a5640, 0x24c93a8, ...)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
(test.instance) DBG | created by net/rpc.(*Server).ServeCodec
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x4ac
(test.instance) DBG | 
(test.instance) DBG | goroutine 1 [select]:
(test.instance) DBG | github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver(0x7f444b745988, 0xc820212000)
(test.instance) DBG | 	/go/src/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:52 +0x74f
(test.instance) DBG | main.runDriver(0xc82001413b, 0x9)
(test.instance) DBG | 	/go/src/github.com/docker/machine/cmd/machine.go:171 +0x11b9
(test.instance) DBG | main.main()
(test.instance) DBG | 	/go/src/github.com/docker/machine/cmd/machine.go:88 +0xc7
(test.instance) DBG | 
(test.instance) DBG | goroutine 5 [syscall]:
(test.instance) DBG | os/signal.loop()
(test.instance) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
(test.instance) DBG | created by os/signal.init.1
(test.instance) DBG | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
(test.instance) DBG | 
(test.instance) DBG | goroutine 17 [IO wait]:
(test.instance) DBG | net.runtime_pollWait(0x7f444b746a60, 0x72, 0xc82000a210)
(test.instance) DBG | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
(test.instance) DBG | net.(*pollDesc).Wait(0xc82016df00, 0x72, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
(test.instance) DBG | net.(*pollDesc).WaitRead(0xc82016df00, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
(test.instance) DBG | net.(*netFD).accept(0xc82016dea0, 0x0, 0x7f444b789a80, 0xc820216080)
(test.instance) DBG | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
(test.instance) DBG | net.(*TCPListener).AcceptTCP(0xc8201100b0, 0xc820046e70, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
(test.instance) DBG | net.(*TCPListener).Accept(0xc8201100b0, 0x0, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
(test.instance) DBG | net/http.(*Server).Serve(0xc82001e480, 0x7f444b745ab8, 0xc8201100b0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1887 +0xb3
(test.instance) DBG | net/http.Serve(0x7f444b745ab8, 0xc8201100b0, 0x0, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1765 +0x85
(test.instance) DBG | created by github.com/docker/machine/libmachine/drivers/plugin.RegisterDriver
(test.instance) DBG | 	/go/src/github.com/docker/machine/libmachine/drivers/plugin/register_driver.go:49 +0x525
(test.instance) DBG | 
(test.instance) DBG | goroutine 33 [IO wait]:
(test.instance) DBG | net.runtime_pollWait(0x7f444b7469a0, 0x72, 0xc82000a210)
(test.instance) DBG | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
(test.instance) DBG | net.(*pollDesc).Wait(0xc820218060, 0x72, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
(test.instance) DBG | net.(*pollDesc).WaitRead(0xc820218060, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
(test.instance) DBG | net.(*netFD).Read(0xc820218000, 0xc82023b000, 0x1000, 0x1000, 0x0, 0x7f444b785050, 0xc82000a210)
(test.instance) DBG | 	/usr/local/go/src/net/fd_unix.go:232 +0x23a
(test.instance) DBG | net.(*conn).Read(0xc82021c000, 0xc82023b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/net.go:172 +0xe4
(test.instance) DBG | bufio.(*Reader).fill(0xc820224060)
(test.instance) DBG | 	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
(test.instance) DBG | bufio.(*Reader).Read(0xc820224060, 0xc820220060, 0x1, 0x9, 0x13, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/bufio/bufio.go:207 +0x260
(test.instance) DBG | io.ReadAtLeast(0x7f444b705290, 0xc820224060, 0xc820220060, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/io/io.go:298 +0xe6
(test.instance) DBG | io.ReadFull(0x7f444b705290, 0xc820224060, 0xc820220060, 0x1, 0x9, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/io/io.go:316 +0x62
(test.instance) DBG | encoding/gob.decodeUintReader(0x7f444b705290, 0xc820224060, 0xc820220060, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/encoding/gob/decode.go:121 +0x92
(test.instance) DBG | encoding/gob.(*Decoder).recvMessage(0xc820236080, 0xc8200b5408)
(test.instance) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
(test.instance) DBG | encoding/gob.(*Decoder).decodeTypeSequence(0xc820236080, 0x1cb2b00, 0xc820236080)
(test.instance) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
(test.instance) DBG | encoding/gob.(*Decoder).DecodeValue(0xc820236080, 0x109d720, 0xc820216600, 0x16, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
(test.instance) DBG | encoding/gob.(*Decoder).Decode(0xc820236080, 0x109d720, 0xc820216600, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/encoding/gob/decoder.go:185 +0x289
(test.instance) DBG | net/rpc.(*gobServerCodec).ReadRequestHeader(0xc82021a210, 0xc820216600, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:403 +0x51
(test.instance) DBG | net/rpc.(*Server).readRequestHeader(0xc8201140c0, 0x7f444b7052e0, 0xc82021a210, 0x0, 0x0, 0xc820216600, 0xc8200b5700, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:576 +0x90
(test.instance) DBG | net/rpc.(*Server).readRequest(0xc8201140c0, 0x7f444b7052e0, 0xc82021a210, 0xc8201140c0, 0xc820220080, 0xc820117a80, 0x0, 0x0, 0x0, 0x0, ...)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:543 +0x8b
(test.instance) DBG | net/rpc.(*Server).ServeCodec(0xc8201140c0, 0x7f444b7052e0, 0xc82021a210)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:462 +0x8c
(test.instance) DBG | net/rpc.(*Server).ServeConn(0xc8201140c0, 0x7f444b705230, 0xc82021c000)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:454 +0x4ee
(test.instance) DBG | net/rpc.(*Server).ServeHTTP(0xc8201140c0, 0x7f444b705180, 0xc82021e0b0, 0xc820234000)
(test.instance) DBG | 	/usr/local/go/src/net/rpc/server.go:694 +0x503
(test.instance) DBG | net/http.(*ServeMux).ServeHTTP(0xc820014c00, 0x7f444b705180, 0xc82021e0b0, 0xc820234000)
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1699 +0x17d
(test.instance) DBG | net/http.serverHandler.ServeHTTP(0xc82001e480, 0x7f444b705180, 0xc82021e0b0, 0xc820234000)
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1862 +0x19e
(test.instance) DBG | net/http.(*conn).serve(0xc82021e000)
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1361 +0xbee
(test.instance) DBG | created by net/http.(*Server).Serve
(test.instance) DBG | 	/usr/local/go/src/net/http/server.go:1910 +0x3f6
(test.instance) DBG | 
(test.instance) DBG | goroutine 23 [IO wait]:
(test.instance) DBG | net.runtime_pollWait(0x7f444b746820, 0x72, 0xc82000a210)
(test.instance) DBG | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
(test.instance) DBG | net.(*pollDesc).Wait(0xc820218990, 0x72, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
(test.instance) DBG | net.(*pollDesc).WaitRead(0xc820218990, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
(test.instance) DBG | net.(*netFD).Read(0xc820218930, 0xc820403400, 0x400, 0x400, 0x0, 0x7f444b785050, 0xc82000a210)
(test.instance) DBG | 	/usr/local/go/src/net/fd_unix.go:232 +0x23a
(test.instance) DBG | net.(*conn).Read(0xc82021c200, 0xc820403400, 0x400, 0x400, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/net.go:172 +0xe4
(test.instance) DBG | crypto/tls.(*block).readFromUntil(0xc820528c60, 0x7f444b705088, 0xc82021c200, 0x5, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
(test.instance) DBG | crypto/tls.(*Conn).readRecord(0xc820222b00, 0x1cb2b17, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
(test.instance) DBG | crypto/tls.(*Conn).Read(0xc820222b00, 0xc8202c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
(test.instance) DBG | net/http.noteEOFReader.Read(0x7f444b747490, 0xc820222b00, 0xc8202c4058, 0xc8202c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/net/http/transport.go:1370 +0x67
(test.instance) DBG | net/http.(*noteEOFReader).Read(0xc8205456a0, 0xc8202c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
(test.instance) DBG | 	<autogenerated>:126 +0xd0
(test.instance) DBG | bufio.(*Reader).fill(0xc8203f0f00)
(test.instance) DBG | 	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
(test.instance) DBG | bufio.(*Reader).Peek(0xc8203f0f00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
(test.instance) DBG | 	/usr/local/go/src/bufio/bufio.go:132 +0xcc
(test.instance) DBG | net/http.(*persistConn).readLoop(0xc8202c4000)
(test.instance) DBG | 	/usr/local/go/src/net/http/transport.go:876 +0xf7
(test.instance) DBG | created by net/http.(*Transport).dialConn
(test.instance) DBG | 	/usr/local/go/src/net/http/transport.go:685 +0xc78
(test.instance) DBG | 
(test.instance) DBG | goroutine 24 [select]:
(test.instance) DBG | net/http.(*persistConn).writeLoop(0xc8202c4000)
(test.instance) DBG | 	/usr/local/go/src/net/http/transport.go:1009 +0x40c
(test.instance) DBG | created by net/http.(*Transport).dialConn
(test.instance) DBG | 	/usr/local/go/src/net/http/transport.go:686 +0xc9d
Error setting machine configuration from flags provided: unexpected EOF

**Comment by tdensmore** [comment] 2016-02-20 04:10
Looks like this issue might be a duplicate of : 

https://github.com/docker/machine/issues/2661

**Comment by dgageot** [comment] 2016-02-20 10:53
duplicate of #2661

**Closed by dgageot** 2016-02-20 10:53 UTC
Labels: driver/ec2
