### ISSUE TITLE
docker-machine create --swarm-master requires --swarm to work

### ISSUE THREAD

**Issue by nadiasvertex** [docker/machine#1395] opened 2015-06-20 21:57 UTC
The command:

docker-machine create -d virtualbox --swarm-master --swarm-discovery consul://192.168.99.100:8500/swarm m0

Will create a machine with no running containers. I would expect a "swarm manage" container to have been created. In the swarm docs, we are told that running a swarm node on same host as a master is not a good idea for production. If that's true, then docker-machine should be able to create a node that does not run an exec node.

**Comment by selimekizoglu** [comment] 2015-11-11 16:20
Any update on this?

**Comment by schmunk42** [comment] 2015-11-12 10:43
Same question here.

As @nadiasvertex mentioned, by default your swarm-master is also a node, which may create problems during deployment, eg. if constraints are not properly set some containers will go to the master and consume resources.

Possibly related issue: https://github.com/docker/swarm/issues/1405

Current workaround for me is to manually stop the `swarm-agent` on the master.

**Comment by dgageot** [comment] 2016-01-26 15:21
Duplicate of https://github.com/docker/machine/issues/2302

**Closed by dgageot** 2016-01-26 15:21 UTC
Labels: area/swarm
