### ISSUE TITLE
Do not store digiral ocean access tokens in plain (base64) text

### ISSUE THREAD

**Issue by outcoldman** [docker/machine#2220] opened 2015-11-08 17:03 UTC
Recently I have changed my access token in DO and after that I have found few issues:

1. Docker Machine stores access token in Plain Text (before it was a plain text, now it is in base64, which basically the same thing). You have zero mentions about that on docs http://docs.docker.com/machine/get-started-cloud/ or when you create a driver. My concern is - when I create machine on DO - I actually expect that "~/.docker/machine" has only credentials to VM I created, but in reality using this configuration you can control my whole account on DO created for this account. 
2. There are no ways to update DO credentials if you have changed it. As I said in 1 - I don't think that it is good idea to store them in plain text, but it is actually impossible to update Access Token. The only workaround I have found is to write 10 lines of code in go to do that.
3. For some reason `docker-machine ssh` does not allow you to ssh on remote VM (in my case it was DO) when access token is invalid. SSH keys are valid, so I don't see a reason why I should not be able to ssh to it. I tried to use `ssh foo.com -i ~/.docker/machine/foo/id_rsa` and it worked. Looks like a bug for me.

**Comment by nathanleclaire** [comment] 2015-11-09 20:59
Duplicate of: https://github.com/docker/machine/issues/1312

> There are no ways to update DO credentials if you have changed it. As I said in 1 - I don't think that it is good idea to store them in plain text, but it is actually impossible to update Access Token. The only workaround I have found is to write 10 lines of code in go to do that.

This, I am happy to accept proposals for how to do, and is something I want to address in Machine in the future.

> For some reason docker-machine ssh does not allow you to ssh on remote VM (in my case it was DO) when access token is invalid. SSH keys are valid, so I don't see a reason why I should not be able to ssh to it. I tried to use ssh foo.com -i ~/.docker/machine/foo/id_rsa and it worked. Looks like a bug for me.

It's because it needs to look up the VM's IP address from the DigitalOcean API.  We could store it locally, but then there's yet another stateful bit to keep track of, so I don't plan on covering it soon.

**Closed by nathanleclaire** 2015-11-09 20:59 UTC
