### ISSUE TITLE
Azure driver AZURE_SUBSCRIPTION_CERT and AZURE_SUBSCRIPTION_ID environment variables not taken into account

### ISSUE THREAD

**Issue by chanezon** [docker/machine#2180] opened 2015-11-05 00:01 UTC
https://docs.docker.com/machine/drivers/azure/
$echo $AZURE_SUBSCRIPTION_ID
12345...
$echo $AZURE_SUBSCRIPTION_CERT
/Users/pat/.ssh/docker-azure-cert.pem
$ docker-machine create -d azure pat-2
Error setting machine configuration from flags provided: Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file

if --azure-subscription-id and cert flags are mandatory and the environment variables are not taken into account, maybe they are not needed.

**Comment by dmp42** [comment] 2015-11-05 00:34
cc @ahmetalpbalkan wdyt?

**Comment by nathanleclaire** [comment] 2015-11-05 00:57
It certainly is possible that the flags are not getting propagated to the driver correctly with the new plugin model, so first steps is to ensure that they are actually getting across the wire correctly.

**Comment by dgageot** [comment] 2015-11-05 12:21
Hi @chanezon, I couldn't reproduce your issue.

```
$ export AZURE_SUBSCRIPTION_ID=12345
$ export AZURE_SUBSCRIPTION_CERT=~/.ssh/file_that_exists
$ docker-machine --version
docker-machine version 0.5.0 (04cfa58)
$ docker-machine create -d azure pat-2
Running pre-create checks...
```

Can you please check which version of `docker-machine` you are using?

**Comment by dmp42** [comment] 2015-11-10 21:37
Monsieur @chanezon and his bug are awaited by Monsieur Gageot at the bug fixing booth :-)

**Comment by nathanleclaire** [comment] 2015-11-10 22:40
I also can't seem to dupe this class of issues.  The environment variables have been working OK for me, at least on DigitalOcean and VirtualBox.  It is possible that there is a conversion miss on some of the flags for some drivers which is causing this issue.

**Comment by dgageot** [comment] 2015-11-23 08:55
@chanezon I'm closing the issue since we couldn't reproduce it. Env variables are working fine.
Please re-open the ticket with more details if it still fails on your side.

**Closed by dgageot** 2015-11-23 08:55 UTC
Labels: driver/azure, kind/bug

**Comment by machzqcq** [comment] 2016-04-18 14:42
I am getting this error on yosemite mac. However the same seems to move forward on Windows 7. Freshly installed Docker toolbox in both cases as of 4/17/2016. (Ultimately the windows 7 also got stuck on "waiting for SSH to be available",but that's a different issue)

**On Mac**
```
Anyones-Mac-mini:~ pmacharl$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
Anyones-Mac-mini:~ pmacharl$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 azure-mac-sandbox
Error setting machine configuration from flags provided: Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file
Anyones-Mac-mini:~ pmacharl$ docker-machine ls
NAME               ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
aws-sandbox        -        amazonec2    Stopped                                       Unknown   No IP for instance i-272533e0
default            -        virtualbox   Stopped                                       Unknown
docker-developer   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.0
```

**On Windows 7**  
```
$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-43
08-ba66-02aa66cc0ca8 azure-sandbox
Running pre-create checks...
(azure-sandbox) Microsoft Azure: To sign in, use a web browser to open the page
https://aka.ms/devicelogin. Enter the code ARBVWKQ9G to authenticate.
(azure-sandbox) Completed machine pre-create checks.
Creating machine...
(azure-sandbox) Querying existing resource group.  name="docker-machine"
(azure-sandbox) Creating resource group.  name="docker-machine" location="westus
"
(azure-sandbox) Configuring availability set.  name="docker-machine"
(azure-sandbox) Configuring network security group.  name="azure-sandbox-firewal
l" location="westus"
(azure-sandbox) Querying if virtual network already exists.  name="docker-machin
e-vnet" location="westus"
(azure-sandbox) Configuring subnet.  name="docker-machine" vnet="docker-machine-
vnet" cidr="192.168.0.0/16"
(azure-sandbox) Creating public IP address.  static=false name="azure-sandbox-ip
"
(azure-sandbox) Creating network interface.  name="azure-sandbox-nic"
(azure-sandbox) Creating storage account.  name="vhds93ac0oknz5xngnsj6fsf" locat
ion="westus"
(azure-sandbox) Creating virtual machine.  location="westus" size="Standard_A2"
username="docker-user" osImage="canonical:UbuntuServer:15.10:latest" name="azure
-sandbox"
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
```  

![docker-machine-azure](https://cloud.githubusercontent.com/assets/6425159/14608007/079f97e6-0552-11e6-9164-be0abb76e0b9.png)

**Comment by ahmetalpbalkan** [comment] 2016-04-18 14:57
@machzqcq 

```
Anyones-Mac-mini:~ pmacharl$ docker-machine create --driver azure --azure-subscription-id 48abda7f-a0b5-4308-ba66-02aa66cc0ca8 azure-mac-sandbox
Error setting machine configuration from flags provided: Please specify azure subscription params using options: --azure-subscription-id and --azure-subscription-cert or --azure-publish-settings-file
```

this is happening because you don't have docker-machine 0.7.0.

For the "Waiting for SSH" apparently the VM is not booting up timely. Can you please run it with `docker-machine --debug [...]` next time and send its output? (Preferably by opening a new issue, you're currently posting in a closed issue.)

**Comment by machzqcq** [comment] 2016-04-18 17:31
Sure will do and [here](https://github.com/docker/machine/issues/3333) it is
