### ISSUE TITLE
Odd console output in Windows

### ISSUE THREAD

**Issue by anweiss** [docker/machine#530] opened 2015-02-11 17:57 UTC
Noticing odd console output behavior in Windows.

![2015-02-11_12-52-36](https://cloud.githubusercontent.com/assets/2326106/6152681/15492146-b1ed-11e4-8873-0249c6d85ec7.png)

Looks as if I'm missing a specific font or something. The status lines also don't appear until I scroll down and then scroll back up in the console.

Running Windows Server Technical Preview (Version 6.4.9841)

**Comment by ehazlett** [comment] 2015-02-11 18:08
Thanks.  This is a duplicate of #501.

**Closed by ehazlett** 2015-02-11 18:08 UTC
