### ISSUE TITLE
Machine should have --ssh-user flag common to all drivers

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1672] opened 2015-08-11 20:33 UTC
There are many driver flags which are on the order of `--amazonec2-ssh-user`, `--digitalocean-ssh-user`, etc.  They all seem to do mostly the same thing so this should probably be a "global" create flag like `--swarm` is, for instance.

**Comment by ehazlett** [comment] 2015-08-14 19:56
:+1:

**Comment by dalanmiller** [comment] 2015-10-05 22:40
Also agree here.

**Comment by dgageot** [comment] 2016-02-12 06:30
Duplicate of https://github.com/docker/machine/issues/489

**Closed by dgageot** 2016-02-12 06:30 UTC
Labels: driver/all
