### ISSUE TITLE
0.5.0rc2 default share not working for virtualbox on linux

### ISSUE THREAD

**Issue by atomi** [docker/machine#2045] opened 2015-10-21 20:44 UTC
If I run ```docker-machine create -d virtualbox hello``` on Windows ```docker-machine``` creates a default share under ```/c/``` on the created machine. 

However when running the same command under Linux Mint there is no share that gets created. I checked ```/home/``` as well.

**Comment by nathanleclaire** [comment] 2015-10-22 01:50
Dupe of: https://github.com/docker/machine/issues/1376

**Closed by nathanleclaire** 2015-10-22 01:50 UTC
Labels: kind/bug
