### ISSUE TITLE
Same IP Addresses on Linux

### ISSUE THREAD

**Issue by garystafford** [docker/machine#1892] opened 2015-09-23 02:58 UTC
I know there is a fix underway for ssh multiplexing. Unclear if that is the root cause of continued issues with docker-machine using the same IP addresses for multiple machines. And, these were all just built consecutively without the typical timeout ssh issues on Linux that so many people are still getting. Note the repetition of IP addresses.

```bash
gstafford-X555LA:$ docker-machine ls
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
swarm-master             virtualbox   Running   tcp://192.168.99.100:2376   swarm-master (master)
swarm-node-01            virtualbox   Running   tcp://192.168.99.100:2376   swarm-master
swarm-node-02            virtualbox   Running   tcp://192.168.99.101:2376   swarm-master
swarm-node-03            virtualbox   Running   tcp://192.168.99.102:2376   swarm-master
swarm-node-04            virtualbox   Running   tcp://192.168.99.101:2376   swarm-master
```

Deleting the two boxes with duplicate IPs and re-running commands (took 2x) until they had a unique IP assigned, fixed issue.

```bash
swarm-master             virtualbox   Running   tcp://192.168.99.100:2376   swarm-master (master)
swarm-node-01            virtualbox   Running   tcp://192.168.99.103:2376   swarm-master
swarm-node-02            virtualbox   Running   tcp://192.168.99.101:2376   swarm-master
swarm-node-03            virtualbox   Running   tcp://192.168.99.102:2376   swarm-master
swarm-node-04            virtualbox   Running   tcp://192.168.99.104:2376   swarm-master
```

**Comment by nathanleclaire** [comment] 2015-09-23 03:06
That's a weird one.  Perhaps @ehazlett can chime in on whether or not he's experienced this before.

What's your Virtualbox version?

**Comment by garystafford** [comment] 2015-09-23 03:28
```bash
gstafford@gstafford-X555LA:$ docker --version && 
> docker-compose --version && 
> docker-machine --version && 
> echo "VirtualBox $(vboxmanage --version)"

Docker version 1.8.2, build 0a8c2e3
docker-compose version: 1.4.1
docker-machine version 0.4.1 (e2c88d6)
VirtualBox 5.0.0r101573
```

**Comment by nathanleclaire** [comment] 2015-09-23 18:42
Thanks @garystafford .  Can you please paste the output of:

```console
$ VBoxManage list hostonlyifs
$ VBoxManage list dhcpservers
```

**Comment by garystafford** [comment] 2015-09-23 23:56
@nathanleclaire:
`VBoxManage list hostonlyifs`: https://gist.github.com/garystafford/881ebf19b58d63108656
`VBoxManage list dhcpservers`: https://gist.github.com/garystafford/19669ed3f7fad7ce98b5

**Comment by nathanleclaire** [comment] 2015-09-24 00:14
Hm.  That second half of the dhcpservers looks rather suspect.  If you get a chance, try removing them all and re-trying the creates to see if it fixes the issue.

**Comment by garystafford** [comment] 2015-10-02 04:34
I just cloned and built the latest docker-machine on the master branch on GitHub for Ubuntu and Fedora. I am still seeing no improvements on the ssh errors and duplicate IPs if `docker-machine create` succeeds with Ubuntu or Fedora:
```
gstafford@gstafford-X555LA:$ docker-machine -v
docker-machine version 0.5.0-dev (fe5a722)
```

```
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM
swarm-master    -        virtualbox   Running   tcp://192.168.99.100:2376   swarm-master (master)
swarm-node-01   -        virtualbox   Running   tcp://192.168.99.102:2376   swarm-master
swarm-node-02   -        virtualbox   Running   tcp://192.168.99.100:2376   swarm-master
swarm-node-03   -        virtualbox   Running   tcp://192.168.99.101:2376   swarm-master
```

**Comment by garystafford** [comment] 2015-10-02 13:23
@nathanleclaire I went from 80%+ failures creating machines and/or getting IP address conflicts to 100% success by deleting those extra host-only network adapters you mentioned. On VirtualBox 5.0.3, I went to VirtualBox -> Preferences -> Network -> Host-only Networks, and removed them. After that I created a 5-cluster swarm and added weave with not obvious errors or issues.

**Comment by nathanleclaire** [comment] 2015-10-02 18:12
Thanks a lot for your persistence @garystafford.  The network interfaces in Virtualbox do have a tendency to get out of control and wreak havoc if not periodically pruned, so I wonder if we could do some automatic cleanup of ones which aren't actively in use.

**Comment by dgageot** [comment] 2015-11-03 08:15
Closing. Duplicate of #2091

**Closed** 2015-11-03 10:15 UTC
Labels: driver/virtualbox, kind/bug
