### ISSUE TITLE
Azure docker-machine default driver image is not found  'canonical:UbuntuServer:15.10:latest

### ISSUE THREAD

**Issue by SteveStrong** [docker/machine#3729] opened 2016-09-07 01:59 UTC
So using the defaults, looks lit if fails because azures default image is not there.  am I missing something?

PS C:\WINDOWS\system32> docker-machine create --driver azure --azure-subscription-id XXXXXX-XXX-XXXXXXXXXXXXXX --azure-location=eastus  myDocker
Running pre-create checks...
(myDocker) Completed machine pre-create checks.
Creating machine...
(myDocker) Querying existing resource group.  name="docker-machine"
(myDocker) Creating resource group.  name="docker-machine" location="eastus"
(myDocker) Configuring availability set.  name="docker-machine"
(myDocker) Configuring network security group.  name="myDocker-firewall" location="eastus"
(myDocker) Querying if virtual network already exists.  name="docker-machine-vnet" location="eastus"
(myDocker) Configuring subnet.  name="docker-machine" vnet="docker-machine-vnet" cidr="192.168.0.0/16"
(myDocker) Creating public IP address.  static=false name="myDocker-ip"
(myDocker) Creating network interface.  name="myDocker-nic"
(myDocker) Creating storage account.  name="vhdsxs5wmcddqbuefqulygl4" location="eastus"
(myDocker) Creating virtual machine.  name="myDocker" location="eastus" size="Standard_A2" username="docker-user" osImage="canonical:UbuntuServer:15.10:latest"
Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original
 Error: Long running operation terminated with status 'Failed': Code="ImageNotFound" Message="The platform image 'canonical:UbuntuServer:15.10:latest' is not avai
lable. Verify that all fields in the storage profile are correct."

**Comment by SteveStrong** [comment] 2016-09-07 02:14
![image](https://cloud.githubusercontent.com/assets/500861/18297530/222cbfc0-747f-11e6-87f5-db02c6aa4fb1.png)

currently in azure

**Comment by ahmetalpbalkan** [comment] 2016-09-07 16:08
Duplicate of #3676. Already fixed, waiting for release.

**Comment by ahmetalpbalkan** [comment] 2016-09-13 20:13
@nathanleclaire please close

**Closed** 2016-09-13 20:47 UTC
