### ISSUE TITLE
Unable to publish the application to docker

### ISSUE THREAD

**Issue by VenkateshSrini** [docker/machine#2709] opened 2015-12-29 12:52 UTC
Hi,
I'm trying to execute the following command. 
docker -H tcp://192.168.99.100:2376 build -t sampledocker -f "C:\Users\333478\AppData\Local\Temp\PublishTemp\WebApplication187\approot\src\WebApplication1\Dockerfile" "C:\Users\333478\AppData\Local\Temp\PublishTemp\WebApplication187"

But I get the error 
An error occurred trying to connect: Post http://192.168.99.100:2376/v1.21/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=approot%2Fsrc%2FWebApplication1%2FDockerfile&memory=0&memswap=0&rm=1&t=sampledocker&ulimits=null: WSASend tcp 192.168.99.1:54630: An existing connection was forcibly closed by the remote host.
Please visit http://go.microsoft.com/fwlink/?LinkID=529706 for troubleshooting guide.	WebApplication1		0	

I'm using the docker version v1.9.1. Also driver that I use is virtual box.

Thanks and regards
Venkatesh

**Comment by thaJeztah** [comment] 2015-12-29 13:02
Looks like you created two issues, and this is a duplicate of https://github.com/docker/machine/issues/2710. Can you close one of them?

**Comment by nathanleclaire** [comment] 2015-12-29 22:04
Dupe

**Closed by nathanleclaire** 2015-12-29 22:04 UTC

**Comment by VenkateshSrini** [comment] 2015-12-30 00:48
Yes please close this issue

-----Original Message-----
