### ISSUE TITLE
Enumerate in the documentation the list of cloud provider drivers

### ISSUE THREAD

**Issue by DazWilkin** [docker/machine#1425] opened 2015-06-25 14:54 UTC
"...there are drivers included for several providers including Amazon Web Services, Google Compute Engine, and Microsoft Azure". However, the documentation is sparse with regards the mapping between this list of providers and the parameter values of the docker-machine create driver parameter.

For example, this (somewhat hidden) page includes Google Compute Engine and a good first line would be an example command, at least the driver value for compute engine:

https://github.com/docker/machine/blob/master/docs/index.md#google-compute-engine

    docker-machine create --driver google ...

**Comment by dgageot** [comment] 2016-01-26 14:44
Closing. Duplicate of https://github.com/docker/machine/issues/2705

**Closed by dgageot** 2016-01-26 14:44 UTC
Labels: driver/all, kind/docs
