### ISSUE TITLE
Docker-Machine - VM created in Virtualbox with Azure driver - internal failure while setting the bit

### ISSUE THREAD

**Issue by Delpedro** [docker/machine#3238] opened 2016-03-28 09:54 UTC
The VM created fine. I can ssh into the VM. I can run basic docker commands such as info, run, images etc.

When I execute the following command: docker run -itd -P tutum/hello-world I'm getting the following error.

docker: Error response from daemon: internal failure while setting the bit: open /var/lib/docker/network/files/local-kv.db: no such file or directory.

**Comment by Delpedro** [comment] 2016-03-28 18:46
& here too :D Sir @nathanleclaire

**Comment by nathanleclaire** [comment] 2016-03-28 21:52
This seems to be duplicate of https://github.com/docker/machine/issues/3240

**Closed by nathanleclaire** 2016-03-28 21:52 UTC

**Comment by Delpedro** [comment] 2016-03-28 22:38
Sorry Nathan for the duplication!
