### ISSUE TITLE
GCE: SourceImage option

### ISSUE THREAD

**Issue by Hokutosei** [docker/machine#617] opened 2015-02-26 01:11 UTC
Greetings,

does docker machine adds an option for source image for selecting a SourceImage now?, other drivers currently supports it. would be nice to have an option for gce also. thanks!

**Comment by Hokutosei** [comment] 2015-02-26 08:26
tried hacking and playing machine this afternoon in my dev machine, seems well but, i hit an error when trying to use coreos. 
```
INFO[0045] Uploading SSH Key
INFO[0046] Waiting for SSH Key
INFO[0049] Configuring Machine...
sudo: service: command not found
ERRO[0054] Error creating machine: exit status 1
WARN[0054] You will want to check the provider to make sure the machine and associated resources were properly removed.
FATA[0054] Error creating machine
```

**Comment by ehazlett** [comment] 2015-02-26 15:36
It could be added.  Right now, we only deploy to the latest LTS of Ubuntu supported on the provider (except for local drivers which use b2d).  We are planning to add cloudinit support which would enable a lot more options as far as base image / setup.

**Comment by Hokutosei** [comment] 2015-02-27 03:24
Greetings,

I see, cloudinit could be the best solution for this. so it might not worth adding an option now for source-image. i have a working machine bin in my local that does something like `--google-source-image ubuntu-1404-trusty-v20150128` though.

**Comment by ehazlett** [comment] 2015-02-27 14:53
Cool.  With cloudinit it would make sense.  Thanks!

**Comment by nathanleclaire** [comment] 2015-07-06 19:02
Dupe of https://github.com/docker/machine/issues/1243

**Closed by nathanleclaire** 2015-07-06 19:02 UTC
Labels: driver:google
