### ISSUE TITLE
No vboxsf mounts when running docker-machine from Linux

### ISSUE THREAD

**Issue by bascht** [docker/machine#2063] opened 2015-10-22 21:57 UTC
This might be an issue in boot2docker but I only could reproduce it with docker-machine, so here we go:

### Two files in one folder
```
$ ls
docker-compose.yml  it-works.txt
```
```yaml
# docker-compose.yml
test:
  image: busybox
  volumes:
    - .:/test
```
(it-works.txt is just an empty file to check)

## On a Linux host
```
$ docker-machine create --driver virtualbox bug
[…]
$ eval "$(docker-machine env bug)"
[…]
$ docker-compose run test sh -c 'ls -lsa ./test'
total 4
     0 drwxr-xr-x    2 root     root            40 Oct 22 21:04 .
     4 drwxr-xr-x   19 root     root          4096 Oct 22 21:34 ..
```
## On an OS X host
```
$ docker-machine create --driver virtualbox bug
[…]
$ eval "$(docker-machine env bug)"
[…]
$ docker-compose run test sh -c 'ls -lsa ./test'
total 8
     0 drwxr-xr-x    1 1000     staff          136 Oct 22 21:05 .
     4 drwxr-xr-x   19 root     root          4096 Oct 22 21:09 ..
     4 -rw-r--r--    1 1000     staff           66 Oct 22 21:05 docker-compose.yml
     0 -rw-r--r--    1 1000     staff            0 Oct 22 21:05 it-works.txt
```

---

If I compare both machines, I see that machine on OS X has mounted `/Users`:

```
docker@bug:~$ mount
tmpfs on / type tmpfs (rw,relatime,size=918072k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
none on /Users type vboxsf (rw,nodev,relatime)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
```

while the Linux has no vboxsf mounts or /home mounts

```
docker@bug:~$ mount
tmpfs on / type tmpfs (rw,relatime,size=918064k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
/dev/sda1 on /mnt/sda1/var/lib/docker/aufs type ext4 (rw,relatime,data=ordered)
```

What it does have though, is an empty folder at exactly the same location that the host has:

```
docker@bug:~$ find /home/bascht/
/home/bascht/
/home/bascht/Documents
/home/bascht/Documents/Code
/home/bascht/Documents/Code/docker-machine-bug
```

---

Both Mac OS and Linux are using docker-machine 0.4.1 and docker-compose version 1.4.2 with VirtualBox and Boot2Docker version 1.8.3. I tried docker-machine v0.5.0-rc3 and got the same behaviour. If I can supply more information, let me know. 

Thanks to @railsbros-dirk for testing this on shiny Apple hardware. :)

**Comment by nathanleclaire** [comment] 2015-10-22 22:18
Thanks for the issue -- it's a dupe of : https://github.com/docker/machine/issues/1376

**Closed by nathanleclaire** 2015-10-22 22:18 UTC
