### ISSUE TITLE
Sharing host files for development purposes

### ISSUE THREAD

**Issue by wildsurfer** [docker/machine#1781] opened 2015-08-31 12:34 UTC
I want to use docker-machine to create development environment that is very close to production. In production I use data-only containers that works just fine. In development I want to share source code from the host to the container to be able to see changes made to project in real time. As far as I see in release notes this is possible under Linux (my OS) since 0.4.0-rc1.

**The problem:** When I try to start nginx I get `403 Forbidden` error.

**Steps to reproduce:**

```
$ docker run --rm --name some-nginx -p "80:80" -v /home/kuzma/workspace/tmp/html:/usr/share/nginx/html:rw nginx
192.168.99.1 - - [31/Aug/2015:12:27:19 +0000] "GET / HTTP/1.1" 403 570 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" "-"
2015/08/31 12:27:19 [error] 6#6: *1 "/usr/share/nginx/html/index.html" is forbidden (13: Permission denied), client: 192.168.99.1, server: localhost, request: "GET / HTTP/1.1", host: "192.168.99.100"
192.168.99.1 - - [31/Aug/2015:12:27:20 +0000] "GET /favicon.ico HTTP/1.1" 403 570 "http://192.168.99.100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" "-"
2015/08/31 12:27:20 [error] 6#6: *1 open() "/usr/share/nginx/html/favicon.ico" failed (13: Permission denied), client: 192.168.99.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/"
```

```
$ namei -l /home/kuzma/workspace/tmp/html/
f: /home/kuzma/workspace/tmp/html/
drwxr-xr-x root  root  /
drwxrwxrwx root  root  home
drwx------ kuzma kuzma kuzma
drwxrwxrwx kuzma kuzma workspace
drwxrwxrwx kuzma kuzma tmp
drwxrwxrwx kuzma kuzma html
```

**docker-machine version:** 0.4.0-rc1
**OS:** Linux

**Comment by wildsurfer** [comment] 2015-09-01 15:51
Am I the only one who have such issue?!

**Comment by mwaaas** [comment] 2015-09-09 09:28
I have the same issue

**Comment by dgageot** [comment] 2015-11-03 20:52
Closing. Duplicate of #1376

**Closed by dgageot** 2015-11-03 20:52 UTC
