### ISSUE TITLE
support b2d on linux host

### ISSUE THREAD

**Issue by chantra** [docker/machine#2110] opened 2015-10-29 05:57 UTC
b2d install just fine on a Linux host, but the homedir is not mounted preventing from mounting volume in the container.
I have a patch for both b2d and docker-machine that would add support.

The issue is alrady logged in https://github.com/boot2docker/boot2docker/issues/1085 . Opening it here for visibility.

**Comment by nathanleclaire** [comment] 2015-10-29 19:22
Dupe of https://github.com/docker/machine/issues/1376

**Closed by nathanleclaire** 2015-10-29 19:22 UTC
