### ISSUE TITLE
Fusion: ip not found for static address

### ISSUE THREAD

**Issue by kvondreth** [docker/machine#2137] opened 2015-11-01 11:39 UTC
With vmware Fusion driver:
When using a static IP (assigned in the dhcp.conf of the vmnet), docker-machine does not find the IP.
Reason is a static IP does not appear in the DHCP lease.
Is there a reason why the driver parses the leases and does not use "vmrun getGuestIPAddress"?
Does docker-machine needs to get the IP when the VM is down?

**Comment by mschygulla** [comment] 2015-11-03 14:09
To my knowledge "vmrun getGuestIPAddress" requires installed VMware guest tools to get the guest IP address. You can not rely on the fact that the tools are always installed (e.g. if you use CoreOS they are not).

**Comment by dgageot** [comment] 2016-01-26 16:55
ping @frapposelli

**Comment by mynameismevin** [comment] 2016-02-26 21:11
I noticed this was due to the TinyCore init system, as dicussed [here](https://github.com/boot2docker/boot2docker/issues/1108). It seems @yyyc514 just added a basic init that open-vm-tools can understand.

However, I noticed that when assigning a static IP via dhcp.conf, `docker-machine` can still control the VM, but when it waits for SSH to become available, it will never connect.

Is anyone actively working on this?

**Comment by kvondreth** [comment] 2016-02-29 18:29
I tested a function using getGuestIPAddress instead of the DHCP leases.
Works, but in the end abandoned the idea of static IP for the docker machine.

**Comment by mrbuk** [comment] 2016-04-10 16:52
I have created a pull request with code that checks also the configuration file where static addresses are configured

https://github.com/docker/machine/pull/3289

With that change the process will look like

1. Try to find MAC -> IP in one of the following files `/Library/Preferences/VMware\ Fusion/vmnet*/dhcpd.conf`
2. If 1. was not successful use the old process the relies on the following files `/var/db/vmware/vmnet-dhcpd-vmnet*.leases`

Maybe the pull request will be accepted or used to implement the functionality.

**Comment by frapposelli** [comment] 2016-04-12 01:09
#3289 has been merged (thanks @mrbuk !), @kvondreth can you double check if the problem is solved with current master?

**Comment by kvondreth** [comment] 2016-04-13 07:33
Problem solved (tested static & dynamic). Thanks all, well done!

**Closed** 2016-04-13 16:10 UTC
Labels: driver/vmwarefusion
