### ISSUE TITLE
Creating machine with azure driver fails to create vm

### ISSUE THREAD

**Issue by cditcher** [docker/machine#3685] opened 2016-08-19 16:57 UTC
I successfully created a machine with the following command:
```
docker-machine create -d azure \
  --azure-ssh-user ops \
  --azure-subscription-id <Your AZURE_SUBSCRIPTION_ID> \
  --azure-open-port 80 \
  machine
```

However a few days later, when attempting to create a new machine in the same resource group i got the following error:

```
Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpd
ate: Failure sending request: StatusCode=404 -- Original Error: Long running operation terminated with status 'Failed': Code="
ImageNotFound" Message="The platform image 'canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in t
he storage profile are correct."
```

All of the components seem to be created (firewall, nic, ip, etc) but the VM itself. Odd. I have tried creating a new machine using a different resource group, but same error. Any thoughts?

**Comment by cditcher** [comment] 2016-08-19 17:42
This seems to be similar to https://github.com/Azure/azure-quickstart-templates/issues/433 . I am trying different combinations of the image name but still no luck.

**Comment by shanegray** [comment] 2016-08-20 18:57
This worked for me

```
docker-machine create -d azure \
  --azure-image canonical:UbuntuServer:16.04.0-LTS:16.04.201608150 \
  --azure-ssh-user ops \
  --azure-subscription-id <Your AZURE_SUBSCRIPTION_ID> \
  --azure-open-port 80 \
  machine
```

**Comment by shanegray** [comment] 2016-08-20 18:57
^^ for northeurope though

**Comment by ahmetalpbalkan** [comment] 2016-08-20 19:58
Duplicate of #3676. This issue is fixed in `master` branch. Default image 15.10 got removed as it EOLd by Canonical.

**Comment by ahmetalpbalkan** [comment] 2016-08-22 18:34
@nathanleclaire please close.

**Closed** 2016-08-22 18:42 UTC

**Comment by cditcher** [comment] 2016-08-23 15:38
I used the same vm that shanegray used and this worked. Thanks! Incidentally, where do I find the list of acceptable vms?

**Comment by ahmetalpbalkan** [comment] 2016-08-23 16:30
@cditcher Try running `azure vm image list` and it will prompt you for publisher/location. You can try `coreos`, `canonical`, `openlogic`, `suse` etc as the publisher input and get a full list of the images.

**Comment by cditcher** [comment] 2016-08-23 18:25
Perfect, thanks!
