### ISSUE TITLE
Error creating machine: Error with pre-create check: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

### ISSUE THREAD

**Issue by Dreampie** [docker/machine#2608] opened 2015-12-17 12:50 UTC
centos  use overlay muti-host networking.
```
docker-machine create -d virtualbox mh-keystore
Running pre-create checks...
Error creating machine: Error with pre-create check: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
```

**Comment by dgageot** [comment] 2015-12-18 07:58
Hi @Dreampie you have to install Virtualbox before you use the virtualbox driver.
Can you run `which VBoxManage`?

**Comment by Dreampie** [comment] 2015-12-18 08:05
I use centos，and must create virtualbox？If already have a virtual machine, and how do create virtualbox？

**Comment by dgageot** [comment] 2015-12-18 08:07
Centos supports native Docker but then you don't need docker-machine.
If you still want to use docker-machine, for eg. to create multiple virtual hosts on your laptop, then you should install VirtualBox, otherwise docker-machine won't work with virtualbox driver.

**Comment by Dreampie** [comment] 2015-12-18 08:12
if machine already is virtualbox,how to do?

**Comment by Dreampie** [comment] 2015-12-18 08:39
https://docs.docker.com/engine/userguide/networking/get-started-overlay/  this only for VirtualBox Docker not for native Docker OS？Centos supports native Docker，so it not need to use docker-machine to impl overlay networking？

**Comment by dgageot** [comment] 2016-01-04 16:13
@Dreampie `docker-machine create -d virtualbox mh-keystore` can only be run on a machine that has VirtualBox installed. This message tells you VirtualBox is not installed. Please install it and try again.

**Comment by dgageot** [comment] 2016-01-13 11:15
Closing. Not a bug

**Closed by dgageot** 2016-01-13 11:15 UTC
Labels: driver/virtualbox

**Comment by Aaqib041** [comment] 2016-06-13 09:05
For me same error , I have installed Virtual box but still error exist. Please help

**Comment by saadaouad** [comment] 2016-08-27 03:10
@Dreampie, @Aaqib041 you have to install VirtualBox : 

```bash
sudo apt-get install virtualbox
```

Then create a machine:
 
```bash
docker-machine create --driver virtualbox default
```

**Comment by Nitinkumar-Gove** [comment] 2016-09-06 19:46
@saadaouad Thank you for your inputs.

**Comment by saadaouad** [comment] 2016-09-07 00:07
@Nitinkumar-Gove No problem :+1:

**Comment by smalot** [comment] 2016-10-09 15:30
Hi All,
Virtualbox is correctly (I Hope) installed on my computer, but I'm encountering this issue.

````
VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
````

````
~# docker-machine --version
docker-machine version 0.7.0, build a650a40
````

Many thanks

**Comment by gameguyr** [comment] 2018-02-01 22:41
I just downloaded VirtualBox for mac osx and it started working fine
https://www.virtualbox.org/wiki/Downloads

**Comment by BillioJeverson** [comment] 2018-06-27 02:08
Hello DreamPie have u manage to solve the problem ? I am having the same problem now . I tried @saadaouad solution but it came up with apt-get not found. please help me out here

**Comment by runstrider** [comment] 2018-07-24 10:06
same error

**Comment by thibmo** [comment] 2018-09-12 14:06
That is because apt is only for Debian-like distributions, like Debian (Duh), Ubuntu, Mint, etc... OSx does NOT have apt......

**Comment by omidbabaeigithub** [comment] 2018-11-09 12:08
I just export PATH=$PATH:$(which vboxmanage) before executing docker-machine create ...

**Comment by etrim** [comment] 2019-01-15 01:47
Install the newest version of docker-machine from github.
https://github.com/docker/machine

**Comment by salimfadhley** [comment] 2019-02-05 18:10
I'm stuck on this as well. VirtualBox is installed and VBoxManage is in my path:

```
sal@gruntyman:~/PycharmProjects/exoduspoint_homework$ docker-machine create --driver virtualbox dev
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
sal@gruntyman:~/PycharmProjects/exoduspoint_homework$ which VBoxManage 
/usr/bin/VBoxManage
```
Any idea what might be going wrong here?

**Comment by albertzubkowicz** [comment] 2019-02-18 13:27
same here. fresh install (according to https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository), path added to ~/.bashrc, but the error persists.

**Comment by wapmorgan** [comment] 2019-03-26 15:15
I think it's important to note:
1. **Remove docker, installed via snap**.
2. Install docker-machine with **official instructions**: https://docs.docker.com/machine/install-machine/

**Comment by gasparyanyur** [comment] 2019-05-01 11:07
```
$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```
OS: Ubuntu - 18.04

```
$ which virtualbox 
/usr/bin/virtualbox
$ which VBoxManage 
/usr/bin/VBoxManage

```

Can not solve this problem!

**Comment by chovy** [comment] 2019-05-02 17:56
I'm still having same issue on 18.04 LTS

**Comment by albertzubkowicz** [comment] 2019-05-11 17:25
I've managed to resolve it by adding user to docker group and restarting system.

**Comment by SundeepPidugu** [comment] 2019-05-15 13:02
@albertzubkowicz  how do i do that ? and i still have the same issue

**Comment by albertzubkowicz** [comment] 2019-05-15 13:18
@SundeepPidugu https://docs.docker.com/install/linux/linux-postinstall/

**Comment by SundeepPidugu** [comment] 2019-05-16 11:07
@albertzubkowicz Can you please post a set of required instructions that i can follow for the same.

**Comment by albertzubkowicz** [comment] 2019-05-18 18:18
@SundeepPidugu just install docker with official instructions and do post-install from above link.

**Comment by sytae** [comment] 2020-01-09 13:36
> I just export PATH=$PATH:$(which vboxmanage) before executing docker-machine create ...

This solved my issue. Thanks!

**Comment by KacperBiedka** [comment] 2020-03-12 11:16
In my case one of the most random fixes happened. After running docker run hello-world it got fixed automatically O.o

**Comment by sakthivelj** [comment] 2020-08-27 02:39
> export PATH=$PATH:$(which vboxmanage)

```
tyrebot@tyrebot-PhotoGAUGE:~$ docker-machine create --driver virtualbox default
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
```
